### ISSUE TITLE
dep-collector -check is failing for knative/client

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#1018]
The reason for the failure is, that an old, installed dep-collector is picked up from $GOPATH/bin without rebuilding is with a new license dependency:

```
+ go get -u github.com/google/licenseclassifier
go: finding github.com/google/licenseclassifier latest
go: downloading github.com/google/licenseclassifier v0.0.0-20190501212618-47b603fe1b8c
go: extracting github.com/google/licenseclassifier v0.0.0-20190501212618-47b603fe1b8c
go: downloading github.com/sergi/go-diff v1.0.0
go: extracting github.com/sergi/go-diff v1.0.0
+ find /home/prow/go -name licenseclassifier
/home/prow/go/pkg/mod/cache/download/github.com/google/licenseclassifier
+ run_go_tool ./vendor/github.com/knative/test-infra/tools/dep-collector dep-collector -check github.com/knative/client/cmd/kn github.com/knative/client/hack github.com/knative/client/pkg github.com/knative/client/pkg/kn/commands github.com/knative/client/pkg/kn/commands/revision github.com/knative/client/pkg/kn/commands/service github.com/knative/client/pkg/kn/core github.com/knative/client/pkg/printers github.com/knative/client/pkg/serving github.com/knative/client/pkg/serving/v1alpha1 github.com/knative/client/test/e2e
+ local tool=dep-collector
++ which dep-collector
+ [[ -z /go/bin/dep-collector ]]
+ shift 2
+ dep-collector -check github.com/knative/client/cmd/kn github.com/knative/client/hack github.com/knative/client/pkg github.com/knative/client/pkg/kn/commands github.com/knative/client/pkg/kn/commands/revision github.com/knative/client/pkg/kn/commands/service github.com/knative/client/pkg/kn/core github.com/knative/client/pkg/printers github.com/knative/client/pkg/serving github.com/knative/client/pkg/serving/v1alpha1 github.com/knative/client/test/e2e
2019/06/22 06:53:47 Error creating license classifier: cannot register licenses: EOF
```

**Comment by adrcunha** [comment]
It's easy to check if the dep-collector tool is running using an old license classifier because of the error message `cannot register licenses`. The newest version would say `cannot register licenses from`.

**Comment by adrcunha** [comment]
I tried rebuilding prow-tests, the "old" dep-collector/licenseclassifier is there.

**Comment by adrcunha** [comment]
Probably it's best always building dep-collector with the latest sources from github.com. Otherwise a new license that's not covered by the old binary will cause the check to fail.

**Comment by adrcunha** [comment]
Also, because knative/client doesn't vendor test-infra/tools/dep-collector, the license checking function will try to use a local binary.

**Comment by rhuss** [comment]
> Also, because knative/client doesn't vendor test-infra/tools/dep-collector, the license checking function will try to use a local binary.

Even when `knative/client` would vendor the dep-collector, a locally installed `dep-collector` will always take precedence.

**Comment by adrcunha** [comment]
> Even when `knative/client` would vendor the dep-collector, a locally installed `dep-collector` will always take precedence.

Yes, that's expected. Without a local binary, because knative/client doesn't vendor dep-collector, the check function will fail.
