### ISSUE TITLE
Fix permission in prow/boskos/permissions.sh

### ISSUE THREAD

**Issue by dushyanthsc** [knative/test-infra#1026]
Executing prow/boskos/permissions.sh on a newly created GCP project is failing with:

"ERROR: Policy modification failed. For a binding with condition, run "gcloud alpha iam policies lint-condition" to identify issues in condition.
ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Group 89939 does not exist.
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: Group 89939 does not exist."

This issue is created to fix the script.

**Comment by dushyanthsc** [comment]
The current work-around is to add the "knative-productivity-admins@googlegroups.com" manually to the project.

**Comment by adrcunha** [comment]
Wait, you can't add knative-productivity-admins@ to the project using the script, but you can do it in the console?

**Comment by dushyanthsc** [comment]
Yes, that is correct.

**Comment by adrcunha** [comment]
@dushyanthsc  `gcloud projects add-iam-policy-binding knative-boskos-50 --member group:knative-productivity-admins@googlegroups.com --role roles/editor` worked for me, so if it's a permission issue, it's on the user not on the script. Can you try that?

**Comment by coryrc** [comment]
This is a bug in the script with using the variable "GROUPS". I will fix this with issue 1074 (don't know how to link it, sorry).
