### ISSUE TITLE
Prow's milestone command stopped working

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#1029]
The `/milestone` command used to work in https://github.com/knative/eventing issues, but it stopped working a few weeks ago. Here's a recent example of a `/milestone` command being ignored: https://github.com/knative/eventing/issues/1214

**Comment by adrcunha** [comment]
From SD logs:

https://pantheon.corp.google.com/logs/viewer?project=knative-tests&minLogLevel=0&expandAll=false&timestamp=2019-06-25T03%3A18%3A35.594000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2019-06-25T02%3A19%3A35.688Z&dateRangeEnd=2019-06-25T03%3A19%3A35.688Z&interval=PT1H&resource=container%2Fcluster_name%2Fprow%2Fnamespace_id%2Fdefault&scrollTimestamp=2019-06-25T03%3A19%3A15.000000000Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.zone%3D%22us-central1-f%22%0Aresource.labels.pod_id%3D%22hook-7dfbc8bb87-cc82q%22%0Aresource.labels.project_id%3D%22knative-tests%22%0Aresource.labels.cluster_name%3D%22prow%22%0Aresource.labels.container_name%3D%22hook%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.instance_id%3D%226141739562598386007%22%0Atimestamp%3D%222019-06-25T03%3A17%3A53.000000000Z%22%0AinsertId%3D%2217a9gcjg17bz7rp%22

```
2019-06-24 20:17:53.000 PDT
{"component":"hook","file":"prow/hook/events.go:385","event-GUID":"cda6f3f0-96f7-11e9-9b6e-542a530fa41e","error":"return code not 2XX: 404 Not Found","func":"k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1","msg":"Error handling GenericCommentEvent.","author":"adrcunha","url":"https…
Expand all | Collapse all {
 insertId:  "17a9gcjg17bz7rp"  
 jsonPayload: {
  author:  "adrcunha"   
  component:  "hook"   
  error:  "return code not 2XX: 404 Not Found"   
  event-GUID:  "cda6f3f0-96f7-11e9-9b6e-542a530fa41e"   
  event-type:  "issue_comment"   
  file:  "prow/hook/events.go:385"   
  func:  "k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1"   
  level:  "error"   
  msg:  "Error handling GenericCommentEvent."   
  org:  "knative"   
  plugin:  "milestone"   
  pr:  1214   
  repo:  "eventing"   
  url:  "https://github.com/knative/eventing/issues/1214#issuecomment-505264610"   
 }
 labels: {
  compute.googleapis.com/resource_name:  "gke-prow-prow-node-pool-55195415-09rp"   
  container.googleapis.com/namespace_name:  "default"   
  container.googleapis.com/pod_name:  "hook-7dfbc8bb87-cc82q"   
  container.googleapis.com/stream:  "stderr"   
 }
 logName:  "projects/knative-tests/logs/hook"  
 receiveTimestamp:  "2019-06-25T03:17:58.530418173Z"  
 resource: {
  labels: {
   cluster_name:  "prow"    
   container_name:  "hook"    
   instance_id:  "6141739562598386007"    
   namespace_id:  "default"    
   pod_id:  "hook-7dfbc8bb87-cc82q"    
   project_id:  "knative-tests"    
   zone:  "us-central1-f"    
  }
  type:  "container"   
 }
 severity:  "ERROR"  
 timestamp:  "2019-06-25T03:17:53Z"  
}
```
