### ISSUE TITLE
Provide compute resource requirements per prow job.

### ISSUE THREAD

**Issue by dushyanthsc** [knative/test-infra#1031]
This issue is created to investigate if its feasible to provide compute resource requirements (cpu and memory) at a per job level. We currently have setup LimitResources at a test-pods namespace level, however each job would have different characteristics and probably makes sense to provide the resource requirements at job level.

**Comment by chaodaiG** [comment]
It's already supported, see this example: https://github.com/knative/test-infra/blob/c270971a47b2f418c0a2619f2c03f516528caff2/config/prow/config_knative.yaml#L180
