### ISSUE TITLE
Prow job config generator supports generating multiple jobs with same name

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1042]
Currently Prow job config generator only supports generating one job for the same job name, which doesn't fit some of the upcoming jobs. For example, running perf test in different regions as #1041 , and vanity URL (`knative.dev`) migration need different jobs supporting old release branches.
It would be nice if prow job config generator can support generating multiple jobs with same name, ideally in a generic way.

**Comment by adrcunha** [comment]
Looks like the generator needs to be rewritten. :)

**Comment by chaodaiG** [comment]
done via #1124
