### ISSUE TITLE
Eventing dot release job failed to notice new commit to release branch

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#1049]
Commit https://github.com/knative/eventing/commit/90c5aca9fded347baafd47b5c3c537932aac5864 was pushed to branch `release-0.6` yesterday morning, before the eventing-dot-release job ran.

The job [ran ~~yesterday afternoon~~ this morning](https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-eventing-dot-release/1143457969216688128/?log#log) and detected no new commits since the `v0.6.0` tag: 

```
Dot release requested
Last release is v0.6.0
Last release branch is release-0.6
From https://github.com/knative/eventing
 * [new branch]        release-0.6 -> upstream/release-0.6
*** Branch release-0.6 is at commit d123d12f7c6b9c51298719c67cd9745571abade2
*** Branch release-0.6 has no new cherry-picks since release v0.6.0
*** No dot release will be generated, as no changes exist
```

But there were definitely new commits:  https://github.com/knative/eventing/compare/v0.6.0...release-0.6

/cc @adrcunha

**Comment by adrcunha** [comment]
PR 1452 was merged on June 24 1:11 PM PDT.
dot-relase ran on June 25 2:56 AM PDT, log is https://storage.googleapis.com/knative-prow/logs/ci-knative-eventing-dot-release/1143457969216688128/build-log.txt
d123d12f7c6b9c51298719c67cd9745571abade2 is the commit before PR 1452, from May 14.

**Comment by adrcunha** [comment]
During initialization, I see no difference between

**Comment by adrcunha** [comment]
This is hard to reproduce, so I'll consider that #1053 fixed it. If that's not true, we'll work on it more once it happens again.
