### ISSUE TITLE
Enable Prow for new Knative repo Caching

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#106]
@adrcunha, can you pls document steps on how to onboard a new Knative repo to Knative Prow?

**Comment by adrcunha** [comment]
Steps are already documented at https://github.com/knative/test-infra/blob/master/ci/prow/prow_setup.md%23setting-up-prow-for-a-new-repo

**Comment by adrcunha** [comment]
I'll favor the issue in knative/caching since this is strictly related to that repo.
