### ISSUE TITLE
Evaluate moving webhook-apicoverage to pkg repo

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1060]
test-infra and pkg repos are both vendored in most of other repos, the dependency between these two could be a problem for other repos. webhook-apicoverage has quite some dependencies on pkg repo, which probably should be move to pkg repo for breaking the dependency

**Comment by chaodaiG** [comment]
FYI @mattmoor since you ran into this problem earlier today while working on this: https://github.com/knative/serving/pull/4546

**Comment by adrcunha** [comment]
@chaodaiG please take this in consideration during Q3 work.
