### ISSUE TITLE
Autoscaling or alert for high usage of janitors/boskos

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#1080]
Should be an easy alert in Grafana.

We will want an alert if free projects drops very low.
May also want an alert for janitors fully occupied, but also may not want that.

/assign @chaodaiG 
Please consider for Q3 planning.

**Comment by adrcunha** [comment]
@chizhg the `/lifecycle` command in the comment from the robot wasn't recognized. I wonder why.

**Comment by coryrc** [comment]
This is superseded by #1624 
/close
