### ISSUE TITLE
Could not resolve host: github.com in Prow job

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#1082]
I've seen this error message a couple of times. Not sure if additional logic is needed, but it seems the test retryer can handle it?

Log link:
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_test-infra/954/pull-knative-test-infra-integration-tests/1144796790348845057

/cc @chaodaiG

**Comment by chaodaiG** [comment]
AFAIK we have no control over `git clone` logic, so if there is a retry it should be handle in Prow. 
@krzyzacy, have you seen this kind of error before?

**Comment by krzyzacy** [comment]
@stevekuznetsov @cjwagner ^^

seems just network flakes?

**Comment by chaodaiG** [comment]
I think it's network flakes too, just want to make sure, as this should also happen in k8s if that's the case

**Comment by chaodaiG** [comment]
I have scanned all failed jobs today and from yesterday, the same error hasn't happened since, so it seems like a network flakiness on last Friday

**Comment by chaodaiG** [comment]
Since Cory is interested
/assign @coryrc

**Comment by stevekuznetsov** [comment]
Yeah so it's highly suggested to run DNS caches on high throughput k8s clusters -- are you running any?

**Comment by chaodaiG** [comment]
@stevekuznetsov , this is a good point. afaik we are not using DNS caches, are you referring to something like this? https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns

**Comment by chaodaiG** [comment]
Another input, just scanned all test logs in past month, it started happening since 06/22/19, which was right after we switched from bootstrap to pod-utils.

**Comment by stevekuznetsov** [comment]
I am fairly certain the `clonerefs` container is based on Alpine (@cjwagner @fejta please confirm) which would be using the `musl`-based resolver unlike the `glibc` one in `bootstrap.py`, as documented here: https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS

I would tentatively point the blame at that? But you should run DNS caches either way :)

**Comment by adrcunha** [comment]
I tried to find k8s DNS cache setting in prow/cluster, but it's not there. Maybe I'm looking in the wrong place?

```
test-infra/prow$ grep -ri dns
config.yaml:        dns:
plugins.yaml:  - kubernetes/dns
getting_started_deploy.md:Point the DNS record for your domain to point at that ingress IP. The convention
cmd/mkbuild-cluster/main.go:		if _, err = c.ListPods("k8s-app=kube-dns"); err != nil {
```

**Comment by chaodaiG** [comment]
@adrcunha I think it's an addon for prow cluster, see the link in my previous comment

**Comment by adrcunha** [comment]
Yes, it's a kubernetes add-on. I was just expecting that, if it's a recommended setting, it would be documented/configured for k8s and thus available in the k8s repo, so we could base our config on that.

**Comment by chaodaiG** [comment]
I see. @stevekuznetsov , how was DNS cache enabled on k8s Prow cluster?

**Comment by chaodaiG** [comment]
Analyzed all jobs in test-infra and serving since 06/30, there were 25 out of 964 runs failed for this

**Comment by stevekuznetsov** [comment]
One option is [here](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns) but I cannot vouch for it specifically.

**Comment by chaodaiG** [comment]
It magically stopped happening since 07/01, closing this issue
/close

**Comment by adrcunha** [comment]
@chaodaiG just because you closed it: https://storage.googleapis.com/knative-prow/logs/ci-knative-serving-auto-release/1151168386852458496/build-log.txt

**Comment by chaodaiG** [comment]
It did start happening 40/6781 times since 07/12. Reopening the issue since it's still annoying
@coryrc  for reference

**Comment by stevekuznetsov** [comment]
I mean if you don't fix the DNS issue it will just continue happening indefinitely.

**Comment by chaodaiG** [comment]
@stevekuznetsov , thanks for reminding, we will investigate and act appropriately

**Comment by chaodaiG** [comment]
Followed 3 of the jobs failed at the same time this morning:
(Create time: 2019-07-17 07:29:13 -0700 PDT)
pr-logs/pull/knative_serving/4787/pull-knative-serving-build-tests/1151498938310725632
pr-logs/pull/knative_serving/4787/pull-knative-serving-go-coverage/1151498938314919940
pr-logs/pull/knative_serving/4787/pull-knative-serving-upgrade-tests/1151498938314919938

At the moment there was no node available for scheduling new pods, so all 3 jobs were created on freshly created nodes, since we have autoscale turned on. 

Turned off autoscale and see if it helps

**Comment by chaodaiG** [comment]
Scanned Prow jobs from test-infra and serving in past week on 07/22/2019, the last appearance of this error was 11:44:44AM on 07/17/2019. I'm having pretty good confidence that turning off autoscale fixed the problem

**Comment by Fredy-Z** [comment]
Completely disabling autoscale may not be a long-term solution. We'll have to increase the number of nodes manually whenever there is abruptly high load, and it is highly possible that a lot of nodes will have low utilization after the peak. The problem may become more serious as the project evolves.
@stevekuznetsov May I ask if Kubernetes' Prow cluster has `autoscaling` enabled?

**Comment by adrcunha** [comment]
I believe the answer is "no" and that prow.k8s has enough nodes to handle utilization peaks and doesn't care about them being idle. But I might be wrong.

**Comment by stevekuznetsov** [comment]
Please just deploy the DNS caches. I don't see why that isn't the simple, direct answer to this question.

**Comment by chaodaiG** [comment]
@stevekuznetsov , to be honest, I'm not quite convinced that DNS caches can solve this problem. Based on my investigation, the root cause of this issue is network not ready on newly provisioned nodes, so the problem happened on the first few DNS lookups on the fresh nodes. And based on this [doc](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/#introduction), DNS cache looks up caches on same node, so it wouldn't work as there should be no cache yet. 

However, if you can prove I'm wrong, I would be more than happy to explore it further.

**Comment by stevekuznetsov** [comment]
You're saying you see this only at node boot-time and never again after the fact?

**Comment by coryrc** [comment]
@stevekuznetsov Correct

**Comment by cjwagner** [comment]
Anecdotally I've seen the same.
I added a node pool to a gke cluster the other day and immediately scheduled a ProwJob pod to it. The job failed with `Could not resolve host: github.com`, but since then I haven't seen that reoccur.

**Comment by chaodaiG** [comment]
@cjwagner , is autoscaling turned on in the cluster that runs k8s Prow workloads?

**Comment by cjwagner** [comment]
> @cjwagner , is autoscaling turned on in the cluster that runs k8s Prow workloads?

No

**Comment by chaodaiG** [comment]
> > @cjwagner , is autoscaling turned on in the cluster that runs k8s Prow workloads?
> 
> No

Thanks! Then I think I can close this issue for now, since I'm pretty confident that it's fixed by turning off autoscaling. How to make the error disappear with autoscaling turned on should be explored in a separate issue if we need to.
