### ISSUE TITLE
Knative oncall should have all required permissions

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1090]
Knative oncaller isn't necessarily a test-infra admin, thus sometimes need escalation for certain operations such as updating/patching Prow cluster. Should explore ways of automatically assign/unassign sufficient roles for oncallers

**Comment by adrcunha** [comment]
My major concern is that a service account able to do `gcloud projects add-iam-policy-binding` in a job is a pretty powerful one, although we could have one that's just able to change roles. Let's discuss pros and cons.

/assign @chaodaiG

**Comment by adrcunha** [comment]
Currently all oncallers have the required permissions through a custom role, without the need of being owners OR a custom service to admin that. I consider this fixed.

/close
