### ISSUE TITLE
Preventing Boskos from running out of resources

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1102]
Boskos running out of resources has been a recurring issue causing integration tests failures globally: https://github.com/knative/test-infra/issues/964, https://github.com/knative/test-infra/issues/875, https://github.com/knative/test-infra/issues/638

This issue is created for tracking progress of several works aiming at solving this problem:
- Investigate why it takes janitor ~40 minutes cleaning up Boskos project #946 
- Autoscaling or alert for high usage of janitors/boskos #1080 
- Kubetest waits for Boskos instead of fail when Boskos ran out #1101

**Comment by chizhg** [comment]
The relevant issues have all been fixed.
