### ISSUE TITLE
Branch name is missed in periodic jobs for releases

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#1104]
It started from the PR to replace `bootstrap` with `podutil` - #989 , now all periodic jobs are running against the `master` branch.

One example error job config:
https://github.com/knative/test-infra/blob/9ccec33ae7eb8ede1bdffeb3dc50b0b6ec7b6c88/ci/prow/config.yaml#L1864

The right job should contain `release-x.x` like below, so that prow will be able to know which branch to check out:
https://github.com/knative/test-infra/blob/86f1fe74ca578734829a7fb2efeda9ab3a258f0e/ci/prow/config.yaml#L1969

**Comment by chaodaiG** [comment]
Thanks at @Fredy-Z for finding this out, PR out #1106
