### ISSUE TITLE
Set correct org name for dot-release and auto-release jobs

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#1136]
Right now in `scripts/release.sh`, the `org` name is hard coded as `knative`. But `cloud-run-events` is under `GoogleCloudPlatform`, which will cause `dot-release` and `auto-release` jobs to fail. We'll need to support setting `org` name dynamically by adding an extra flag.

**Comment by adrcunha** [comment]
You mean fixing this (log from auto-release job):

```
Activated service account credentials for: [prow-job@knative-releases.iam.gserviceaccount.com]
Remote upstream URL is ''
Setting remote upstream URL to 'https://github.com/knative/cloud-run-events'
Auto release requested
Fetching upstream
fatal: could not read Username for 'https://github.com': No such device or address
error: Could not fetch upstream
error: error fetching branches/tags from remote
```
