### ISSUE TITLE
Separate each service/deployment config into it's own file

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1164]
Currently we have Prow config files that contains multiple services/deployments, for example `boskos`, `janitor`, `reaper` in https://github.com/knative/test-infra/blob/master/ci/prow/boskos/config.yaml. This approach makes it not easy to roll back from bad config applied by `kubectl apply -f config.yaml`, as `kubectl delete -f config.yaml` would delete everything in the config, while we might only need to delete one of them. 
Proposing splitting them up to have a single service/deployment in each file, like in this example: https://github.com/knative/test-infra/blob/master/ci/prow/boskos/config.yaml

[BONUS] Have a proper strategy of applying them in batches

**Comment by adrcunha** [comment]
/assign @chaodaiG 

The config can be split and put into a separate subdirectory. A `make` target can make it easier to apply all at once. Other operations (like delete), full or individual, should be done by hand to avoid mistakes.
