### ISSUE TITLE
Change the build log link in the alert message to spyglass link

### ISSUE THREAD

**Issue by yt3liu** [knative/test-infra#1167]
Currently the build log link the alert message links to the GCS bucket. Update this to use the spyglass link to get summary of the error. 

/kind monitoring

**Comment by srinivashegde86** [comment]
According to the schema, we should be storing the link to the build-log file - https://github.com/knative/test-infra/blob/81861c7c2060af68e3dbdc72bcd3a2f0584566d2/tools/monitoring/mysql/schema.sql#L27

But, it looks like we are actually storing the path to the GCS dir instead. When sending the alert, we are just using this and hence, it points to the GCS dir.

**Comment by srinivashegde86** [comment]
We either need to update the storage to start storing the URL instead of the GCS path, or update the schema to also store the url with the GCS path
