### ISSUE TITLE
Add monitoring to the monitoring app

### ISSUE THREAD

**Issue by yt3liu** [knative/test-infra#1168]
Currently there's no monitoring on the [monitoring app](https://github.com/knative/test-infra/tree/master/tools/monitoring). Add some monitoring to make sure the app is up-and-running as expected in case of no alerts. 

Potential approaches: stackdriver logging, Kubernetes health check (liveness probe)

/kind monitoring

**Comment by chaodaiG** [comment]
Done by https://github.com/knative/test-infra/issues/1469
/close
