### ISSUE TITLE
stats.knative.dev is stale

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#1179]
Looks like there's no new data since 7/1.

https://stats.knative.dev/d/7/contributing-companies?orgId=1&from=now-1y&to=now&var-period=d28&var-repogroup_name=All

**Comment by adrcunha** [comment]
Restarting the backfill and cron jobs didn't help. The link above still shows data until 7/1. Something seems to be wrong because:

* the graph above shows 0 contributing companies until 5/30;
* the dashboard above doesn't exist in https://knative.teststats.cncf.io, which clearly shows that our instance is outdated;

**Comment by Fredy-Z** [comment]
It seems this issue has been "fixed"? The dashboard now shows data till yesterday.

**Comment by adrcunha** [comment]
Yes, indeed there's new data, probably captured by the cron job. However, the graph is still weird: no data at all from 6/6 to 7/23.

**Comment by adrcunha** [comment]
The data is being updated, so the dashboard is not stale anymore.
