### ISSUE TITLE
Implement the cluster creation library for Test Infra 2.0

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#1186]
This library should provide the basic functionality for the creation of test clusters for E2E tests, on Prow (using boskos) and locally.

**Comment by adrcunha** [comment]
Chao is looking into talking to boskos.

**Comment by chaodaiG** [comment]
I think I can close this issue as it's feature complete, WDYT? @adrcunha

**Comment by adrcunha** [comment]
Sure. Thanks for all the work.

/close
