### ISSUE TITLE
Propose: add an option --skip-prepare-cluster in e2e-test

### ISSUE THREAD

**Issue by zrss** [knative/test-infra#122]
## Expected

i have a kubernetes cluster that is bootstrapped by `kubeadm`, but currently, there is no way to let knative components run e2e on it

**Comment by adrcunha** [comment]
The behavior you need can be achieved with `--run-tests`. If you just want to run the e2e tests, `go test` is enough. How to run the e2e tests is documented in the `README.md` files (e.g., in serving), although `--run-tests` is documented in the script headers only (I encourage you to move it to the README files if you think it would have solved the scenario of this issue).

**Comment by zrss** [comment]
thanks for reply

i hit this case by `./hack/release.sh` ... and actually we should have a k8s cluster to run the e2e test right ? [https://github.com/knative/serving/blob/master/test/README.md#running-end-to-end-tests](https://github.com/knative/serving/blob/master/test/README.md#running-end-to-end-tests)

> you need to have a running environment that meets the e2e test environment requirements,

**Comment by adrcunha** [comment]
You can use `--skip-tests` to skip running the e2e tests in `release.sh`. And yes, you should have a k8s cluster to run the e2e tests, as explained in the docs.

**Comment by zrss** [comment]
yes, i can skip the test though `--skip-tests` to skip all the tests (include e2e), but how about i have a k8s cluster rather then a GCP cluster, maybe there can be a choice that i can skip the step to setup/create a cluster from the GCP

**Comment by adrcunha** [comment]
Looks like there's some confusion here. `release.sh` doesn't create a cluster; `e2e-tests.sh` does, and you can skip that using `--run-tests` or using `go test` directly as explained above (in both cases you still need to set up the env vars for your test to run).

**Comment by zrss** [comment]
that's correct. `e2e-tests.sh` create a cluster not `release.sh`, but if i already have a cluster, can there be an option like `skip-prepare-cluster` to skip creating a cluster in `e2e-tests.sh` ?

**Comment by adrcunha** [comment]
Such option is `--run-tests`.

**Comment by zrss** [comment]
thanks adrcunha kindly explain

i check again the `e2e-test.sh` code, i find the env that u said, if u mean that ~

```
export K8S_USER_OVERRIDE=[your k8s user]
export K8S_CLUSTER_OVERRIDE=[your k8s cluster]
export DOCKER_REPO_OVERRIDE=[your docker repo]

./e2e-test.sh --run-tests
```

though if there is a well-documented about how to launch a e2e test in existing k8s cluster maybe more attractive

thanks anyway

**Comment by adrcunha** [comment]
Assuming you're working on knative/serving, that would be https://github.com/knative/serving/blob/master/test/README.md#running-end-to-end-tests

**Comment by zrss** [comment]
happy to see it 😆
