### ISSUE TITLE
Prow project plugin is not configured

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#1240]
We'd like to use the [Prow project plugin](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/project/project.go) but it's not configured. Here's [the configuration struct](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/config.go#L425) and [an example config](https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml#L302).

**Comment by adrcunha** [comment]
/assign @Fredy-Z 

Hey Chi, is it something you could work on?

**Comment by Fredy-Z** [comment]
Sure, I can work on it.

**Comment by Fredy-Z** [comment]
Update the Prow config.
