### ISSUE TITLE
Coverage shouldn't fail if the baseline it compares to failed

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1242]
Currently presubmit coverage test looks for latest master coverage result and compares against it, the latest master coverage result is produced by postsubmit coverage test. Normally this flow works, but when there is one postsubmit coverage test failed, presubmit coverage test would fail due to not able to find baseline. An example is here: https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_eventing/1658/pull-knative-eventing-go-coverage/1159243486059302912

Currently it's fine as coverage is optional, so PRs can still merge and keep generating new baselines. But it's not hard to imagine this could block all PRs from merging once it becomes required. We should either retry postsubmit or allow presubmit comparing with earlier runs, to make this flow more resilient

**Comment by steuhs** [comment]
We used to go for earlier post submit when the master head fails, it was modified to tolerate minor failures. However the modification does not take into consideration of all tests fail due to changing directory. (see #1241). I am working on a fix for it.
