### ISSUE TITLE
Regional clusters are using 3X resources than expected

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1247]
Currently regional clusters are created by default for e2e tests, each of them by default spawns 3 random zones, and provisions a copy of what's asked in each zone, thus there are 3X resources provisioned in each cluster than we expected.

For example: in an [e2e test](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_test-infra/1245/pull-knative-test-infra-integration-tests/1159540568989110272) with standard cluster creation, the relevant parameters are:
`--min-nodes=1 --max-nodes=3 --region=us-central1 --machine-type=n1-standard-4 --num-nodes=1`
We would expect 1 node of `n1-standard-4` provisioned for this cluster, but actually there were 3 nodes provisioned, 1 in each zones of `us-central1-a`, `us-central1-b`, and `us-central1-f`, and description says 1-3 nodes per region.
![Screen Shot 2019-08-08 at 2 23 19 PM](https://user-images.githubusercontent.com/45011425/62738862-37ba0580-b9e8-11e9-91c1-655a96e60783.png)

And if we supply a zone to make this a zonal cluster, it will be provisioned as expected: 1 node as in the example above. Which results in inconsistency between tests using regional and zonal clusters.

More details about `gcloud` params are available here:
https://cloud.google.com/sdk/gcloud/reference/container/clusters/create

**Comment by adrcunha** [comment]
/assign @chaodaiG 

The idea behind regional test clusters by default is having higher availability and making them bit less stockout prone. Tests that require specific regions/zones can do so by setting the corresponding environment variables. Also, the clusters are short lived so the cost shouldn't be an issue. I suggest syncing up with @mattmoor about this, who originally proposed this approach. If it's still valid (and I think it is), I don't think there's anything to do here.

**Comment by chaodaiG** [comment]
This is actually intended 

/close
