### ISSUE TITLE
flaky-test-retryer: based on more up-to-date stats with broader spectrum

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1250]
Currently flaky-test-retryer is based on the same report flaky-test-reporter produces daily at 5AM each morning, which could be outdated later in the day, and misses lots of retries which could happen. The report only scans past 10 runs in master, which could also miss flaky tests that happen less frequently.

Propose to improve this by:
- set up a cron job runs a variant of flaky-test-reporter hourly, this variant does everything but not reporting to github or slack
- the new cron job scans past 20 or 30 runs instead of 10
- flaky-test-retryer based on the artifacts of this new job

The other pros I can imagine, is that if a single run failed, going back 1 hour should still be fine, which is much better than going back 1 day as where we stand today

**Comment by chaodaiG** [comment]
fyi @TrevorFarrelly  in case you feel bored

**Comment by adrcunha** [comment]
Just in case Trevor leaves before getting bored. :)

/assign @chaodaiG
