### ISSUE TITLE
Support for passing timeout duration to go_test_e2e

### ISSUE THREAD

**Issue by navidshaikh** [knative/test-infra#1259]
New e2e tests added for one of `kn` PR requires updating service in sync multiple times summing the total time taken for e2e go beyond the default timeout duration (10minutes) in `go test`. 

https://golang.org/cmd/go/#hdr-Testing_flags
```
-timeout d
    If a test binary runs longer than duration d, panic.
    If d is 0, the timeout is disabled.
    The default is 10 minutes (10m).
```

In this kn [PR](https://github.com/knative/client/pull/345), e2e tests are failing complaining (ref [logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/345/pull-knative-client-integration-tests/1161176727611772928#0:build-log.txt%3A1060) )
```
*** Test killed with quit: ran too long (10m0s).
```

Can we support adding parameter to library function `go_test_e2e` for timeout duration ?

**Comment by Fredy-Z** [comment]
You can pass the `-timeout=xx` on this line:
https://github.com/knative/eventing/blob/539d72ec0417bd7127e64bac09a131316251d395/test/e2e-tests.sh#L33

Example:
https://github.com/knative/eventing/blob/539d72ec0417bd7127e64bac09a131316251d395/test/e2e-tests.sh#L33

**Comment by navidshaikh** [comment]
@Fredy-Z : Thanks! :+1:
