### ISSUE TITLE
dot-release is running the ./hack/release.sh in master branch

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1262]
`eventing-contrib` repo is doing a dot-release but the job ended up with an error.

From the job logs https://prow.knative.dev/log?job=ci-knative-eventing-contrib-dot-release&id=1161353664162435072, we can see the error is `2019/08/13 19:14:03 Error enumerating files: lstat github/config/: no such file or directory`. However, `github/config/` is a path written in the `./hack/release.sh` of master branch but not 0.8 branch.

Our dot-release job should use `./hack/release.sh` in branch 0.8, instead of master.

/cc @adrcunha 

FYI @chaodaiG since he found the reason of this bug.

**Comment by adrcunha** [comment]
The way the release script currently works it runs indeed from the master branch.

The workaround is to manually create a dot-release job, and update it to use the branch before starting it. This will be addressed in test-infra 2.0.

**Comment by adrcunha** [comment]
New release published successfully:

https://prow.knative.dev/log?job=ci-knative-eventing-contrib-dot-release&id=1161389776184545280

/close

**Comment by chizhg** [comment]
/unassign @adrcunha 

As test-infra 2.0 was not launched as planned, this issue still needs to be addressed.

/reopen
