### ISSUE TITLE
Update project names in project plugin config

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#1265]
Some observations of the project plugin based on my testing in https://github.com/knative/eventing/issues/1461:

* It only supports project names without spaces. I'm not sure how project names like [KEP Implementation Tracking](https://github.com/kubernetes/test-infra/blob/9501e29276a5e98eeb809684ee639f7888ffcca8/prow/plugins.yaml#L316) work. Maybe they don't? I can't find any usages of the `/project` command in other repos.
* Spaces are supported in column names.
* Project names are case insensitive, but column names are not.
* Projects that aren't listed in the config can still be used but require a column name to be specified.

I renamed "Performance: Measurement" to "perf/measurement" to work with the plugin. I'll also get the admins to create the eventing-project-maintainers team. Once that's done, I'll submit a PR to update the project name and team id.

**Comment by Fredy-Z** [comment]
I have changed the name in the plugin to "perf/measurement", so you can use `/project perf/measurement` to add the issue as `To do` by default.
For the things listed here, they do not seems to be "features", I'm looking into the source code to see if I can make a quick fix.

**Comment by adrcunha** [comment]
The name was fixed https://github.com/knative/test-infra/pull/1266

**Comment by chizhg** [comment]
We should fix this plugin and push it to upstream.

/cc @chaodaiG

**Comment by chaodaiG** [comment]
The PR for allowing spaces in project name was merged, and we should be able to do `/project "Performance: Measurement"` after we update Prow next week
