### ISSUE TITLE
Write script to file quote increase requests for all boskos project

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#1270]
Right now if we want to increase quotas for boskos projects, we'll have to manually go to each project's Quota page, change the quota, and submit the request.

Since there are already 70 boskos projects, that would be a lot of manual work. We need a script to automatically do it for us.

**Comment by adrcunha** [comment]
I'm afraid this can't be automated, as the documentation only points to the manual process:

https://cloud.google.com/compute/quotas

**Comment by Fredy-Z** [comment]
Ah, then we may have one more reason to look into Mason.

**Comment by adrcunha** [comment]
I assume you mean https://github.com/kubernetes/test-infra/tree/master/boskos/mason

If so, I'm not sure I picture how quotas fit into the Mason flow.

**Comment by Fredy-Z** [comment]
By using Mason, we will be able to create multiple clusters within the same project, that means we will not need to always increase the number of Boskos projects as Knative grows. I'm not sure how often we will need to increase the quota, but if one day when we have 200 boskos projects, that would be even more work to do.

But these are just my two cents.

**Comment by adrcunha** [comment]
Got it. Indeed, an ever-growing list of Boskos projects is not sustainable. For the purposes of this bug then I think Mason is not the right solution, so I'll close it as unfeasible.

/close
