### ISSUE TITLE
'Changes' link points to Kubernetes repository

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#131]
When I visit: https://testgrid.knative.dev/knative-serving#continuous

**Comment by dprotaso** [comment]
I see `Changes` beside `Overall` and the test underneath

**Comment by srinivashegde86** [comment]
Looks like they are supposed to show changes between the last 2 columns to aid in figuring out the issue for the failures. but, it is pointing to the kubernetes/kubernetes instead of knative/serving.

**Comment by adrcunha** [comment]
That's weird. This is not part of Testgrid, because the app was not updated, so it was probably part of the data. However, it's now gone. Anyway, this seems like another variant of #75.
