### ISSUE TITLE
automatically file git issues to track flaky tests

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#132]
This way, working group triage will get the visibility to flaky tests and assign proper owners. 
The bug should provide data points about flakiness per test. Prefer one issue per flaky test.

**Comment by adrcunha** [comment]
We can have a daily job that inspects the CI test jobs and files issues accordingly. Most of this work is already done in the latency and API coverage jobs.

**Comment by adrcunha** [comment]
By "inspects the CI test jobs" I mean parsing the junit XML files containing the test results.

**Comment by chaodaiG** [comment]
thanks for clarification!

**Comment by chaodaiG** [comment]
I consider this work is done, can we close this issue? @jessiezcc
