### ISSUE TITLE
E2E tests fail with go 1.13

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1329]
When running serving tests with go1.13, they would fail complaining flags provided but not defined. 
For example: 
```
# clone knative/serving
go test -v -tags=e2e -count=1 ./test/e2e -run ^TestAutoscaleUpDownUp$
```
Got errors:
```
flag provided but not defined: -test.v
```

**Comment by srinivashegde86** [comment]
probably related - https://github.com/golang/go/issues/31859

**Comment by adrcunha** [comment]
This seems to be caused due to the way flags are parsed in serving/test/e2e:

```
$ go test -v -count=1 ./pkg/... -run ^TestAutoscaleUpDownUp$
testing: warning: no tests to run
PASS
ok      knative.dev/serving/pkg/activator       0.294s [no tests to run]
?       knative.dev/serving/pkg/activator/config        [no test files]
testing: warning: no tests to run
...
$ go test -v -tags=e2e -count=1 ./test/e2e -run ^TestAutoscaleUpDownUpX$
flag provided but not defined: -test.v
Usage of /tmp/go-build413005213/b001/e2e.test:
...
```

**Comment by adrcunha** [comment]
We're running go 1.12 on Prow. The issue described happens with go 1.13rc1.

**Comment by adrcunha** [comment]
istio is facing the same issue: https://github.com/istio/istio/issues/16797

**Comment by adrcunha** [comment]
Root cause: custom flag initialization function (https://github.com/knative/serving/blob/master/test/e2e_flags.go#L66) calling `flag.Parse` before the testing flags have been registered.

It *seems* to me that simply ommiting `flag.Parse()` would work, as it will be called later by the testing package.

**Comment by howardjohn** [comment]
We fixed a similar issue in Istio by parsing in test main instead of init fwiw

**Comment by adrcunha** [comment]
Interesting, thanks John. @steuhs if we go that way, make sure test-infra is updated because otherwise using `TestMain` might break the presubmit build tests depending on what it does or expects.

**Comment by chaodaiG** [comment]
@steuhs is OOO this week
/assign

**Comment by chaodaiG** [comment]
In go1.13 testing level flags (i.e. `-v`) are registered in `testing.Init()` according to [release note](https://golang.org/doc/go1.13#testing) as part of generated `main()` function, which is executed later than global variable initialization, such as [`initializeServingFlags`](https://github.com/knative/serving/blob/d2bf8fd8fb9d290f84530cbb88bb98fcef633bd0/test/e2e_flags.go#L53) call, which failed to parse flags as they are not registered yet.
