### ISSUE TITLE
Prow auto-bumper tool updates prow config, but does not apply it

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#1340]
The prow auto-bumper tool creates a PR and auto merges the updates to prow config so that we are using latest stable version. But, applying this is still a manual process and we should consider automating it. Else, we will not be reflecting the version we are acutally using in the repo as in the actual prow cluster

/cc @chaodaiG

**Comment by srinivashegde86** [comment]
Note that the auto-PR also updates `config.yaml`to use these new references - https://github.com/knative/test-infra/pull/1336

So, if we only update config-map to use the new config.yaml, it will point to new references and prow will still be on the older version.

**Comment by chaodaiG** [comment]
Agree with automating applying part, we can set up a postsubmit job to do it. What's worth discussing is:
1. If the job should update with any `*.yaml` change under `ci/prow`, or just a subset of it
2. Should the job only update when PR author is prow auto updater bot or any user

**Comment by adrcunha** [comment]
I'm not sure I like the idea of Prow being automatically updated when the PR gets merged.

**Comment by srinivashegde86** [comment]
My only concern is that we will keep updating our files in the repo and not actually update prow cluster. So, we will still see issues of backward-incompatibility like before.

**Comment by adrcunha** [comment]
I agree. The PRs should only be approved by the oncall, who then updates the cluster immediately. We already talked about that.procedure, but never wrote that down; we should do that.
