### ISSUE TITLE
GitHub notification for Knative actions

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#136]
This came up from scaling working group with @josephburnett. 

PR owners often need to wait for approve/lgtm to close on a PR. However, from the reviewer side, they also have difficulty knowing when something needs their  attention. It's normal for folks to get like a bazillion emails about Knative each day. We have an internal chrome pluggin for our google code review tool that gives me a little red flag in the corner of my browser when a cr needs my attention. something like that would be useful for knative. so individuals don't have to ping each person on slack.

Perhaps git notification can help. Let's discuss options.

**Comment by adrcunha** [comment]
Gubernator PR dashboard is a great way to be on top of PRs that need your attention.

An interesting (intern?) project would be creating a Chrome plugin for notifications (I'm not aware that such thing exists).

But then we're now mostly on Kubernetes land.

@fejta might have more comments/ideas about this.

**Comment by adrcunha** [comment]
https://medium.freecodecamp.org/i-wanted-real-time-github-push-notifications-so-i-built-a-chrome-extension-7e6be0611e4 seems to be exactly the problem/feature we need (just as an example)

**Comment by jessiezcc** [comment]
With chrome, we don't know whether all contributors use chrome.
With github, it's guaranteed all contributors will see it.

**Comment by adrcunha** [comment]
According to https://help.github.com/articles/about-notifications/ you can configure your notifications, so even if we inject them somehow, it's not guaranteed that the user will see them on the web page (or even at all, if the notification is also disabled for email).

**Comment by fejta** [comment]
Chrome extension would be cool. Could serve as a reference for people who want to write one for Firefox/safari/edge. 

I definitely find the PR dashboard very helpful -- I know which PRs need my reply. This is works better than GitHub notifications which doesn't have the concept of a review turn.

**Comment by adrcunha** [comment]
https://github.com/marketplace/pull-reminders (also https://pullreminders.com) is an app in the GitHub marketplace that reminds you about pending reviews in Slack. It's free for open source projects. Looks like Pivotal is using it, maybe they can provide us with their opinion about the tool effectiveness.
