### ISSUE TITLE
Staging mechanism for new prow-tests images

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#1364]
Problem: No good or documented way to test new prow-tests images.

Solution:
Building on https://github.com/knative/test-infra/issues/329, add an optional presubmit using an alpha tagged prow-tests image, change a CI flow to use a beta-tagged image, and document the procedure.

**Comment by adrcunha** [comment]
Don't change a CI flow. Instead, create a new one that exercises the components/tools. Add tests as necessary.

**Comment by coryrc** [comment]
We discussed in person; plan is new presubmit same as CI master branch, then CI master branch using the image.

**Comment by adrcunha** [comment]
So I don't get confused again about this:

* new presubmit job uses "alpha" image;
* test-infra CI flow uses "beta" image;
* everyone else uses "prod" image;

**Comment by coryrc** [comment]
Oh, as another part of modifying the config generator, may want the ability to leave old releases on an old image (f.ex. updating to go 1.13 would break releases pre-0.9), but I won't actually set an old image at this time.

**Comment by coryrc** [comment]
Don't forget to update the playbook as well

**Comment by coryrc** [comment]
And, not test-infra CI flow using beta, knative/serving master CI flow uses beta image. It's the same test that is run in the new presubmit.

test-infra doesn't do enough interesting work to serve as a valid test case.

**Comment by adrcunha** [comment]
We don't want to use knative/serving as a guinea pig. If test-infra doesn't have good enough test cases for the image, add new ones, even if they're used exclusively by the beta flow.

**Comment by coryrc** [comment]
The presubmit runs in knative/serving. It runs the exact same job as CI master branch. There's no reason for it to fail, and it will be easy to revert.

We currently have no testing. This is better.

**Comment by adrcunha** [comment]
> The presubmit runs in knative/serving. It runs the exact same job as CI master branch.

Almost. The CI job runs everything in sequence.

> There's no reason for it to fail, and it will be easy to revert.

Famous last words. 🤣 It's even easier and more contained if we use test-infra.

> We currently have no testing. This is better.

We do have testing, and they're meant to test the infrastructure, not Knative. If they're not enough for the prow-tests image, this is yet another reason to add more tests.

**Comment by coryrc** [comment]
Creating a new CI flow as copy of the integration-tests CI flow in each repo.

**Comment by coryrc** [comment]
2044 should have fixed this

**Comment by coryrc** [comment]
Missed a few images being -go114: https://github.com/knative/test-infra/pull/2044/files#diff-d7e5ce7ac90738a0137d602ea0820b71R8056

**Comment by coryrc** [comment]
Fixed in: https://github.com/knative/test-infra/pull/2065

I need to document using the flows though.
