### ISSUE TITLE
Add Issue / Pull Request Lifecycle Management to Docs Repo

### ISSUE THREAD

**Issue by eallred-google** [knative/test-infra#1368]
Add issue / Pull Request Lifecycle Management to knative/docs repo

Stale = 90 days
Rotten = Stale + 30 days
Close = Rotten + 30 days

Details outlined in [proposal doc](https://docs.google.com/document/d/15sqqVxOGAXLNEDFp777NWIpevwrSMYbGQABFLNqiq5Q/edit#)

**Comment by adrcunha** [comment]
The config generator needs to be updated to handle per-repo jobs, as well as per-repo settings for the deadlines. I also would like the messages to be updated to reflect those in the proposal doc.

@Fredy-Z can you work on this? Not urgent, but also shouldn't be a hard task.

/assign @Fredy-Z 
/label kind/project-support

**Comment by adrcunha** [comment]
@Fredy-Z please sync up with the oncall to update the Prow config and enable the new jobs.

**Comment by eallred-google** [comment]
I added the lifecycle/stale, lifecycle/rotten, and lifecycle/frozen labels to the Docs repo.
