### ISSUE TITLE
Update testing image to have `kail` installed

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#1379]
We try to install `kail` here:
https://github.com/knative/serving/blob/5407c07d2f247032ddcbebf2f6048eb73eb70857/test/e2e-common.sh#L344

but it should be pre-installed in the test image.

This tool is used to collect logs.

I need to
1. Update the test image
2. Publish updated test image
3. Update this code to not attempt to install kail

/assign

**Comment by adrcunha** [comment]
Fixed by #1378.
/close
