### ISSUE TITLE
Flaky test retryer reacts slowly to failed presubmit tests

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#1383]
Sometimes the flaky test retryer takes a few minutes to make comments on the PR after presubmit tests failed. 

One example can be seen at https://github.com/knative/serving/pull/5623.

From the [stackdriver logs](https://pantheon.corp.google.com/logs/viewer?interval=NO_LIMIT&project=knative-tests&minLogLevel=0&expandAll=false&timestamp=2019-09-22T21:50:04.762146215Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22monitoring%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.project_id%3D%22knative-tests%22%0Aresource.labels.zone:%22us-central1-a%22%0Aresource.labels.container_name%3D%22flaky-test-retry-bot%22%0Aresource.labels.pod_id:%22flaky-test-retry-bot-%22%0A%22serving%2Fpull%2F5623%22&scrollTimestamp=2019-09-20T18:49:12.657662487Z), we can see it took 6 seconds (17:59:44 - 17:59:50) from `starting analysis` to `triggering retry`. And from the [test log](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/5623/pull-knative-serving-integration-tests/1175098967826894849) , we can see the test failed at 17:51:44.

So for this specific case, the reason that caused its slowness is the time between the job failed and retryer received the pubsub message is long (17:59:44 - 17:51:44 = *8min*).

FYI @chaodaiG

**Comment by chaodaiG** [comment]
Thanks @Fredy-Z , I have investigated once with @yt3liu , and we noticed that the latency between jobs failed and pubsub message isn't very long(less than 1 minute), so there must be some other activities going on that prevented retryer from reacting fast.

**Comment by chaodaiG** [comment]
So after some investigation I believe the bottleneck is in prow/crier, as we only have 1 pubsub-worker configured for crier. After updating pubsub-worker to 5 in #1392, the problem seemed fixed. 
Examples:
https://github.com/knative/serving/pull/5339
https://github.com/knative/serving/pull/5655

**Comment by Fredy-Z** [comment]
Nice 👍

**Comment by chaodaiG** [comment]
Have checked a few other runs of flaky test retryer, the latency is down to less than 1 minute for all. Mark this issue as fixed.

/close
