### ISSUE TITLE
Allow specifying cluster name in clustermanager library

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1393]
Right now by using the clustermanager library in https://github.com/knative/pkg/testutils/clustermanager to create a cluster, the cluster name is fixed and we don't have a way to manipulate it.

As requirements of Knative performance testing, we need to:
1. Create clusters with any names
2. Delete and recreate the cluster if it already exists

/cc @chaodaiG 
/cc @adrcunha

**Comment by chaodaiG** [comment]
> @Fredy-Z: The label(s) `kind/feature` cannot be applied. These labels are supported: ``

I think the last sentence revealed a bug
