### ISSUE TITLE
Coverage for knative/pkg is empty for 9/24

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#140]
https://testgrid.knative.dev/knative-pkg#coverage

The changes from #110 were pushed yesterday, and the other repos show coverage numbers for today. It seems that the target change caused the coverage report on knative/pkg to break.

**Comment by steuhs** [comment]
I am looking at it

**Comment by steuhs** [comment]
fixed

**Comment by steuhs** [comment]
updated binary to use most recent code to fix the issue: https://github.com/kubernetes/test-infra/pull/9313
