### ISSUE TITLE
Rename test-infra to productivity

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#145]
Since this will be our primary repo for productivity related projects, is it feasible to rename the repo to Productivity? "test-infra" is a bit limited in terms of scope.

**Comment by adrcunha** [comment]
Technically this is not an issue. test-infra was chosen to follow the pattern from kubernetes. So far the scope of the repo reflects its name.

**Comment by jessiezcc** [comment]
not a priority, big risks for breaking.
