### ISSUE TITLE
Notify when LGTM is lost due to merge

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#146]
This was brought up from scaling working group. 

["What about automatically notifying if LGTM is lost because of a merge?"](https://docs.google.com/document/d/1FoLJqbDJM8_tw7CON-CJZsO2mlF8Ia1cWzCjWX8HDAI/edit#)

**Comment by adrcunha** [comment]
This is interesting and should be filed in kubernetes test-infra/prow.

**Comment by adrcunha** [comment]
When LGTM is lost due to a change, a comment is added to the issue, e.g., https://github.com/knative/serving/pull/1817#issuecomment-411774784

However, such comment is not added when Prow removes the LGTM due to a new commit, e.g., https://github.com/knative/serving/pull/2435#event-1955723201

**Comment by jessiezcc** [comment]
Jessie to file an ask against Prow, and then close this issue.

**Comment by adrcunha** [comment]
This is now properly notified by Prow when a merge happens: https://github.com/knative/test-infra/pull/831#issuecomment-496651103
