### ISSUE TITLE
Monitoring pubsub based services over pubsub messages using stackdriver

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1469]
We have a few tools running as standalone services on monitoring k8s cluster, such as flaky test retryer and monitoring tool, which by themselves are not monitored, and we wouldn't know about them fail even if they haven't been running for quite a while. Since these 2 tools both consume pubsub messages, the pubsub messages will not be acked if the services are not working. So we can use stackdriver to monitor if the pubsub messages are acked or not, or check how old the messages are and send alert based

**Comment by nicoaragon** [comment]
1) message age per topic: When P99 message age is older than threshold "X", this means your service is too slow to drain the queue and might have stopped running.

2) queue depth per topic: When there are more than "K" messages queued, this means your service is not draining the queue and might have stopped running.

Tweaking "X" and "K" will configure alarm sensitivity (increase/decrease accuracy for alarms).

**Comment by chaodaiG** [comment]
Have played with my test project, and the alerting for queue depth works great! Thanks a lot for the tips. I somehow had trouble figuring out the query for P99 message, any pointer would be appreciated.

**Comment by adrcunha** [comment]
I was able to remove the project from such workspace and add it to knative-tests. I'm now able to access it. Please try again.

**Comment by chaodaiG** [comment]
Great! Monitoring for `monitoring` app and `flaky-test-retryer` app is set up here: https://app.google.stackdriver.com/policies/15844359308756244434?project=knative-tests

I would consider this task completed
/close
