### ISSUE TITLE
Enable /lint in prow for knative repos

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#147]
Prow provides many plugins for static analysis. We have enabled a few, but not linting. There is a golint plugin that adds warnings as comments to the PR. We should enable that.

**Comment by adrcunha** [comment]
The linter is already enabled, and anyone can use it:

https://prow.k8s.io/command-help

For example:

https://github.com/knative/serving/pull/2095#issuecomment-425185226

Note that it's not automatic, you have to manually issue `/lint`. For details about where, when and why, see https://github.com/knative/serving/issues/346.
