### ISSUE TITLE
Monitoring should only handle failed jobs or be configurable

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1494]
According to the logic in https://github.com/knative/test-infra/blob/027b4ff36fdb3a671f12e4fb1d386a742ee12183/tools/monitoring/alert/alert.go#L61, monitoring is handling all Prow jobs (parse the build log, match the error pattern, decide if alert needs to be sent, etc.), it can easily overload the service. 

We should only handle failed jobs. If we do need to handle some normal jobs for specific reason, we need to make it configurable in the `config.yaml`, and skip all jobs that should not be handled.

/kind bug

**Comment by steuhs** [comment]
Fixed by https://github.com/knative/test-infra/pull/1501. 
Need to build and use new image after the change

**Comment by steuhs** [comment]
Image updated and deployed https://github.com/knative/test-infra/pull/1504
