### ISSUE TITLE
Documentation on existing test-infra tooling

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#150]
This has come up a few times from various discussions. Need to bring up awareness of existing tooling such as gubernator, testgrid, prow, and etc.

**Comment by adrcunha** [comment]
Our documentation in the repo is barely minimum. We should document our tools, use cases and expected flow better. Although there's some documentation about it in some repos (knative/serving or knative/docs), it's hidden, generic and mostly pointing to existing (long) documentation, so I think nobody reads that. With a proper documentation/guide, we can point/remind devs to them when needed.

**Comment by jessiezcc** [comment]
@samodell, Sam, do you think docs team can help us out here?

**Comment by jessiezcc** [comment]
This issue actually tracks much bigger scope of test-infra documentation. 
I'm working on a spec and is conversation with docs wg to help out.

**Comment by jessiezcc** [comment]
There are incremental documentation activities happened as we update/add new features.
