### ISSUE TITLE
Set up cherrypick plugin

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1505]
There is a plugin in Prow called [CherryPicker](https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker). If it's enabled, users can add a comment like `/cherrypick release-1.10` under a PR, the plugin will create a new PR against that branch after the PR is merged. This plugin seems to be very useful especially for knative/docs repo.

**Comment by adrcunha** [comment]
This seems interesting. However, this is an external plugin, meaning it must be hosted somewhere: 

https://github.com/kubernetes/test-infra/blob/master/prow/plugins/README.md

That's probably why I don't see it enabled for Kubernetes:

https://github.com/kubernetes/test-infra/search?q=cherrypicker&unscoped_q=cherrypicker

**Comment by chizhg** [comment]
Enabled in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/630
