### ISSUE TITLE
Monitoring should not report all lines in the email when pattern ".*" is used

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#1506]
Monitoring currently report all occurrences of an error pattern in a build log. It works as desired for regular patterns with concrete content. However, when the pattern ".*" is used, it will report all lines in the build log - it costs storage and traffic, and distracts reader.

**Comment by chizhg** [comment]
I think we can make ".*" as the default configuration, if it's being specified, we skip the matching process.
