### ISSUE TITLE
Consider a way to automatically retrigger stuck presubmit jobs

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1528]
During the down time of Prow or Github, if someone creates a PR, the presubmit jobs will be stuck in `wait for status to be reported` state, and won't be automatically triggered after everything is recovered.

Users can type `/retest` or `git push` to get these jobs started, but it would be nice if they can be automatically handled in the failover process.

**Comment by adrcunha** [comment]
This should be moved to kubernetes/test-infra, as it's Prow-specific.

**Comment by chizhg** [comment]
Make sense, created https://github.com/kubernetes/test-infra/issues/15178.
/close
