### ISSUE TITLE
No dot release for 0.10 due to ordering

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#1542]
The eventing-dot-release run yesterday thought the most recent release branch was `release-0.9`, ignoring `release-0.10` because it was sorted earlier:

```
From https://github.com/knative/eventing
 * [new branch]        master       -> upstream/master
 * [new branch]        release-0.10 -> upstream/release-0.10
 * [new branch]        release-0.2  -> upstream/release-0.2
 * [new branch]        release-0.3  -> upstream/release-0.3
 * [new branch]        release-0.4  -> upstream/release-0.4
 * [new branch]        release-0.5  -> upstream/release-0.5
 * [new branch]        release-0.6  -> upstream/release-0.6
 * [new branch]        release-0.7  -> upstream/release-0.7
 * [new branch]        release-0.8  -> upstream/release-0.8
 * [new branch]        release-0.9  -> upstream/release-0.9
 * [new branch]        v0.1         -> upstream/v0.1
Last release is v0.9.0
Last release branch is release-0.9
```

This seems to block any 0.10.1 release.

/cc @adrcunha

**Comment by adrcunha** [comment]
I thought this has been solved, let me take a look.

**Comment by adrcunha** [comment]
https://github.com/knative/test-infra/pull/1377 fixed that for auto releases, but not dot releases.

**Comment by grantr** [comment]
Great, seems like a simple fix.

**Comment by adrcunha** [comment]
Fix is in, releases built manually, waiting for the remaining PRs to be merged before closing this issue.

**Comment by yt3liu** [comment]
For eventing-operator, the required test-infra changes is merged in another PR: https://github.com/knative/eventing-operator/pull/32/files

**Comment by adrcunha** [comment]
All PRs merged.
/close
