### ISSUE TITLE
prow-tests image update fails knative-serving integration tests

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1557]
After upgrading the tools in prow-tests, knative serving integration tests are not setup correctly and fails due to:
```
Error from server (NotFound): horizontalpodautoscalers.autoscaling "activator" not found
ERROR: Knative setup failed
```

Test PR in OSS: https://github.com/knative/serving/pull/6089
Spyglass link: https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/6089/pull-knative-serving-integration-tests/1197947484156989440

The most likely culprit that breaks the test-infra is ko update.

@yt3liu since she first reported and documented this issue

**Comment by adrcunha** [comment]
Since this issue is 7 days old, I assume the prow-tests image was rolled back?
