### ISSUE TITLE
Incorrect return status from default_build_test_runner

### ISSUE THREAD

**Issue by navidshaikh** [knative/test-infra#1561]
client is [using](https://github.com/knative/client/blob/master/test/presubmit-tests.sh#L51) default build test runner, which failed/stopped [here](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/523/pull-knative-client-build-tests/1200012590198034432#1:build-log.txt%3A449) on `go: error loading module requirements` and no sub-tests (codegen, licenses) ran further. This should be flagged as error?
A complete client build tests run looks like [this](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/415/pull-knative-client-build-tests/1199985410650935298#1:build-log.txt%3A1326) and completes with `No errors found.` message.

Also client defines additional `post_build_tests`, which [continued](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/523/pull-knative-client-build-tests/1200012590198034432#1:build-log.txt%3A451) and completed, the build tests took the return status of `post_build_tests` to report build tests passed.

**Comment by adrcunha** [comment]
While it's correct that the build tests should be aborted and no further tests run if a module loading error happens, post_build_tests shouldn't run as well.

**Comment by adrcunha** [comment]
The cause is a bit more subtle. Offending line is

https://github.com/knative/test-infra/blob/2c4cd9df33c648a86d95bdd4119386cba04cde56/scripts/presubmit-tests.sh#L161

It seems that `go list` is failing, thus returning no content, which causes the function to return, but since no test failed so far (and at this point the only test run was the markdown test) it returns success.

**Comment by navidshaikh** [comment]
Another thing wanted to discuss is, client uses `default_build_test_runner` which performs multiple steps, markdown, `go build`, etc, we'd like to be able to customize the `go build` [step](https://github.com/knative/test-infra/blob/2c4cd9df33c648a86d95bdd4119386cba04cde56/scripts/presubmit-tests.sh#L167) or use it as a separate function which supports args, specifically would like to call `go build` with `-mod=vendor` to avoid downloading the deps during the build, since the deps are already populated in the `vendor` directory of client. 
The main reason for asking this is, we've seen failures resolving deps on `modernc.org` https://github.com/knative/client/pull/525#issuecomment-559522731 and configured custom `unit_tests` function with `-mod=vendor`.
Note that the error on resolving deps is not frequent, but when it occurs all the go operations trying to download the deps block on it. 

@adrcunha WDYT ?

**Comment by adrcunha** [comment]
If you just want `-mod=vendor` in `go build`, I suggest you add such feature to the base script. If you prefer having your custom build step, see step 2 in https://github.com/knative/test-infra/blob/master/scripts/README.md#using-the-presubmit-testssh-helper-script

**Comment by navidshaikh** [comment]
Thanks!, I checked the step 2 in docs, would like to keep and re-use other useful checks base script has of `IS_DOCUMENTATION_PR`, markdown, codegen, license etc but just adjust the parameters of `go build`.

>  I suggest you add such feature to the base script. 

Alright! :+1:
