### ISSUE TITLE
Update prow config to enable go 1.13 for client

### ISSUE THREAD

**Issue by navidshaikh** [knative/test-infra#1574]
client planning to move to go 1.13 https://github.com/knative/client/issues/532 ,
logging this to track changes needed at test-infra side.

**Comment by adrcunha** [comment]
I believe that once https://github.com/knative/test-infra/pull/1558 is merged it's just a matter of merging 532 above and updating the Prow config.

**Comment by navidshaikh** [comment]
/close

Prow configured to use go 1.13 for client, thanks!
