### ISSUE TITLE
Enable nightly job of Tekton e2e tests for client

### ISSUE THREAD

**Issue by navidshaikh** [knative/test-infra#1575]
We've Tekton-Knative e2e tests setup for client, per last WG call meeting we decided to run these e2e  tests only as (a) Nightly check (post usual nightly job) ~and (b) Pre-release check~.

This is to track configuring respective jobs at test-infra side.

**Comment by adrcunha** [comment]
I understand that (a) is a nightly job (running after the usual nightly release job), but it's not clear to me what (b) would be.

**Comment by navidshaikh** [comment]
(b) Pre-release check - The validations tests ran before the auto-release, wanted to append these Tekton-Knative e2e tests to the default validations tests. 
However, thinking about the kn image that will be used for these tests - the one configured is `gcr.io/knative-nightly/knative.dev/client/cmd/kn` (the last nightly built image, or even the one before if last nightly had failed) and the release branch might include additional commits after last nightly run. So, these Tekton-Knative e2e test run will be identical to the one ran after last nightly (a).
Beside, the Tekton-Knative e2e tests results will be part of result the pre-release validation tests (b).

So adding these Tekton-Knative e2e to pre-release validation tests will not test the right kn image / from-commit we want to cut release against. 

What do you suggest?

**Comment by navidshaikh** [comment]
In the current setup, the pre-release job would be same as the last nightly job run for Tekton tests. 
So let's configure only nightly job for Tekton tests.

**Comment by adrcunha** [comment]
Sorry, this fell off my radar. So the idea is to run https://github.com/knative/client/blob/master/test/tekton-tests.sh at after 1:41AM PST (https://testgrid.knative.dev/client#nightly), say around 5AM PST?

**Comment by navidshaikh** [comment]
Yup, 5AM PST sounds good!
