### ISSUE TITLE
Enable project plugin for docs repo

### ISSUE THREAD

**Issue by eallred-google** [knative/test-infra#1586]
Using the prow **/project Kn Client Docs** command in the docs repo to add an issue to a project is failing. 

repro Steps 
- open an issue in the docs repo
- /project 23
- results "Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository."

Sam has sufficient rights to add the Issue itself to the  project manually. 

Prow command ref for Project](https://prow.k8s.io/command-help#project)

**Comment by adrcunha** [comment]
It doesn't work because it's not configured for the docs repo:

https://github.com/knative/test-infra/blob/master/ci/prow/plugins.yaml#L50

**Comment by samodell** [comment]
@adrcunha  It would be super helpful to have that implemented for the docs repo! We have contributors wanting to organize their work in our projects. Thanks for looking into the issue.

**Comment by adrcunha** [comment]
@samodell And what settings should be used?

**Comment by samodell** [comment]
I'd say any Knative org Member should be able to use /project to put issues/PRs into projects with Prow. Is that similar to what other repos are doing?

**Comment by adrcunha** [comment]
Sorry, I was thinking specifically about the plugins settings (https://github.com/knative/test-infra/blob/master/ci/prow/plugins.yaml#L55). Do you need extra columns? Is the default milestone team enough, or do you need to create a new one?

**Comment by samodell** [comment]
We could use https://github.com/orgs/knative/teams/knative-doc-writers for the team who will have access.

And the default column being "to do" is fine, like for eventing. Thanks! @adrcunha

**Comment by samodell** [comment]
Unless the Knative Doc Writers group has more permissions than I'm aware of -- maybe we should get a new group created. I can ask about it and get back to you.

**Comment by adrcunha** [comment]
Unfortunately I don't have permission to query the API to check the ID of knative-doc-writers. Someone from https://github.com/orgs/knative/teams/knative-admin should be able to do that (as explained in https://github.com/knative/test-infra/blob/master/ci/prow/plugins.yaml#L44). Also, I believe @grantr can give you the right guidance regarding whether creating a new group is recommended or not.

**Comment by samodell** [comment]
I sent an email to the Knative admins to ask what permissions knative-doc-writers has now. I'll let you know when I hear back!

**Comment by chizhg** [comment]
@samodell any update for this?

**Comment by samodell** [comment]
@chizhg @adrcunha 

Thanks for the ping! The admins created a new group for this purpose -- https://github.com/orgs/knative/teams/knative-doc-contributors

Can we give that group of folks permissions through Prow to:

- Add issues to projects in the Docs repo
- Add labels to issues and PRs, except for the Approved, LGTM, and CLA:YES labels (if that's possible)

**Comment by adrcunha** [comment]
These are GitHub permissions, not Prow. If they can be set, it's probably through GitHub's settings UI (probably by an admin).

Specifically, the cla:yes label is handled by googlebot and the approve/lgtm ones by Prow; these two won't be fooled if a bad player simply add such labels, so there's no need to worry.

**Comment by chizhg** [comment]
@samodell 

Sorry I missed this issue.. Do we still want it? It seems https://github.com/orgs/knative/teams/knative-doc-contributors does not exist anymore. Maybe we also want to push this issue back until [Knative Github ACLs](https://docs.google.com/document/d/1pCLzTfNP5-_Z9taNK0W5hntyKbP4E5DI4-6n16GpyeU/edit#) is landed.
