### ISSUE TITLE
Add Issue / Pull Request Lifecycle Management to Serving Repo

### ISSUE THREAD

**Issue by eallred-google** [knative/test-infra#1593]
Add issue / Pull Request Lifecycle Management to knative/docs repo

Stale = 90 days
Rotten = Stale + 30 days
Close = Rotten + 30 days

Details outlined in [proposal doc](https://docs.google.com/document/d/15sqqVxOGAXLNEDFp777NWIpevwrSMYbGQABFLNqiq5Q/edit#)

**Comment by eallred-google** [comment]
added the following labels to Serving Repo
Label                     Description
lifecycle/stale        Flags lifecycle automation to ignore
lifecycle/rotten      lifecycle automation - stale + untouched for 30 days
lifecycle/frozen     lifecycle automation - untouched for 90 days

**Comment by adrcunha** [comment]
Prow config updated.

**Comment by adrcunha** [comment]
Jobs are running fine. Sample stale issue in serving:

https://github.com/knative/serving/issues/2452

Initial list of stale issues:

https://prow.knative.dev/log?job=ci-knative-serving-issue-tracker-stale&id=1207994091841785857

**Comment by eallred-google** [comment]
Thank you Adriano - looks great!
