### ISSUE TITLE
Investigate the behavior or /kind and /area

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#1603]
Looks like they are either misconfigured or the described behavior is now different from the actual behavior.

For example: https://github.com/knative/serving/issues/6375

I noticed the same issue in /label and filed https://github.com/kubernetes/test-infra/issues/15628

**Comment by chaodaiG** [comment]
It’s configured as a plugin called label  here: https://github.com/knative/test-infra/blob/master/config/prow/core/plugins.yaml
The source of this plugin is at: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/label

**Comment by chizhg** [comment]
It looks there is no issue with `/kind` and `/area` commands now, see https://github.com/knative/test-infra/issues/2278#issuecomment-655827424
