### ISSUE TITLE
Making testgrid alerts more useful and standardize the alerts

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1609]
Currently testgrid will send email alerts when Prow jobs fail, as configured in https://github.com/knative/test-infra/blob/master/ci/prow/testgrid.yaml. By default it will send alerts for every job failure, and for some CI jobs it will send alerts if there are more than 3 failures. 

In this way it will send a lot of alerts, most of which are not useful. Further more, we now have FlakyTestReporter and Monitoring for alerting, and many alerts they send are duplicate.

We should distinguish responsibilities for these tools and avoid sending duplicate alerts:
1. Testgrid should only alert for general Knative job failures that we care about, e.g.
- Alert for any release job failure
- Alert for release CI job failures if they fail 3 times in series
2. Monitoring (or any monitoring system we would replace in the future) should only alert for infra related issues, e.g.
- Alert if any maintenance job failures, e.g. prow auto bumper, cleanup job, issue tracker job, etc.
- Alert if any infra related issue happens, e.g. boskos fails to acquire project, github no such host issue.
3. FlakyTestReporter should still alert for flaky test cases, no changes are required.

/kind good-first-issue

**Comment by adrcunha** [comment]
Agreed. 1 is trivial, is there even a change needed for 2 and 3?
