### ISSUE TITLE
Need a testgrid tab dedicated to conformance tests

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#162]
It should show overall conformance tests passing rate as well as individual test results.
Right now, it's shown under continuous/release together with unit tests and E2E tests.

**Comment by srinivashegde86** [comment]
Conformance and e2e tests are currently run as one group. We may need to separate them out and store results separately.

**Comment by adrcunha** [comment]
I wonder if we can have a Testgrid tab that filters the conformance tests from the CI job... This way we get the results for free, with no overhead.

**Comment by adrcunha** [comment]
Answer is "yes":

https://testgrid.knative.dev/knative-serving#continuous&include-filter-by-regex=%2Ftest%2Fconformance
