### ISSUE TITLE
Enhance Prow config presubmit tests

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1622]
Istio EngProd team has added a new presubmit test job to check Prow cluster config and job configs - https://github.com/istio/test-infra/blob/master/.prow.yaml.

It's actually using the same tool we are using in https://github.com/knative/test-infra/blob/d5990f0e5a05d5819a40ad3b4de6227406850b48/ci/prow/Makefile#L145, but there are a lot of recent changes that makes it being able to catch various lint errors, see https://github.com/kubernetes/test-infra/blob/5f81c02cfa52aed3311a76b9b9e0b077db34d035/prow/cmd/checkconfig/main.go#L90-L103.

I think it's worth to replace the current check with a presubmit job, in which we can check both Prow cluster config and job configs.

/kind good-first-issue

**Comment by adrcunha** [comment]
A separate job won't achieve anything that the current job doesn't already do. We run @k8s//prow/cmd/checkconfig in the presubmit tests since I don't remember when, and there were several instances where the check didn't catch issues (I don't remember them though).

I'm not confident with simply having checkonfig as the gatekeeper for automatic deploying Prow configs.

**Comment by adrcunha** [comment]
One example of an error (typo) that checkconfig can't catch: rename `tide:` in `config.yaml` to, say, `tida:`, and it won't complain. It means that entire sections of the config file can be missing or wrong (as long as the file is parseable YAML) and the presubmit will still pass.

**Comment by chizhg** [comment]
I believe that @k8s//prow/cmd/checkconfig has been improved a lot to be able to catch more errors, there are a lot of options that we can enable for better checking, which we don't have for now. See https://github.com/kubernetes/test-infra/blob/5f81c02cfa52aed3311a76b9b9e0b077db34d035/prow/cmd/checkconfig/main.go#L90-L103

I can check if options like `tideStrictBranchWarning` can catch the error you mentioned above. And if it works, I think we can add all the options to see how they works. If it turns out to be useful, we can  then move that check to a separate presubmit job.

**Comment by adrcunha** [comment]
Indeed, our test has room for improvement. For example, we have warnings about long job names (which then fail the test if `--strict` is used). But other than that looks like only `--expensive-checks` is missing? (all warnings are enabled by default)

And AFAICU from the code, `tideStrictBranchWarning` is enabled by default and didn't catch the example I mentioned (although just enabling it is a very specific solution to the general problem I pointed).

**Comment by chizhg** [comment]
Indeed, based on the code logic, it's not enabled by default (though the var name `defaultWarnings` is super confusing).
To enable the warnings, you'll have to pass them as flags, things like:
```
bazel run @k8s//prow/cmd/checkconfig -- \
		--config-path=$(PROW_CONFIG) \
		--plugin-config=$(PROW_PLUGINS)
		--warnings=mismatched-tide \
		--warnings=mismatched-tide-lenient \
		--warnings=tide-strict-branch
```

**Comment by adrcunha** [comment]
No, by default all warnings are enabled (if expensive warnings are enabled, there are more):

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/checkconfig/main.go#L198

But currently there's only one expensive warning, but it's just for checking OWNERS files:

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/checkconfig/main.go#L120

In your example above you would be checking just 3 warnings.

Anyway, the current checks don't cover the case I mentioned (but please don't stick to it as the single blocker).

**Comment by coryrc** [comment]
We were suggested to use a checkconfig test image

**Comment by cjwagner** [comment]
FWIW the case that Adriano mentioned is covered by the default checkconfig warnings. In particular the `unknown-fields` warning. It is likely that you aren't running that check because checkconfig is at an old version: https://github.com/knative/test-infra/pull/1792#issuecomment-598498852
It also looks like you are missing the `--strict` flag to cause the job to fail when these lint checks fail.

**Comment by chizhg** [comment]
Duplicate of https://github.com/knative/test-infra/issues/1810
