### ISSUE TITLE
Add postsubmit job to update Prow configs

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1623]
After https://github.com/knative/test-infra/issues/1622 is done and we are confident it can catch all the Prow config errors, we can add a postsubmit job to automatically deploy Prow components and update ProwJob configs.

Below are a few reference links from Istio test-infra:
- Example auto deploy job for automatically deploying Prow component file changes: https://github.com/istio/test-infra/blob/1c8f575e361332019600628f5a24a5c6ac48b949/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.gen.yaml#L85-L121
- Example plugin config for automatic ProwJob config upload: https://github.com/istio/test-infra/blob/1c8f575e361332019600628f5a24a5c6ac48b949/prow/plugins.yaml#L13-L20
and https://github.com/istio/test-infra/blob/1c8f575e361332019600628f5a24a5c6ac48b949/prow/plugins.yaml#L72

Documentation about making Prow update and deploy itself: https://github.com/kubernetes/test-infra/blob/master/prow/more_prow.md#make-prow-update-and-deploy-itself

**Comment by chaodaiG** [comment]
Prow job configs and Prow components are not actually on the same level of stability. 
- For job configs, due to the fact that they are generated, there is much less chance of random errors such as typos
- For Prow components
    - Images update is done automatically, relatively "Stable" 
    - Any other updates are still scary, we don't really have a good way of validating them

I think we can do this in steps:
1. Auto apply job configs
1. Auto apply images changes
1. Having a good mechanism of catching regression in any other config changes

**Comment by chizhg** [comment]
Agree.

In order to do this, at first we'll need to do some changes to make Prow being able to differentiate the different kinds of PRs, and run the corresponding `update-config` job. 
Solutions currently in my mind:

1. Auto apply job configs - move all Prow job and testgrid configs to separate folders, if a PR only contains changes in those folders, run `make update-config` and `make update-testgrid-config` as post submit job.

2. Auto apply images changes - IMO we should only auto update if the PR is created by Prow auto bumper (I vaguely remember Prow job supports such filter), but if it's a change like https://github.com/knative/test-infra/pull/1625, we still need to update manually.

3. For such change, I'm considering if the staging Prow cluster would help for the automation process. But if not, whoever needs to make such changes should take care of it :)

**Comment by chizhg** [comment]
This issue has been solved by the prow-config-updater tool, see https://github.com/knative/test-infra/tree/master/tools/prow-config-updater for more details.
