### ISSUE TITLE
Set up monitoring dashboard for Prow

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1624]
Kubernetes Prow has a dashboard where we can check the metrics for the running Prow instance - http://velodrome.k8s.io/.

The doc is in https://github.com/kubernetes/test-infra/blob/master/prow/metrics/README.md.

We should set up the same dashboard as it's now built in Prow.

/kind monitoring

**Comment by adrcunha** [comment]
Velodrome is deprecated and unmaintained. Last time we talked to the Prow team about this, there was an upcoming feature that include the metrics server and a graphana dashboard in Prow, which would make it easy to create dashboards.

The first step for this issue is to sync up with the Prow team about the current/best way of setting up this dashboard.

**Comment by adrcunha** [comment]
I was told once by the Prow team that once we have a grafana dashboard up and running, it's easy to set up alarms for thresholds (and thus solve issues like https://github.com/knative/test-infra/issues/1080).

**Comment by chizhg** [comment]
What we actually need is https://monitoring.prow.k8s.io/.

@cjwagner do you know how this dashboard was set up?

**Comment by cjwagner** [comment]
Monitoring resources are deployed with bazel. Instructions are here: https://github.com/kubernetes/test-infra/tree/master/prow/cluster/monitoring#deploy
These are the commands used to deploy: https://github.com/kubernetes/test-infra/blob/02fd978b4312d6930708a1a22e2ff46b3aa22858/prow/deploy.sh#L91-L92

Please upstream any improvements you make that would be generally useful!

**Comment by coryrc** [comment]
Please ensure it includes metrics on boskos (free, dirty, cleaning, busy).

**Comment by chaodaiG** [comment]
This we done. The dashboard was already set up
