### ISSUE TITLE
Allow repo leads to update their Prow jobs independently

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1626]
Currently all Prow job configs are in one single file, which is https://github.com/knative/test-infra/blob/master/ci/prow/config.yaml.

For better control and separation of ownerships, we should separate the Prow job config file into different project folders, and add `OWNERS` file for each folder, so that each project leads will be able to merge the PRs related to that project without approval from test-infra owners.

/kind enhancement

**Comment by adrcunha** [comment]
I'm afraid things are not just that simple:
* the monolithic config is created by a tool, which needs to be updated to generate separate configs;
* given that we we don't deploy Prow config changes automatically, having leads approving them doesn't make them going live automatically (which can be both frustrating and confusing);
* given that we cannot rely only on our presubmit checks, I'm not comfortable with having config files being updated without someone from test-infra LGTMing it;

Once #1623 is fixed, then I believe this issue can be tackled pretty easily.

**Comment by coryrc** [comment]
Given the config generator, this isn't feasible and we should drop in favor of more important things.

/close
