### ISSUE TITLE
Presubmit tests on untagged release branch picks up the wrong latest release in installing its dependencies

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1629]
If the presubmit tests is run on a release branch that has not been tagged (handled by auto-release Prow jobs), `get_latest_knative_yaml_source` will return a wrong release.

The reason is because in https://github.com/knative/test-infra/blob/dfeb254e57938f9e30b179034e9833e196ec899f/scripts/library.sh#L619, it will return a tag that is on the previous release.

To fix it, `major_minor` in that function should be derived from the release branch name, e.g. get `v0.11` from `release-0.11`.

/kind bug

**Comment by chizhg** [comment]
Also as a project can possibly cut release before its dependencies, in such case the function should be able to fall back to the latest nightly release.

**Comment by adrcunha** [comment]
What's the context here? A release branch is created once, and then a major release cut, adding the tag. Presubmits will run only after the release is cut (ignore the race condition between the manual operations of creating the branch AND creating the CI jobs for the new release). Based on your last comment, it seems to me that the release process was changed (maybe some created a branch and later renamed it?), which then could cause the situation described.

**Comment by chizhg** [comment]
There are two issues here.

As an example, project `knative-gcp` depends on `serving`, and in its e2e test setup phase, it will run `start_latest_knative_serving` to install the latest `serving` release, with the version got from `get_latest_knative_yaml_source`.

The first issue is, suppose `knative-gcp` just cut branch `release-0.12`, it can take up to 2 hours to be released (as the interval for `auto-release` job is 2 hours), and even longer if the job fails because of flaky tests. During this period, if someone submit a PR, the function `start_latest_knative_serving` will install the previous serving release as it uses tags, which will only be updated after `knative-gcp` being actually released. See log in https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/google_knative-gcp/503/pull-google-knative-gcp-integration-tests/1219793641162149889#1:build-log.txt%3A161.

The second issue is, suppose `knative-gcp` cut branch `release-0.12` before serving 0.12 being released, `start_latest_knative_serving` will get an error as it cannot find serving 0.12. In such situation, it should, and makes sense to start serving latest nightly release.

**Comment by adrcunha** [comment]
> The first issue is, suppose `knative-gcp` just cut branch `release-0.12`, it can take up to 2 hours to be released (as the interval for `auto-release` job is 2 hours), and even longer if the job fails because of flaky tests. During this period, if someone submits a PR, the function `start_latest_knative_serving` will install the previous serving release (0.11 or even before) as we uses tags, which will only be updated after `knative-gcp` being actually released.

That's correct and expected: since 0.12 wasn't built yet, it doesn't make sense expecting any jobs to use 0.12.

> The second issue is, suppose `knative-gcp` cut branch `release-0.12` before serving 0.12 being released, `start_latest_knative_serving` will get an error as it cannot find serving 0.12. In such situation, it should, and makes sense to start serving latest nightly release.

That makes sense.
