### ISSUE TITLE
Failure to create a cluster should be reported in the log as an Error

### ISSUE THREAD

**Issue by pbuzek** [knative/test-infra#1632]
For example this [log](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_eventing-operator/75/pull-knative-eventing-operator-integration-tests/1219742932098093057) does not show any errors which makes the failure a little more difficult to diagnose. We should simply print out an error like we do [here](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_eventing-operator/75/pull-knative-eventing-operator-integration-tests/1219682298039898112)

**Comment by adrcunha** [comment]
This is not a good example:

```
Creating cluster keventing-operator-e1219742932098093057 in us-central1...
............................................................................................................{"component":"entrypoint","file":"prow/entrypoint/run.go:168","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2020-01-21T22:07:21Z"}
```

Note that the job was terminated (not sure if during or after the cluster creation) due to some error in the entrypoint binary (run.go) so there's no way the error could be properly displayed. We can highlight this particular error in Spyglass, but I wonder how often it happens (I never saw it before).

**Comment by adrcunha** [comment]
BTW the cluster creation error is already highlighted in Spyglass (unless the job is killed, as explained above):

https://github.com/knative/test-infra/blob/087ff9c87533fd594ac02a41ad4b70d6cdbfc161/ci/prow/config.yaml#L64

**Comment by adrcunha** [comment]
The error is now highlighted:

![image](https://user-images.githubusercontent.com/35786489/73115550-59e30980-3edc-11ea-8680-09e000105358.png)
