### ISSUE TITLE
Prow config update PRs don't have an approver auto-assigned 

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#1638]
Assignees are set by knative-prow-robot, who selects reviewers and approvers from the OWNERS file.

However all PRs from knative-prow-updater-robot are assigned only to a reviewer. See https://github.com/knative/test-infra/pull/1637 for example.

This it NOT because knative-prow-updater-robot is not a member of Knative, as other PRs created by non-members do get a reviewer and an approver assigned by knative-prow-robot.

**Comment by adrcunha** [comment]
Assignees are set by knative-prow-robot, who selects reviewers and approvers from the OWNERS file. If this is really desired, the config files should be moved to a separate directory and have a custom OWNERS file.

**Comment by adrcunha** [comment]
It would be good to expand on why this is desired, though.

**Comment by adrcunha** [comment]
Hmmm... I think the reason for this issue is because https://github.com/knative/test-infra/pull/1637 was assigned only to coryrc, who's a reviewer but not an approver.

**Comment by adrcunha** [comment]
It seems that the way the update PR is generated is causing this behavior, but I can't see any obvious cause in https://github.com/knative/test-infra/blob/b0c4c4e1691282f24ccb3b5b0399952bf086edfc/tools/prow-auto-bumper/pullrequest.go#L141
