### ISSUE TITLE
Enable rerun plugin for Prow

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1653]
Rerun plugin allows whitelisted users being able to click a button on Prow UI and rerun a job. For example, lead of repo X can rerun dot release in case a hotfix missed the automated dot release which runs once per week. Otherwise lead will need to have the permission to apply job yaml on Prow cluster as described here: https://github.com/knative/test-infra/blob/master/ci/manual_release.md#creating-a-dot-release-on-demand

<img width="1225" alt="Screen Shot 2020-01-31 at 11 01 33 AM" src="https://user-images.githubusercontent.com/45011425/73567238-cd27d680-441a-11ea-9e60-41f4587f83cd.png">

**Comment by chizhg** [comment]
Is it indeed a plugin? I searched in https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml but didn't find it.

**Comment by adrcunha** [comment]
This is not a plugin, but a oauth config instead:

https://github.com/kubernetes/test-infra/blob/45246b09ed105698aa8fb928b7736d14480def29/prow/cmd/deck/github_oauth_setup.md#how-to-setup-github-oauth

**Comment by chaodaiG** [comment]
There is a design affecting how Github teams work in knative: https://docs.google.com/document/d/1pCLzTfNP5-_Z9taNK0W5hntyKbP4E5DI4-6n16GpyeU/edit#

Since this work will very likely use Github teams as authorized user, let's hold off until the design landed
