### ISSUE TITLE
Capture errors introduced by Go1.14 

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1658]
Go1.14 is going to be released very soon: https://github.com/golang/go/releases/tag/go1.14beta1

With early manually testing there were already a couple of bugs discovered and fixes are on the way: https://github.com/knative/serving/pull/6725

We could set up Prow jobs running continuously or even in presubmit test to avoid uncaught errors

**Comment by chizhg** [comment]
I think it will be enough to run optional presubmit tests with Go 1.14, we can change it to be required at some time point.
Do we really need to run the Prow job continuously?
