### ISSUE TITLE
Go coverage tool is not reporting the correct status

### ISSUE THREAD

**Issue by yt3liu** [knative/test-infra#1666]
https://github.com/knative/serving/pull/6740 delete a test file which should change the coverage data, but the prow job passes without reporting any coverage result on the drop on coverage. 

Sample PR for when the coverage job is reporting coverage data: https://github.com/knative/serving/pull/6566#issuecomment-575931991

**Comment by yt3liu** [comment]
A fix was attempted last week https://github.com/knative/test-infra/pull/1647. This changed is pushed through coverage-dev image and it's still having the same issue. 
**NOTE:** Change is not pushed to all coverage job as this is not the right fix. 
https://pantheon.corp.google.com/gcr/images/knative-tests/GLOBAL/test-infra/coverage-dev?project=knative-tests&gcrImageListsize=30

From the [job build log](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/6740/pull-knative-serving-go-coverage/1225112460512464899), it's failing to compute the joint set of the changed file

```
...
1 files changed, reported by github:
cmd/activator/request_log.go	

2020/02/05 17:48:00 
Finding joining set of changed files from profile[count=0] & github
End of Finding joining set of changed files from profile & github
2020/02/05 17:48:00 Created file:/logs/artifacts/bot-post
2020/02/05 17:48:00 completed PreSubmit.RunPresubmit(...)
end of code coverage main
```

**Comment by coryrc** [comment]
It wasn't supposed to fix that issue (didn't know that was an issue).

**Comment by steuhs** [comment]
I see coverage is running 1 hour ago https://github.com/knative/client/pull/629

**Comment by steuhs** [comment]
> [knative/serving#6740](https://github.com/knative/serving/pull/6740) delete a test file which should change the coverage data, but the prow job passes without reporting any coverage result on the drop on coverage.
> 
> Sample PR for when the coverage job is reporting coverage data: [knative/serving#6566 (comment)](https://github.com/knative/serving/pull/6566#issuecomment-575931991)

Instead of removing the file, you can delete the file content and leave the file there. If there is no _test.go file associated. Go's test coverage tool will just ignore that source file

**Comment by steuhs** [comment]
This is another evidence showing coverage tool working: https://github.com/knative/serving/pull/6774

There is no evidence the coverage tool stop working. Closing this issue
