### ISSUE TITLE
Presubmit tests in test-infra should also include testing for staging prow configuration

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1686]
Since staging prow configuration file is also generated from the config generator tool, if there are some changes to the tool, the auto-generated staging prow configuration will also be changed.

Currently in presubmit tests we are only checking the prod prow configuration file, see https://github.com/knative/test-infra/blob/64615f92c4ebdd4e4423015ffc0db45877660a0d/test/presubmit-tests.sh#L39, we should also check staging prow configuration file here.

/kind good-first-issue

**Comment by chaodaiG** [comment]
Since the recent change moved templates right next to config-generator: https://github.com/knative/test-infra/tree/master/tools/config-generator, I think we can add a unit test for config-generator instead of a unit test in Makefile
