### ISSUE TITLE
Run Prow components and ProwJob pods on separate clusters

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1695]
Currently we are running all the workloads (services and jobs) for Prow on one single cluster.

As suggested by @cjwagner , we should have separate clusters for the prow components (service cluster) and prow job pods (build cluster). 

Copied & pasted from what he suggested:
That is important for security in OSS if you are running presubmit jobs because it prevents anyone who can run presubmits from accessing core Prow components and secrets.
If you have that setup, you can run certain 'trusted' non-presubmit jobs like deployment or image publishing jobs in the service cluster.
That isolates the secrets needed by the trusted jobs from the untrusted and presubmit jobs.
We ensure that test-infra members control what jobs run in the trusted cluster with a presubmit unit test that ensures all ProwJob configs that request to be run in the trusted cluster live in one file or directory that is controlled by test-infra members via OWNERS.

**Comment by chaodaiG** [comment]
All jobs are running on build cluster now

/close
