### ISSUE TITLE
Run verify-spelling in presubmit tests

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1696]
In Kubernetes, they run verify-spelling in presubmit tests with a script - https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh.

For Knative, we should run the similar check. Probably can be done by the `sockpuppet` bot.

/kind  enhancement

**Comment by chaodaiG** [comment]
sockpuppet is already doing it, an example is: https://github.com/knative/test-infra/pull/1670

**Comment by chizhg** [comment]
That is from postsubmit, we can probably add an optional presubmit test job. Also mentioned by JR in https://github.com/knative/serving/pull/7015.

**Comment by chaodaiG** [comment]
I see, make sense

**Comment by chizhg** [comment]
Similar as #2392, we could use GitHub actions to do this.
/kind good-first-issue

**Comment by kellyaa** [comment]
Spelling is currently included in https://github.com/knative/actions/blob/main/.github/workflows/style.yaml#L130

So this is covered.
