### ISSUE TITLE
check_links_in_markdown should check all markdown files

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1714]
Currently `check_links_in_markdown` only checks markdown files that are changed in the PR, see https://github.com/knative/test-infra/blob/d41432f3e415994399b2ea328675e2284451b83b/scripts/presubmit-tests.sh#L143.

However, it can also be possible that some links in the markdown files become invalid because the corresponding files are moved or deleted. So this function should always check all markdown files in presubmit tests.

/kind enhancement

**Comment by adrcunha** [comment]
Please note that by doing so you'll might block a PR because of unrelated changes/files and thus receive a push back from developers (this already happened in the past).

**Comment by chizhg** [comment]
Thanks for the info! I actually understand that. But if we don't do this, the number of broken links will continue growing and make the situation even worse.
We can help removing the broken links, or find the developers to do so before we change this check. But after that, everyone should start taking care of the broken links in their own PR then there won't be any broken links.

**Comment by chizhg** [comment]
/lifecycle frozen
Probably something we can move to GitHub actions.

**Comment by chizhg** [comment]
Similar as #2392, we could use GitHub actions to do this.
/kind good-first-issue

**Comment by kvmware** [comment]
Closing in favor of https://github.com/knative/test-infra/issues/3383
