### ISSUE TITLE
Check yaml errors in presubmit tests with yamllint

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1733]
The knative/test-infra repository holds a lot of yaml files, but there is no check for the yaml file format.
We should add the check in presubmit tests, [yamllint](https://github.com/adrienverge/yamllint) seems to be a tool we can choose.

/kind enhancement

**Comment by chaodaiG** [comment]
Good idea, k8s is already using it: https://github.com/kubernetes/test-infra/blob/bca31114da01be73b3af6e3f500c9b9ed91e8836/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L63

**Comment by chizhg** [comment]
Similar as https://github.com/knative/test-infra/issues/2392, we could use GitHub actions to do this.

**Comment by kellyaa** [comment]
@kvmware has already created this GH Action which includes yaml linting, but is not yet activated in all the repos: https://github.com/knative/actions/blob/main/.github/workflows/reusable_style.yaml

**Comment by kellyaa** [comment]
I'm thinking we can close this particular issue. The capability is there, just needs to be propagated to all the repos, which is  covered by this epic: https://github.com/knative/actions/issues/62

@kvmware - thoughts?

**Comment by kvmware** [comment]
Sounds good thanks @kellyaa :+1:
