### ISSUE TITLE
Support running multiple scripts in a single prow job

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1746]
Currently there are 2 ways of defining what runs in a Prow job:
- Use [`presubmit-tests.sh`](https://github.com/knative/test-infra/blob/master/scripts/presubmit-tests.sh) as entrypoint
- Invoke a script directly

As experimented in #1744, none of these currently work with multiple scripts, will need to figure out a way supporting running multiple scripts in a single Prow job

**Comment by adrcunha** [comment]
Easiest way is to expand --run-test to allow multiple parameters, then loop through them: https://github.com/knative/test-infra/blob/01760e2303d6a17936658f155004da3019d0f43c/scripts/presubmit-tests.sh#L362

**Comment by chaodaiG** [comment]
The PR #1780  doesn't work as expected  was reverted in #1790 

/reopen

**Comment by chaodaiG** [comment]
Some context, this is needed after this work was done: https://github.com/knative/serving/issues/6862

It used to be in all of our test flows, there was a single entry point like `test/e2e-tests.sh`, `test/e2e-upgrade-tests.sh`. Now we need to support multiple scripts in a single flow, see this PR for example: https://github.com/knative/test-infra/pull/1783/files

**Comment by chaodaiG** [comment]
Duplicate of #1811 
/close
