### ISSUE TITLE
k8s.log.txt being truncated

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#1750]
I think the k8s.log.txt is being truncated in continuous runs for knative-serving

**Comment by dprotaso** [comment]
nm - this is in knative serving

**Comment by chizhg** [comment]
Do you have an example for this? The `dump_cluster_state` function actually lives in test-infra - https://github.com/knative/test-infra/blob/edd308cb6d4b023d25722c40eb40cd8a612616ca/scripts/e2e-tests.sh#L90
