### ISSUE TITLE
Investigate how to prevent test-infra outage for release branches

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#177]
In light of test-infra issues coming out of https://github.com/knative/serving/pull/1922 and https://github.com/knative/serving/pull/2050#issuecomment-427389291, we need to define a process or automation to prevent such outage. 

What happened:
we have one prow config for all branches - we removed the ssh check recently in master and updated the scripts. But the release branches don't have the scripts update, only the ssh dependency removal from prow config, hence test-infra was broken for release branches and blocked merges for release branches.

What's needed:
Ideally prow config should also be per branch, hence as we fork the release branch, we fork the entire test-infra. 
Or we will have to backport test-infra changes to all release branches.

**Comment by adrcunha** [comment]
The SSH issue is just part of the problem. Prow being a live part of the infrastructure means that simple versioning won't solve the issue. The same applies for the other live parts involved, e.g., GKE. Take, for example, https://github.com/knative/serving/pull/2208: even if the SSH fix was backported previously, the authentication issue with newer GKE clusters would still exist and wouldn't have been caught.

I suggest having a lighter, maybe once a day, CI job for release branches. These jobs would be maintained and monitored as long as the release is supported, and would test all the configurations supported to ensure that new or live components won't break such release (e.g., a new GKE version).

**Comment by adrcunha** [comment]
The CI job for previous release branches is in place (currently there's only the 0.2 branch worth doing it):

https://testgrid.knative.dev/knative-serving-0.2
