### ISSUE TITLE
[oncall toil]Add periodic Prow jobs to automatically update images

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1773]
There is a list of images in the test-infra repo, see https://github.com/knative/test-infra/tree/master/images.

Currently when there are changes to these images, we manually run `make push` command to build and push the images. This process is tedious and lack of testing.

We should have periodic Prow jobs to update these images, and more importantly, we should make sure these images are properly tested before rolling out.

/kind enhancement

**Comment by chaodaiG** [comment]
We already have this for all other images but prow-tests https://testgrid.knative.dev/utilities#post-knative-test-infra-image-push

**Comment by chizhg** [comment]
We can do this for all other images but not `prow-tests` is because building it require a large amount of memory that we cannot provision in the Prow jobs, and the reasons are probably:

1. The image is based on `gcr.io/k8s-testimages/kubekins-e2e`, which is a pretty big image. We may consider getting rid of it and build the image from scratch, as it includes a lot of stuff that are not needed for Knative.

2. We are using `--no-cache` option to build the image just for the sake of updating `gcloud` every time, we may be able to remove this option once we figure out another way to update `gcloud`.

**Comment by chizhg** [comment]
We are now using cloud build to update the prow-tests image, see https://github.com/knative/test-infra/issues/2434, so all the images can be automatically update if relevant files changed in this repo (though some third-party dependencies like `kubetest2` cannot be automatically updated)
