### ISSUE TITLE
How to enable Istio local gateway for Kn client tests ?

### ISSUE THREAD

**Issue by rhuss** [knative/test-infra#1784]
With the kn client E2E tests we hit a [well known issue](https://github.com/knative/eventing/issues/1973) that a CronJobSource can access a Knative Service only via an Istio local gateway on GKE.

For the [kn E2E tests](https://github.com/knative/client/pull/698#issuecomment-593857882) we would need such a gateway to be available.

What would we need to do to enable the installation of this local gateway like described in this [documentation](https://github.com/knative/docs/blob/d4f56b2979aff631a25f1ed5395ff3794e41bd7c/docs/install/installing-istio.md#updating-your-install-to-use-cluster-local-gateway) ?

**Comment by rhuss** [comment]
// cc: @daisy-ycguo

**Comment by chizhg** [comment]
It seems the GKE cluster created for running e2e tests in client has Istio addon enabled, see more details in https://github.com/knative/test-infra/issues/1787.

Reading through the document you gave, the way to solve this issue should be disable the Istio addon, and install it by following https://github.com/knative/docs/blob/d4f56b2979aff631a25f1ed5395ff3794e41bd7c/docs/install/installing-istio.md.

But I guess there are some serving related e2e tests rely on the Istio addon, these tests may fail if you go with this approach.

**Comment by daisy-ycguo** [comment]
@chizhg  Maybe we don't need to disable Istio add-on, just install a local cluster gateway for e2e testing purpose by:

```
kubectl apply -f https://raw.githubusercontent.com/knative/serving/master/third_party/${VERSION}/istio-knative-extras.yaml
```

Could you tell me where to add this command ? I hope to have a try. Or else, we cannot support this e2e test case.

**Comment by rhuss** [comment]
@daisy-ycguo Is this still an issue and if so, maybe @chizhg has an advice how to enable the istio gateway for the e2e client tests ?
