### ISSUE TITLE
Gubernator: Show "needs approval"

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#1801]
Currently Gubernator shows me a "Status", which goes about as far as LGTM.

Two things I'd love to see are:
1. An indication of which PRs still need `/approve`,
2. An indication of which PRs have `do-not-merge/...` labels.

I'd also love to only see the things I have been `/assign`'d and other kinds of filters, but the above would help me triage a bunch since my dashboard gets fairly noisy.

**Comment by coryrc** [comment]
Gubernator is [deprecated](https://github.com/kubernetes/test-infra/pull/11302).

At the bottom of the page, there [is a link to where to file bugs](https://github.com/kubernetes/test-infra/issues/new?title=PR%20Dashboard:&labels=area/gubernator&assignee=rmmh).
