### ISSUE TITLE
Recursive hack/release.sh calls

### ISSUE THREAD

**Issue by aliok** [knative/test-infra#1804]
This is caused by https://github.com/knative/test-infra/pull/1802

`hack/release.sh` is calling itself recursively forever.

Execution:

```
$ git remote add upstream https://github.com/knative/serving-operator
$ git fetch "https://github.com/knative/serving-operator" release-0.13:upstream/release-0.13
From https://github.com/knative/serving-operator
 * [new branch]      release-0.13 -> upstream/release-0.13
$ git checkout upstream/"release-0.13"
Switched to branch 'upstream/release-0.13'

$ current_branch="$(git rev-parse --abbrev-ref HEAD)"
$ echo current_branch
upstream/release-0.13

```

In this stage, re-execution of the script checks if the `current_branch` is equal to `RELEASE_BRANCH`.
The check fails and re-executes again and again.

This is the check: `"${current_branch}" != "${RELEASE_BRANCH}"` in https://github.com/knative/test-infra/pull/1802/files#diff-0d28f82f2d1cc0deb12146b212778bc9R506

What happens is `current_branch = upstream/release-0.13` and `RELEASE_BRANCH = release-0.13`.
Then since they don't match, the script is triggered again: https://github.com/knative/test-infra/pull/1802/files#diff-0d28f82f2d1cc0deb12146b212778bc9R512

One solution would be using `git checkout -b "${RELEASE_BRANCH}" upstream/"${RELEASE_BRANCH}"` in https://github.com/knative/test-infra/pull/1802/files#diff-0d28f82f2d1cc0deb12146b212778bc9R509 
instead of `git checkout upstream/"${RELEASE_BRANCH}"` so that `git rev-parse --abbrev-ref HEAD` gives `release-0.13` instead of `upstream/release-0.13`.

See the timed out Prow logs here: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-operator-auto-release/1237891510012219392

**Comment by aliok** [comment]
cc @chizhg @mattmoor @chaodaiG @houshengbo 

This issue blocks the release of serving-operator 0.13. I haven't checked the others yet.

**Comment by aliok** [comment]
Also happens in eventing-operator. However, eventing and serving released fine because this change was not in when they were releasing.

**Comment by chaodaiG** [comment]
I think `checkout -b` is the good enough fix

**Comment by houshengbo** [comment]
Many thx to @aliok for working on this.
operators need it to push 0.13 artifacts.

**Comment by chizhg** [comment]
This issue has been fixed by https://github.com/knative/test-infra/pull/1806 and https://github.com/knative/test-infra/pull/1808.
/close
