### ISSUE TITLE
Prow command to list all possible tests to run on a PR

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#1805]
It's not obvious what tests I can run against a PR. I tend to go to the prow config in this repo but that's not ideal.

I'd be nice if prow have a command that would list all the tests.

**Comment by chizhg** [comment]
@cjwagner this sounds to be a very reasonable feature request. Has this issue ever been raised in Prow?

**Comment by cjwagner** [comment]
I haven't heard that request before, but I think its a really great idea! I imagine it would be an addition to Prow's [trigger plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/trigger) which is responsible for handling the `/test`, `/retest` and `/ok-to-test` commands. Something like `/test ?` of `/test-ls` for listing all the jobs that could be triggered would be very helpful.

Are either of you interested in contributing that feature to Prow? 😃

**Comment by cjwagner** [comment]
I added a feature request to k/t-i for this. https://github.com/kubernetes/test-infra/issues/16765

**Comment by chizhg** [comment]
This feature has been supported by https://github.com/kubernetes/test-infra/pull/16926. Now you can type `/test ?` or simply `/test` to check the supported tests.
