### ISSUE TITLE
Flakey test bot messages should provide more information

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#1807]
![Screen Shot 2020-03-12 at 11 14 53 AM](https://user-images.githubusercontent.com/18562/76536435-ba111900-6452-11ea-87ca-4cd54c7a9106.png)

Showing the test name is redundant

**Comment by dprotaso** [comment]
unless the test name column is supposed to show the failed test

**Comment by chaodaiG** [comment]
code lives here: https://github.com/knative/test-infra/tree/master/tools/flaky-test-retryer

**Comment by chaodaiG** [comment]
@Yizong98 , this was fixed by your PR https://github.com/knative/test-infra/pull/2268

See https://github.com/knative/serving/pull/8603#issuecomment-658430593

**Comment by chaodaiG** [comment]
So that you don't need to click the link above
![Screen Shot 2020-07-14 at 3 00 55 PM](https://user-images.githubusercontent.com/45011425/87480785-e5636a80-c5e2-11ea-9ce3-904c46c2770a.png)
