### ISSUE TITLE
Use gvm to install and switch different Go versions (?)

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1823]
For Knative projects, we need to have Prow jobs running with different Go versions, e.g. 1.12, 1.13, 1.14. The current way we handle them is to build [multiple test images](https://github.com/knative/test-infra/tree/master/images) with different Go versions installed, and we need to rebuild all the images if we want to make any changes to the base image.

There is a tool called [gvm](https://github.com/moovweb/gvm), with which we can install and switch multiple different Go versions in one single image. With it, we won't need to build and maintain multiple images for multiple Go versions.

Note:
Having multiple images may not be a problem when we have image auto-update process, so whether we need gvm depends on which way we want to move forward with.

**Comment by chizhg** [comment]
FYI @chaodaiG @coryrc

**Comment by chaodaiG** [comment]
`gvm` looks promising to me, the only question I have is how up-to-date is gvm with Go, in another word, does it require bunch of work for `gvm` to support a new Go version?

Thanks for the investigation!

**Comment by chizhg** [comment]
It seems not. The code for `gvm` hasn't been updated for a few years but clearly it still works with the latest Go versions.

**Comment by coryrc** [comment]
/reopen

I shouldn't have closed this issue until the image is deployed. The beta-testing jobs are telling me:

```
2020/05/13 02:37:28 Error collecting transitive dependencies: cannot find package "_/home/prow/go/src/knative.dev/serving/cmd/activator" in any of:
	/root/.gvm/gos/go1.13.10/src/_/home/prow/go/src/knative.dev/serving/cmd/activator (from $GOROOT)
	/root/.gvm/pkgsets/go1.13.10/global/src/_/home/prow/go/src/knative.dev/serving/cmd/activator (from $GOPATH)
```

so will need to do something about GOPATH when switching

(from https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-0.14-continuous-beta-prow-tests-chizhg/1260398562286505984)
