### ISSUE TITLE
Support dot release from old release branches

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1827]
Current dot-release jobs only detects changes from latest release branch and creates new tags on top of latest release branches, there is no way to automate dot release from old release branches. This should be supported

This is part of #1782

**Comment by chaodaiG** [comment]
The easiest way to support this would be define `RELEASE_BRANCH` environment variable in Prow dot-release jobs, and creating a dot-release job for each old release branch will be needed. 

Currently we support n-3 ... n  release branches, i.e. at the time of creating this bug the latest release branch in serving is 0.13, so we'll have dot-release jobs for 0.10, 0.11, 0.12, and 0.13

**Comment by chizhg** [comment]
Fixed by #1828 

/close
