### ISSUE TITLE
./hack/update-codegen.sh fails in some bash environment

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1856]
From https://github.com/knative/test-infra/pull/1851#issuecomment-603522333, `./hack/update-codegen.sh` fails with below error:

```
$ ./hack/update-codegen.sh 
/Users/evana/go/src/knative.dev/test-infra/hack/update-deps.sh: line 44: DEP_FLAGS[@]: unbound variable
```

The bash version is:
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by coryrc** [comment]
Anybody using a Mac needs to install a newer bash, that's why every file has to have `#!/usr/bin/env bash` instead of `#!/bin/bash`.

/close
