### ISSUE TITLE
Test-infra integration tests are failing after new prow-tests image

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1858]
See here:
https://testgrid.knative.dev/test-infra#continuous

Integration tests failed to install serving in test-infra, but interestingly not in other repos that also consumes serving nightly builds, an example: https://testgrid.knative.dev/docs

The main difference is test-infra is using cluster management lib while doc is not

**Comment by chizhg** [comment]
`knative-gcp` also started failing https://testgrid.knative.dev/knative-gcp#continuous. I have reverted the image.

**Comment by chizhg** [comment]
The issue is caused by `kubectl`, I'm trying to understand it happens.

**Comment by chizhg** [comment]
One link https://prow.knative.dev/view/gcs/knative-prow/logs/ci-google-knative-gcp-continuous/1243183756710252544

**Comment by chizhg** [comment]
Created https://github.com/knative/serving/issues/7755 for tracking.

**Comment by coryrc** [comment]
This should be renamed to "use serving-crds.yaml in place of serving.yaml".

**Comment by chizhg** [comment]
This issue has been fixed in serving and test-infra, and populated to other Knative repos.
