### ISSUE TITLE
Testgrid links to wrong job type

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1864]
https://testgrid.knative.dev/serving#conformance  When you click on any build, it will direct to a continuos build. NOT conformance build.

**Comment by houshengbo** [comment]
We do not even have job called `ci-knative-serving-conformance` to run conformance tests. We probably need to create it first, then link to the conformance builds.

**Comment by chizhg** [comment]
Currently we are running both e2e and conformance tests in https://github.com/knative/serving/blob/master/test/e2e-tests.sh. So the real request for this issue is to separate them into two flows, for both `presubmit` and `periodic` jobs?

+ @mattmoor  for comments.

**Comment by coryrc** [comment]
WAI

the conformance tests are in that test run
/close
