### ISSUE TITLE
Migrate all Knative projects to use Go Modules

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1875]
Currently all Knative projects (except client) are using Go `dep` to manage the dependencies, but Go `dep` is going to be deprecated soon in favor of the official Go dependency management tool - Go Module. We should switch all Knative projects to use Go Modules.

/kind feature-request

**Comment by chizhg** [comment]
After some investigation, the only blocker for us is the [`dep-collector`](https://github.com/knative/test-infra/tree/master/tools/dep-collector). 

If we move the project out of `$GOPATH` and run with `GO111MODULE=auto`, there will be an error:
Error collecting transitive dependencies: package test-infra/tools/prow-auto-bumper is not in GOROOT (/usr/local/go/src/test-infra/tools/prow-auto-bumper)
`ko` fixed this issue in https://github.com/google/ko/pull/50.

Instead of fixing `dep-collector`, the other option is to switch to another tool - https://github.com/google/go-licenses.

**Comment by chaodaiG** [comment]
I think this is done @chizhg
