### ISSUE TITLE
Presubmit microbenchmarks task

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/test-infra#1906]
As discussed in [Eventing Performance Task Force Meeting 15/04/2020](https://docs.google.com/document/d/1UgblGknPcIMcOfUc_UImUAyjTGTfZNWXZV1_iPsDntY/edit?usp=sharing), we need a prow task that runs on every PR and executes the microbenchmarks available around the repository.

The following task should perform these actions:

1. Run microbenchmarks from master
2. Run microbenchmarks from PR revision
3. Use [benchstat](https://godoc.org/golang.org/x/perf/cmd/benchstat) to generate an HTML report that check the difference between the two
4. Publish the report and provide the link from the prow task page

**Comment by coryrc** [comment]
If you write a program (executable or shell script) in your repo that does 1&3, we can help you plumb it into the test flows.

**Comment by slinkydeveloper** [comment]
@coryrc ok i can give it a try, where should i pr these scripts?

**Comment by coryrc** [comment]
eventing or eventing-contrib I assume? @chizhg

**Comment by chizhg** [comment]
> eventing or eventing-contrib I assume? @chizhg

Yeah eventing should be the right place.

**Comment by slinkydeveloper** [comment]
All yours: https://github.com/knative/eventing/pull/3151

**Comment by coryrc** [comment]
Note to myself or team: "You can get a link to it in the top bar by adding a reference to it in finished.json."

I'm not sure how to do that yet, but it means we can make a link to the HTML you generate from the Spyglass page (the one that pops up when you click on the job in TestGrid or details from a PR).

**Comment by slinkydeveloper** [comment]
Now that the scripts are merged in eventing master, how can we setup the task? We don't need to automatically run them, the idea was to run these with a command like `/run-benchmark`

**Comment by chizhg** [comment]
You can add a custom job like https://github.com/knative/test-infra/blob/fac473dda98b6867b825ec79296e06960e8d6f88/config/prod/prow/config_knative.yaml#L235-L239, and run `./hack/generate-configs.sh` to generate the actual Prow job configuration. After you submit the PR and it's merged, you will be able to trigger the job with `/test pull-knative-docs-[job-name]` command on PRs in eventing.

Some notes for the job configuration:
If you don't need to always run it, you can have `always-run: false`. If you don't want its failure to block on presubmit, you can have `optional: true`.
