### ISSUE TITLE
Continuos microbenchmark runs with historical reporting

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/test-infra#1907]
As discussed in [Eventing Performance Task Force Meeting 15/04/2020](https://docs.google.com/document/d/1UgblGknPcIMcOfUc_UImUAyjTGTfZNWXZV1_iPsDntY/edit?usp=sharing), we need a prow task that runs microbenchmarks periodically and store the results.

**Comment by coryrc** [comment]
@chizhg is this feasible to easily add to the continuous Mako runs or should it be a CI job running the same outputs as #1906 ?

**Comment by slinkydeveloper** [comment]
Not sure, let's try to tackle first the #1906 and then we'll figure out this one too

**Comment by slinkydeveloper** [comment]
/remove-lifecycle-stale

Now we have script to run benchmarks, what are we missing to complete this issue?
