### ISSUE TITLE
Move the installation of ko out of Dockerfile to the base bash scripts

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1912]
Currently we are installing `ko` and a few other tools in the prow-tests image, and all the Prow jobs for Knative are using the same image. Since `ko` does not have a good support for backward compatibility, sometimes it can cause issues for jobs running on the old release branches, see one example in https://github.com/knative/serving/pull/7597#issuecomment-615016991.

As now we are releasing test-infra together with other Knative projects, one way to solve this issue would be installing `ko` in the base bash scripts so that it can always be properly versioned. We should also considering installing some other tools that are not always backward compatible, e.g. `gcloud` and `kubectl`.

**Comment by coryrc** [comment]
The linked problem is a bug in `ko` or a bug in the script. Whichever one was the source should have been fixed, rather than paper over the problem.

Additionally, I thought we only supported N-2:N releases; given release-0.14 is out, I don't believe we support 0.11 any more.

**Comment by chizhg** [comment]
We support N-3:N releases for Knative. But it's not important to this issue as such kind of issue can happen on any branch.

**Comment by coryrc** [comment]
It matters because a problem on the oldest supported version has probably been fixed, it does not affect users, and it should be the releaser's responsibility to backport the fix.
