### ISSUE TITLE
Coverage job in prow does not support cgo builds

### ISSUE THREAD

**Issue by davyodom** [knative/test-infra#1945]
The eventing-kafka repo in knative-sandbox requires some c libraries to be preinstalled before running go test/build.  We don't have any access to do this or run in a docker container for the coverage job.

As an example : https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka/2/pull-knative-sandbox-eventing-kafka-go-coverage/1252983884107223042/build-log.txt

```
2020/04/22 15:35:15 Error running 'go test -coverprofile ': error='exit status 2'; combined output='# pkg-config --cflags  -- rdkafka
Package rdkafka was not found in the pkg-config search path.
Perhaps you should add the directory containing `rdkafka.pc'
to the PKG_CONFIG_PATH environment variable
No package 'rdkafka' found
pkg-config: exit status 1
```

**Comment by davyodom** [comment]
@chaodaiG In the meantime, can we just disable the coverage job for knative-sandbox/eventing-kafka so we aren't blocked on merging?

**Comment by chaodaiG** [comment]
Make sense, see https://github.com/knative/test-infra/pull/1968

**Comment by davyodom** [comment]
@chaodaiG, the build has since been refactored and simplified in eventing-kafka, the standard coverage job should now work (I think). Can we re-enable and verify?

**Comment by chaodaiG** [comment]
> @chaodaiG, the build has since been refactored and simplified in eventing-kafka, the standard coverage job should now work (I think). Can we re-enable and verify?

Sure, see #2110

**Comment by davyodom** [comment]
Looks like there is some problem here? https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka/14/pull-knative-sandbox-eventing-kafka-go-coverage/1263888166427824128/build-log.txt

**Comment by chaodaiG** [comment]
> Looks like there is some problem here? https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka/14/pull-knative-sandbox-eventing-kafka-go-coverage/1263888166427824128/build-log.txt

I think this is because of the chicken and egg problem: coverage job needs at least one passed postsubmit coverage job serving as baseline for delta computation. The easiest fix is ignore the coverage result for the first PR then it'll establish a baseline

**Comment by davyodom** [comment]
They seems to still be failing after a few different PRs have been merged, something else required to get it working?
https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka/20/pull-knative-sandbox-eventing-kafka-go-coverage/1265734217526939650/build-log.txt

**Comment by chaodaiG** [comment]
Yes, sorry we ran into a bug with prow, and talking actively with k8s prow folks to see how to resolve this

**Comment by chaodaiG** [comment]
I think this is fixed, may need to have one more PR merged to get it working

**Comment by davyodom** [comment]
Still there!
https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka/21/pull-knative-sandbox-eventing-kafka-go-coverage/1267904842634891265/build-log.txt

**Comment by chizhg** [comment]
It looks the jobs could pass - https://prow.knative.dev/job-history/gs/knative-prow/pr-logs/directory/pull-knative-sandbox-eventing-kafka-go-coverage (the failing jobs seem to be real failures), so we should be able to close it now?

**Comment by davyodom** [comment]
Yes, looks fine now.  We can close it, thanks!
