### ISSUE TITLE
Prow staging does not work if a new PR is merged during the process

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1950]
Currently we are using the `pull` bot to create a PR to sync the changes to the forked repo, after a PR in the main repo is merged. It will only create a PR even if there are multiple PRs merged in the main repo.

The Prow staging process relies on this PR to test if the staging Prow is working, by leaving `/lgtm` and `/approve` on that PR, and then wait for the PR to be merged. But if a new PR in the main repo is merged when it's waiting, a new commit will be added by the `pull` bot in the forked PR and cause the `lgtm` label to be removed, then the PR will never be merged and the staging process will fail for sure.

**Comment by chaodaiG** [comment]
Staging prow isn't relevant any more

/close
