### ISSUE TITLE
Run simple workloads using Github Actions

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1960]
As discussed in Knative productivity WG meeting on 04/24/2020, it was proposed to use Github Actions side by side with Prow for some simple workloads, such as:
- config checker
- build/unit test
- maybe release

The nice thing about using Github Actions are:
- It's free for public repos
- In repo config
- It works better with templated repos, such as sample-source

There are several things need to be confirmed:
- What's the resource limit(cpu, mem, etc.) for free tier? 
- Do we need to get a paid tier?
- Compiling serving can use up to 12 Gb of memory, will this be a problem if multiple of this running concurrently?

cc @chizhg , @cardil, @n3wscott

**Comment by chizhg** [comment]
Another thing we want to investigate is how this works with Tide, e.g. if one test is controlled by GitHub Actions and is marked as `required` in the branch protection rule, how will Tide detect it? Will Tide keep retrying to merge the PR if the test is not passed? 
That's one reason I added https://github.com/knative/test-infra/blob/master/config/prow/core/config.yaml#L146, but I'm not sure if it's actually needed or not, and if we need similar setups for GitHub Actions related tests.

**Comment by chaodaiG** [comment]
tide only relies on `required:true` label in Prow job config afaict, the branch protection rule is a duplicate of this. So this shouldn't be a problem as tide doesn't even care about the existence of jobs defined by Github Actions. see this issue I created in k8s/test-infra: https://github.com/kubernetes/test-infra/issues/16472

**Comment by chizhg** [comment]
Yeah I know. But I think the actions for Tide will be different in these two scenarios. Instead of doing
```
try to merge the PR until all labels are present, all Prow jobs are passed
```
, it will do
```
try to merge the PR while the GitHub Actions test is failed or still running, 
but GitHub does not allow it to be merged, so Tide will keep retrying
```

**Comment by chaodaiG** [comment]
Ah. I see. That makes sense now. This will need to be better supported by tide if it doesn't currently

**Comment by markusthoemmes** [comment]
I think we also need to make sure we have testgrid integration. Unit test flakes shall be visible there.

**Comment by coryrc** [comment]
We should be reducing the number of disparate system we need to support and configure, not increasing them.

**Comment by coryrc** [comment]
> The nice thing about using Github Actions are:
> 
> * It's free for public repos

We already have Prow.

> * In repo config

Prow supports this, our template generator does not.

> * It works better with templated repos, such as sample-source

Not if we put the test scripts into prow-tests (oops, already did!)

**Comment by chizhg** [comment]
> I think we also need to make sure we have testgrid integration. Unit test flakes shall be visible there.

If we run the tests for multiple times, as what's being tried in https://github.com/knative/test-infra/pull/1615, it will be much unlikely to have flaky tests, then I guess testgrid integration won't be that important?
@markusthoemmes @chaodaiG @mattmoor @n3wscott since we have started moving to GitHub actions, it would be better to reach an agreement here.

**Comment by n3wscott** [comment]
The end goal is a test infra that is open to the community and anyone who wants to can contribute to the entire stack. At the moment this is not possible, github actions help open up the infra.

**Comment by markusthoemmes** [comment]
I agree with @n3wscott.

@chizhg i don't quite parse your comment. Increasing the runcount will increase the likelyhood of flakes. Each failure from each run will be reported so I'd think testgrid integration is still of importance.

**Comment by chizhg** [comment]
Sorry for the confusion.

What I meant is since we run unit tests as presubmit tests, and we require
all tests pass to merge a PR, running them multiple times will more likely
expose the flaky tests, thus force the PR author to fix them. Theoretically
in this way the flaky test rate will be gradually reduced.

**Comment by coryrc** [comment]
> The end goal is a test infra that is open to the community and anyone who wants to can contribute to the entire stack. At the moment this is not possible, github actions help open up the infra.

The current infra is all open source except for TestGrid.

github.com/knative/test-infra

https://github.com/kubernetes/test-infra/tree/master/prow

It's just few choose to contribute.

**Comment by chaodaiG** [comment]
This had been fixed

/close
