### ISSUE TITLE
run_job.sh is broken

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#1967]
It failed to find default plank config:
```
FATA[0000] Error loading config                          error="no default decoration config provided for plank"
```

I think it's related to #1939, and the root cause is we are using a very old commit id in k8s/test-infra for bazel

/cc @chizhg

**Comment by chaodaiG** [comment]
In the short term, we can fix it by cloning k8s, but in the long run, we should address #1970

**Comment by chizhg** [comment]
This issue has been fixed by https://github.com/knative/test-infra/pull/1981
