### ISSUE TITLE
As a contributor I'd like the instruct prow to run a test for a PR N times

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#197]
In this PR https://github.com/knative/build/pull/430 I'm trying to flush out a flakey test

I repeatedly need to invoke `/test pull-knative-build-integration-tests` in order to run the test numerous times in hopes of guaranteeing there is no flakiness

It'd be nice if I could type something along the lines of
```
/test pull-knative-build-integration-tests 10
```

This would run the integration test sequentially ten times and stop at any point if there is a failure

**Comment by adrcunha** [comment]
This is another feature request that seems more appropriate to be filed under kubernetes/test-infra IMO.

**Comment by dprotaso** [comment]
Sure

**Comment by adrcunha** [comment]
Workaround if you want to test a PR several times (say, 50) just like Prow:

```
export PROJECT_ID=my_awesome_gcp_project; for i in {1..50}; do ./test/presubmit-tests.sh ; done
``` 

`PROJECT_ID` must point to a GCP project you own, and this line must be run from the root of your repo/branch (so it includes your changes).

**Comment by adrcunha** [comment]
Feedback in 9855 is not favorable, due to concerns about abusing the feature. If that issue gets closed due to staleness, I'll close this one as well as infeasible.

**Comment by jessiezcc** [comment]
Close because it's outside the scope of Knative.
