### ISSUE TITLE
Enable autoscaling in Prow build cluster

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#1974]
Need to first update to 1.15
Enable NodeLocal DNSCache
Then enable autoscaling
/assign @chaodaiG 
(feel free to reassign if desired)

**Comment by chaodaiG** [comment]
To avoid failing badly, created another build cluster and updated it to 1.15, test ran a test-infra job on it and it all went well: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-test-infra-continuous/1254862679047147521

I think it's relatively safe to update cluster

**Comment by chaodaiG** [comment]
Need to first update to 1.15: Done
Enable NodeLocal DNSCache: Ongoing

**Comment by chaodaiG** [comment]
Done

/close
