### ISSUE TITLE
Enable non-Googlers to rescan PRs

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#1975]
https://github.com/knative/net-contour/pull/108#issuecomment-619187191

**Comment by coryrc** [comment]
Internal bug filed

**Comment by coryrc** [comment]
156525597 is the bug number

**Comment by coryrc** [comment]
Normally the PR owner can request a rescan, but in this case being a bot, it requires a googler to do it and it's not a priority for that team to tackle the issue otherwise.
/close

**Comment by coryrc** [comment]
There is a "recheck" functionality built into Github now. Any person in the Collaborator role can trigger the recheck, which will, in turn, have CLA bot rescan a PR.
