### ISSUE TITLE
git command listing changed files gets warnings when there are too many changed files

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#1983]
The git command in https://github.com/knative/test-infra/blob/bf3e6802597ac31776a8e3e62b32d51744b2ae77/scripts/presubmit-tests.sh#L52 gets warnings when there are too many changed files, one example is in https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_serving/7734/pull-knative-serving-unit-tests/1254884557732188162#1:build-log.txt%3A3

/cc @chaodaiG

**Comment by chaodaiG** [comment]
To be more specific, this is too many renames:
```
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 1085 and retry the command.
```

Technically the test behavior is not affected by this warning, as this PR already had > 2000 lines of diff discovered, which we can assure that all tests will run. 

However, we could easily get over this by `git config diff.renames 0` as described here: https://stackoverflow.com/questions/7830728/warning-on-diff-renamelimit-variable-when-doing-git-push
