### ISSUE TITLE
Run tests concurrently to reduce overall test duration 

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#20]
As we drive up code coverage numbers, # of tests (especially unit tests) increase significantly. 
@evankanderson reported overall it's taking 30+min to run the tests, we should look at how much we can save if we run tests concurrently. go test has a parallel option that supports concurrency.  

We can start with unit tests first.

**Comment by adrcunha** [comment]
Obsoleted by https://github.com/knative/serving/issues/3247
