### ISSUE TITLE
Prow autobumper is getting an error

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2012]
The Prow autobumper job throws out an error in the last run:
`2020/05/04 20:01:40 failed updating files: 'failed to change to root dir'`

See details in https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-prow-auto-bumper/1257399883074113537

/assign @chaodaiG

**Comment by chaodaiG** [comment]
Couldn't repro locally

**Comment by chaodaiG** [comment]
This job runs from an image, which hasn't been updated since March: gcr.io/knative-tests/test-infra/prow-auto-bumper. Something wrong with the environment running it
