### ISSUE TITLE
Update playbook for Prow config updater & staging Prow

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2037]
The playbook predates the Prow config updater and staging Prow.

As oncall, I received a PR to auto-update staging Prow. What do I do after it has been approved? It seems manual update is no longer necessary?

What do I do after the staging Prow is updated? Is there another automatic PR bump for the regular Prow? Will that auto-update? How do I do an emergency rollback -- still manual push from slightly older branch? What permissions do I need to get first?

/assign @chizhg

**Comment by chaodaiG** [comment]
These are not relevant any more

/close
