### ISSUE TITLE
e2-tests.sh script sourcing doesn't work properly with zsh

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/test-infra#2042]
I'm trying to follow this guide https://github.com/knative/test-infra/blob/master/scripts/README.md but it doesn't work properly on Fedora 32 with zsh as default shell.

I found somewhere in the codebase of the scripts some bash specific vars like `$BASH_SOURCE`: https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L20 while it should use https://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh

**Comment by slinkydeveloper** [comment]
I've also tried to run the script from bash, like:

```
(kafka_source_tracing)⚡ [127] % bash                                                                                                                                                                   
[slinkydeveloper@localhost eventing-contrib]$ source test/e2e-tests.sh 
error: set $PROJECT_ID or use --gcp-project to select the GCP project where the tests are run
```

But after the script is ran, it quits from bash and goes back to zsh

**Comment by coryrc** [comment]
You shouldn't "source" the script, just run it:
`(kafka_source_tracing)⚡ [127] % test/e2e-tests.sh`

/close

**Comment by slinkydeveloper** [comment]
@coryrc that's what i read here to use separately the setup/teardown functions: https://github.com/knative/test-infra/blob/master/scripts/README.md

Then i suppose this guide needs to be updated

**Comment by coryrc** [comment]
I'm sorry it's not clear, it's describing how to write your own script and we only support bash.
