### ISSUE TITLE
e2e-tests: Passing tags fails running e2e tests

### ISSUE THREAD

**Issue by navidshaikh** [knative/test-infra#2064]
**Issue 1:** 
Passing multiple tags fails running e2e tests

Steps to re-produce:
1 - Pass multiple e2e tags to `go_test_e2e` [ref](https://github.com/knative/client/pull/830/files#diff-0bff8fdbdcedf4cfbdcab24558df0df2R55)
```
go_test_e2e -timeout=45m -tags "e2e serving" ./test/e2e || fail_test
```

2 - Fails with error: `go test: tags flag may be set only once` because there is an additional `-tags=e2e` added to the `go test` command ref: [logs](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/830/pull-knative-client-integration-tests-latest-release/1260654500058763265#1:build-log.txt%3A537)

<hr>

**Issue 2:**
 If passed multiple tags to `report_go_test`, it will not quote the tags, which causes `go test` to find tests in N+1 arg of the values passed to  `-tags`
Steps to re-produce:
```
report_go_test -v -race -count=1 -timeout=45m -tags "e2e serving" ./test/e2e
```
(it will try and find the `serving` dir in this case)

ref: https://github.com/knative/client/pull/830

**Comment by coryrc** [comment]
For the first, you need to do `-tags="e2e serving"`, then it will work (note I added an equals sign).

For the second, if the above does not fix your problem, then adding single quotes probably will:
`"-tags='e2e serving'"`

/close

**Comment by navidshaikh** [comment]
For first, using `-tags="e2e serving"` prevents repeating `-tags` flag. 

<hr>

For second, adding single quotes as suggested doesnt help
```
Running tests with 'go test -v  -race -count=1 -timeout=45m -tags='e2e serving' ./test/e2e '
invalid flag argument for -tags: unterminated ' string 
```

ref: [log](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/830/pull-knative-client-integration-tests/1260888542058385408#1:build-log.txt%3A524)

**Comment by coryrc** [comment]
Did you try with just double quotes first?

Because `go_test_e2e` calls `report_go_test` so it should work

**Comment by navidshaikh** [comment]
Yes, I tried as
```
go_test_e2e -timeout=45m -tags="e2e serving" ./test/e2e || fail_test
```
which gives
```
Running tests with 'go test -v  -race -count=1 -timeout=45m -tags=e2e serving ./test/e2e '
can't load package: package serving: malformed module path "serving": missing dot in first path element
Finished run, return code is 1
XML report written to /tmp/tmp.MfYTqcv9Ae/junit_ujSjtY1h.xml
Test log written to /tmp/tmp.MfYTqcv9Ae/go_test_ujSjtY1h.log
***************************************
***         E2E TEST FAILED         ***
[...]
```

**Comment by chizhg** [comment]
Hi @navidshaikh , could you try updating test-infra and running this again?
Recently I made some change in the `go_test_e2e` which I think fixed this issue.

**Comment by chizhg** [comment]
No, it's not fixed.
I'm checking now.

**Comment by chizhg** [comment]
Just confirmed it's fixed, you need to run the command as:
`report_go_test -v -race -count=1 -timeout=45m -tags="e2e serving" ./test/e2e`
