### ISSUE TITLE
Cannot update shell scripts independently

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2069]
During a test run, we use a collection of shell scripts to run `go build`, `go test`, acquire clusters, install serving, check markdown links, etc. The master source of these shell scripts is in knative/test-infra. Each repo carries of copy of these shell scripts and some extend them by `source`ing them and adding functionality.

When a release is cut, these scripts stop being kept in sync with knative/test-infra. Lesser-maintained repos also rapidly fall out of sync. Example problems [1](https://github.com/knative/test-infra/pull/1520) [2](https://github.com/knative/client/pull/610) [3](https://github.com/knative/eventing-contrib/pull/419) [4](https://github.com/knative/eventing-contrib/pull/448) [5](https://github.com/knative/eventing/pull/1253) [6](https://github.com/knative/test-infra/pull/828) Sometimes the problems are a change in test-infra repo which is not caught until it is vendored into multiple other repos before causing outages, necessitating rapid updates to those scripts across multiple repos. Others are external changes that need to be replicated across multiple repos, including older branches that have fallen out-of-sync, causing even more headache.

Those problems necessitate the ability to easily and quickly update shell scripts in isolation to other changes. We have used dep for that, poorly, but at least it would allow you to only update the scripts. Now with Go modules, it does not work; it is pulling in transitive dependencies of other programs in that repo, but which the shell scripts do not use. See knative/client#841 if you don't believe me.

This presents us with options:

1. Create another repo with just the shell scripts
2. Use a non-Go way to update this dependency which does not contain any Go code
3. Go [multi-module repository](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories) with the scripts in their own "module"

Step 1 is a lot of work and ongoing maintenance cost and strictly inferior to 3.
Step 2 makes it easier than ever to do emergency fixes while changing none of the user interface.
Step 3 is acceptable but continues to hack a tool designed for a different purpose.

Step 2 is incremental, [ready to go](https://github.com/knative/test-infra/pull/2068), and [ready to be used](https://github.com/knative/client/pull/840).
Step 3 is still exposed to a lot of [gotchas](https://github.com/golang/go/wiki/Modules#some-needed-files-may-not-be-present-in-populated-vendor-directory)

_

_

Extra information:

All tests in Prow run in a container whose image is maintained by the Productivity team. We currently have to support 5 different, but similar images for running tests with no way to test them before deployment. I have [created jobs](https://github.com/knative/test-infra/pull/2044) and added [a dashboard](https://testgrid.knative.dev/beta-prow-tests) for testing images, but it is not reasonable to expect our team to maintain so many different images when it is unnecessary. These images have a set of tools common for all repos: Go, ko, gcloud, shellcheck, dep, go-licenses, junithelper.

When we create a problem in shell scripts, it takes hours of manual work to clean up (see example problems). When we create a problem in the Prow test image, it can be [rolled back in minutes](https://knative.slack.com/archives/CCSNR4FCH/p1588923882199700). It would be nice to keep the shell scripts in the prow-tests image and make sure they are backward-compatible, but this may be too difficult with the amount of customization in serving.

This is coming up now because knative/client has been using Go modules for a while. The newest version of the dep-collector tool does not work with repos that use dep (all repos but knative/client) and the just-previous version does not work with Go modules, which is why we switched the scripts to use go-licenses when switching to Go modules. I tried to update just scripts in knative/client, but ran into the linked problem. This is bad if we need to do an emergency release in the future, now that all repos are using it! The test-infra team needs to be able to provide updates to the branches that don't affect the running code in order to keep CI working. Additionally, by not being able to switch this one repo to use go-licenses (both master and past releases) I cannot deploy a unified Prow test image across all the repos.

Finally, because some of the scripts are using the tools from test-infra/master (via `go get`), we often break flows by changing tools and there's no way this is surfaced today. For example, knative/client [0.13](https://testgrid.knative.dev/knative-0.13#client-continuous) and [0.14](https://testgrid.knative.dev/knative-0.14#client-continuous) are broken due to a change in dep-collector. There was no way easy way to test this change before deploying nor a good way to even roll it back (because other repos are dependent on that change to work).

**Comment by chizhg** [comment]
To add some clarity, `go mod` update is following the [Minimal Version Selection](https://github.com/golang/go/wiki/Modules#faqs--minimal-version-selection) to update modules. 

So in your case that updates `test-infra` for `client`, it checks the version of `knative.dev/pkg` in the `go.mod` file of `test-infra`, which is `v0.0.0-20200514052058-c75d324f8b8b` and exactly the version `client` was updated to. The update for `pkg` also incurs updates for other modules it references to, that's why you were seeing so many changes. But since every Knative repo is supposed to vendor the HEAD of `pkg` eventually, this is not a serious problem and won't mysteriously break the build for sure.

**Comment by mattmoor** [comment]
The example in knative/client#841 pulls in a months worth of test-infra changes, and (as discussed in slack) test-infra has an ill-advised dependency on knative/pkg which pulls that into the solution space when running `go get -d knative.dev/test-infra` (as @chizhg points out before I can hit send!).

In a world where we've adequately snapped release branches for test-infra and pkg, would pulling down script-only updates from the release branch of test-infra via `go get -d knative.dev/test-infra@release-0.XY` result in the sort of change you are seeing?  I'm skeptical.

I was really looking for a clearer statement of the problem without the solution laced in 🤷‍♂️

**Comment by coryrc** [comment]
In an ideal world, we have only one set of scripts and they're tested before being updated.

It shouldn't matter what libraries test-infra uses! We don't use it for Go code, we just include it. If we had never entangled them in the first place, there'd be no reason to entangle them today.

**Comment by coryrc** [comment]
> To add some clarity, `go mod` update is following the [Minimal Version Selection](https://github.com/golang/go/wiki/Modules#faqs--minimal-version-selection) to update modules.
> 
> So in your case that updates `test-infra` for `client`, it checks the version of `knative.dev/pkg` in the `go.mod` file of `test-infra`, which is `v0.0.0-20200514052058-c75d324f8b8b` and exactly the version `client` was updated to. The update for `pkg` also incurs updates for other modules it references to, that's why you were seeing so many changes. But since every Knative repo is supposed to vendor the HEAD of `pkg` eventually, this is not a big issue and won't mysteriously break the build for sure.

**Comment by mattmoor** [comment]
Ack, and I agree.

We're not in an ideal world, and unfortunately it does matter what libraries test-infra uses.  I'd love to see us disentangle things, and get ourselves to a better place; however, rushing that in the closing week(ish) of our milestone isn't the right time to try and do that.

I am looking for a clear statement of the problem so that we can assess more tactical options (including "do nothing") in the next 2 business days.

When 0.16 opens, I'd love to see us aggressively move to a world without these entanglements, but this is the 11th hour for 0.15.  Can it wait?  If not, why not?  If so, then let's talk about the ideal world we want to live in and come up with a plan to execute for 0.16.

**Comment by coryrc** [comment]
> Ack, and I agree.

> I am looking for a clear statement of the problem so that we can assess more tactical options (including "do nothing") in the next 2 business days.

It's trivial to backport, so we don't need to do anything in the next 2 days.

> When 0.16 opens, I'd love to see us aggressively move to a world without these entanglements, but this is the 11th hour for 0.15. Can it wait? If not, why not? If so, then let's talk about the ideal world we want to live in and come up with a plan to execute for 0.16.

It can wait.

**Comment by coryrc** [comment]
840 did it
