### ISSUE TITLE
update_licenses pulls more than just license files

### ISSUE THREAD

**Issue by antoineco** [knative/test-infra#2071]
As seen in knative/eventing-contrib#1232, update_licenses copies more than just LICENSE files.

Example: https://github.com/knative/eventing-contrib/tree/master/third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid

**Comment by chizhg** [comment]
This is expected for the [go-licenses](https://github.com/google/go-licenses) tool, see https://github.com/google/go-licenses/blob/master/save.go#L97-L102

If the license type is `Restricted` or `Reciprocal`, it will need to copy the entire source directory instead of just the LICENSE file.
