### ISSUE TITLE
Prow logs contains lots of crier errors

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#2081]
The same crier error is appearing at a steady rate of ~20 times per minute. One of the example from stackdriver is:
```
jsonPayload: {
  component: "crier"   
  error: "[Post https://www.googleapis.com/upload/storage/v1/b/knative-prow/o?alt=json&ifGenerationMatch=0&prettyPrint=false&projection=full&uploadType=multipart: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: write tcp 10.60.20.189:49360->64.233.181.95:443: write: broken pipe, Post https://www.googleapis.com/upload/storage/v1/b/knative-prow/o?alt=json&prettyPrint=false&projection=full&uploadType=multipart: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: write tcp 10.60.20.189:49360->64.233.181.95:443: write: broken pipe]"   
  file: "prow/crier/controller.go:280"   
  func: "k8s.io/test-infra/prow/crier.(*Controller).processNextItem"   
  jobName: "cd38ddb6-991a-11ea-a409-7eeb3588fb44"   
  jobStatus: {…}   
  level: "error"   
  msg: "failed to report job"   
  prowjob: "default/cd38ddb6-991a-11ea-a409-7eeb3588fb44"   
 }
```

A better format of the error message:
```
Post https://www.googleapis.com/upload/storage/v1/b/knative-prow/o?alt=json&prettyPrint=false&projection=full&uploadType=multipart: 
oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: 
write tcp 10.60.20.189:49360->64.233.181.95:443: write: broken pipe
```

**Comment by chaodaiG** [comment]
This has been happening since 2020-04-18 09:23:39.000 PDT

**Comment by chaodaiG** [comment]
This problem also blocks some of the PRs from reporting. Since it's known that restarting crier can temporarily alleviate the problem, rebooting crier to unblock them while investigating

**Comment by chaodaiG** [comment]
Link of stackdriver log:
https://pantheon.corp.google.com/logs/viewer?project=knative-tests&minLogLevel=0&expandAll=false&customFacets=jsonPayload.component,jsonPayload.level&limitCustomFacetWidth=false&interval=PT1H&resource=container%2Fcluster_name%2Fprow%2Fnamespace_id%2Fdefault&pli=1&rapt=AEjHL4M7zLSOVoHMAmPPK7cly20iLMJFTCQ0X2WnE6bNA7VOL1lblvqZ-AXQ1Eonb5DmO3Z5cb23vEh0_3a1TAV0SAtLjdWlMQ&timestamp=2020-05-18T17:15:19.050000000Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22prow%22%0Aresource.labels.namespace_id%3D%22default%22%0ANOT%20jsonPayload.level%3D%22debug%22%0ANOT%20jsonPayload.level%3D%22info%22%0AjsonPayload.level:%22%22%0AjsonPayload.component%3D%22crier%22&dateRangeStart=2020-05-18T16:15:19.313Z&scrollTimestamp=2020-05-18T17:05:34.000000000Z&dateRangeEnd=2020-05-18T17:15:19.313Z

**Comment by chizhg** [comment]
More observations for this issue:
It's because `gcsreporter` was throwing out errors when it uploads files to GCS. The error was in https://github.com/kubernetes/test-infra/blob/3bcd4aea5b0466ecac7cd1be2887b8a9ff237b7f/prow/crier/reporters/gcs/internal/util/util.go#L59-L69.

I have already found some issues with it but not the real culprit. Still digging.

**Comment by chizhg** [comment]
The error only happens if the crier Pod has been running for a relatively long time, like 2-3 days, and restarting the Pod will "fix" the issue. I started running a crontab which deletes the crier Pod every midnight, and since then we never met this issue.

We are now suspecting 3 possible causes, but haven't figured which one is the real culprit.
1. The GCS client is having some quota limit that we are unaware of
2. The token used by the GCS client can be expired after a certain amount of time
3. The crier Pod hit the resource limits (CPU or memory) after running a long time and the performance degraded

**Comment by alvaroaleman** [comment]
> This problem also blocks some of the PRs from reporting. Since it's known that restarting crier can temporarily alleviate the problem, rebooting crier to unblock them while investigating

Are you sure about that? Crier has retrying and I would assume this to be a transient error (but would still be interesting to find out why it happens).

**Comment by chizhg** [comment]
> > This problem also blocks some of the PRs from reporting. Since it's known that restarting crier can temporarily alleviate the problem, rebooting crier to unblock them while investigating
> 
> Are you sure about that? Crier has retrying and I would assume this to be a transient error (but would still be interesting to find out why it happens).

Yes, we are pretty sure about this phenomena.
We've seen quite a few times that the error happens after `crier` running for about 3 days. But after I started running a crontab that deletes `crier` Pod everyday two weeks ago, there is no such  `broken pipe` error anymore.

**Comment by chizhg** [comment]
I'm almost certain that the authentication process is different for a GCS client that is using a credential file vs not, see https://github.com/kubernetes/test-infra/blob/master/prow/io/opener.go#L117-L132, and using a credential file will cause this oauth error after a client has been run for a long time.

The only difference between us and k8s crier deployment is we are not using Workload Identity for the Prow cluster, so I think enable workload identity will fix this issue. If that's the case, it's probably not worth to try fixing the issue when using a credential file as workload identity is now the recommendation way to set authentication for the Google cloud services.

**Comment by chaodaiG** [comment]
Since workload identity is the direction to go, I would say let's go ahead and enable workload identity instead of wasting more time on this bug

**Comment by chizhg** [comment]
That's also what I thought, created https://github.com/knative/test-infra/issues/2235 for tracking.

Let's keep this bug open though until we can confirm enabling workload identity can solve this issue.

**Comment by chizhg** [comment]
We haven't seen such errors anymore after we enabled workload identity for the Prow cluster, so this issue should have been fixed.
