### ISSUE TITLE
Use peribolos to manage org settings, teams and memberships for Knative

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2091]
[peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos) is a tool developed by k8s sig-testing. By using it, the org settings, teams and memberships can be declared in a yaml file, and GitHub will be updated to match the declared configuration.

We can configure this tool for `knative` and `knative-sandbox`. The configuration files will be put under `knative/community`, and two postsubmit and periodic jobs will need to be added to read the configuration files and update Github, examples in https://github.com/kubernetes/test-infra/blob/d2c3ce758a3c06c30ad3ebfc4f0302f075128f71/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L3 and https://github.com/kubernetes/test-infra/blob/d2c3ce758a3c06c30ad3ebfc4f0302f075128f71/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L761

/assign

**Comment by evankanderson** [comment]
Dup of #148 

/close
