### ISSUE TITLE
Auto-push images

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#2103]
test-infra repo maintains several docker images under `images`, which are currently updated manually. This is error prone and sometimes are neglected, we should have a way of automatically uploading images

**Comment by chizhg** [comment]
With the CI beta tests added by @coryrc , we can potentially implement an image auto-promotion flow for rolling out the new image.

**Comment by coryrc** [comment]
CI Jobs in many repos are flaky or completely broken, so we wouldn't want Overall status to gate release of the new image.

**Comment by chaodaiG** [comment]
> CI Jobs in many repos are flaky or completely broken, so we wouldn't want Overall status to gate release of the new image.

For this process I'm not oppose the idea of "jailing", we could start with a few "stable" repos and slowly releasing repos out of "jail" if they proved to be good. This jailing process can be automated as well in my opinion
