### ISSUE TITLE
Separate prow job update job from others

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#2104]
Currently, once a PR containing prow jobs only changes, the config is updated right away by https://prow.knative.dev/?job=post-knative-prow-config-updater. This could be separated out of the process by simply updating prow job configs if the PR contains prow job changes

**Comment by chizhg** [comment]
FYI https://github.com/kubernetes/test-infra/tree/master/prow/plugins/updateconfig could be helpful here. It can even be configured on different repos.

**Comment by chaodaiG** [comment]
> FYI https://github.com/kubernetes/test-infra/tree/master/prow/plugins/updateconfig could be helpful here. It can even be configured on different repos.

Sweet!
