### ISSUE TITLE
We need a tool to bump go version across the repositories in knative org

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#2149]
I've been bumping everything manually which has turned out to be a pain.

I did the bump to 1.14 since so that there would be consistency with the go tooling & it's use of the vendor folder - ie. see https://golang.org/doc/go1.14#go-command

We'll want to bump the go version at some point in the future so some automation would be ideal

**Comment by chizhg** [comment]
We are aware of this issue, and I'm working on a long term solution in https://github.com/knative/test-infra/pull/2147, do you think it is an ideal approach?

**Comment by dprotaso** [comment]
oh my issue was more specifically bumping the version in the `go.mod` file

ie. eventually we'll want to go from 1.14 to 1.15

**Comment by chizhg** [comment]
My PR is specifically targeted on that 😄 

First, we are now use [gvm](https://github.com/moovweb/gvm) which allows us install multiple versions of Go in the test image.
Then after my PR is in, before each Prow job starts, the test driver script will parse the `go.mod` file and use `gvm` to switch to the version of Go specified in it.

So in the future when you submit a PR to change the Go version from 1.14 to 1.15, the infra will automatically choose 1.15 to run the presubmit tests for that PR.

**Comment by dprotaso** [comment]
yours compliments - i mean actually having tooling that will update the go.mod file

ie. automate something like

https://github.com/knative/eventing-contrib/pull/1287

**Comment by chizhg** [comment]
I see, sorry I misunderstood.

Technically we can implement a Prow job to do this. But one thing I'm not sure is the trigger of this job, e.g. how do we determine when is the time to bump up Go versions.
One way I can think of is polling the releases of golang in https://github.com/golang/go/releases and create PRs for Knative when there is a new release. But I'm not sure if there is any caveat for this approach.

cc @chaodaiG  for more thoughts.

**Comment by dprotaso** [comment]
manual triggering of the job would be fine - i don't think we need to poll for new golang releases

**Comment by chizhg** [comment]
I see. That's also what I thought initially, since we don't need it to be run quite often - IIRC Go only have a minor release every half year. I have modified the title to be more accurate and will check it when I get some time.

**Comment by pierDipi** [comment]
I have a tool to change the Go version in `go.mod` files, https://github.com/pierDipi/gobump.
I guess a GH action that uses that tool would work well for this, WDYT?

cc @n3wscott @mattmoor 

/assign
/remove-lifecycle stale
/lifecycle active

**Comment by mattmoor** [comment]
I could see this being a manually triggered workflow in `knative-sandbox/knobots`, wdyt?

**Comment by pierDipi** [comment]
SGTM.

**Comment by pierDipi** [comment]
The general desire is that each repository bumps the minimum go version when they need.

/close
