### ISSUE TITLE
Per partner contribution reporting

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#215]
The ask came up in today's productivity wg meeting. 
Need an automated way to generate such reporting and share with community.

**Comment by adrcunha** [comment]
devstats is able to provide this report, e.g., https://stats.knative.dev/d/4/companies-stats?orgId=1&from=1558980743967&to=1559326343967&var-period=d&var-metric=prs&var-repogroup_name=All&var-companies=All
