### ISSUE TITLE
enforce code coverage threshold by blocking PRs that does not comply

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#220]
Repos to enforce the rule:
knative/serving
knative/build

# sub-tasks
## knative/serving
https://github.com/knative/serving/issues/2347
https://testgrid.knative.dev/knative-serving#coverage
## knative/build
https://github.com/knative/build/issues/447
https://testgrid.knative.dev/knative-build#coverage

**Comment by steuhs** [comment]
@jessiezcc Any other repos we want to enforce the rule?

**Comment by jessiezcc** [comment]
@steuhs , can this issue be closed now?
