### ISSUE TITLE
package level coverage is missing in periodical runs

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#222]
## knative/serving
https://testgrid.knative.dev/knative-serving#coverage
## knative/build
https://testgrid.knative.dev/knative-build#coverage

**Comment by adrcunha** [comment]
Looks like this is obsolete? I see the "overall" line in both grids.

**Comment by steuhs** [comment]
@adrcunha Package level coverage means the coverage summary for each package, e.g. github.com/knative/serving/pkg/activator/handler/

**Comment by steuhs** [comment]
Fixed

**Comment by adrcunha** [comment]
Fixed in https://github.com/knative/test-infra/pull/286
