### ISSUE TITLE
Bug: release branch job generator reverts anchor

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#2297]
Auto release branch job generator is a tool generates release branch jobs when there is a new release branch created from any repo, the generated yaml is https://github.com/knative/test-infra/blob/master/config/prod/prow/config_knative.yaml. 

https://github.com/knative/test-infra/pull/2294 introduced anchor to `config_knative.yaml` file, which was expanded by auto release branch job generator and thus reverted all anchors. An example is here: https://github.com/knative/test-infra/pull/2295

The tool is located here: https://github.com/knative/test-infra/blob/master/tools/config-generator/udpaterelease.go

**Comment by chaodaiG** [comment]
The problem here is that release branch job generator uses yaml Unmarshal, which already expands anchor during unmarshalling. @mattmoor , any idea how to generate yaml with anchor?

**Comment by mattmoor** [comment]
there are yaml libraries that are better about roundtripping yaml (e.g. preserving comments), but if it's a ton of work it's probably worth just avoiding anchors/references.

**Comment by chaodaiG** [comment]
I have looked around, https://godoc.org/gopkg.in/yaml.v3 and https://github.com/goccy/go-yaml are both relevant. However, both require non trivial amount of work. Will leave this issue open and avoiding anchors for now
