### ISSUE TITLE
Spy glass shows the wrong logs with go 1.14 -v

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#2313]
![image](https://user-images.githubusercontent.com/2442466/87989697-5dc0a480-ca97-11ea-915b-047a0cdc19a4.png)

**Comment by chizhg** [comment]
This is a known issue, see https://github.com/knative/test-infra/issues/2109.
And it looks Golang released 1.14.6 on July 16th which included the fix - https://github.com/golang/go/issues/39308, I'll update the Golang version in our test image now which I believe will fix the issue 😃

**Comment by mattmoor** [comment]
thanks!
