### ISSUE TITLE
Knobots linter and prow linter don't agree with each other

### ISSUE THREAD

**Issue by vaikas** [knative/test-infra#2322]
https://github.com/knative/eventing/pull/3682/files
https://github.com/knative/eventing/pull/3668#issuecomment-661963247

@mattmoor @chizhg should be using the same linters in both places?

**Comment by chizhg** [comment]
I think this is also a check that is better to move to GitHub actions, there are quite a few existing ones we can use, e.g. https://github.com/marketplace/actions/markdown-link-check#:~:text=By%20default%20the%20github%2Daction,checks%20to%20only%20specific%20folders.&text=Specify%20how%20many%20levels%20deep,which%20means%20check%20all%20levels..

WDYT @chaodaiG ?

**Comment by chaodaiG** [comment]
> I think this is also a check that is better to move to GitHub actions, there are quite a few existing ones we can use, e.g. https://github.com/marketplace/actions/markdown-link-check#:~:text=By%20default%20the%20github%2Daction,checks%20to%20only%20specific%20folders.&text=Specify%20how%20many%20levels%20deep,which%20means%20check%20all%20levels..
> 
> WDYT @chaodaiG ?

github action sounds good to me, we can start with a canary repo first

**Comment by vaikas** [comment]
/remove-lifecycle stale
@chaodaiG I think this has been done now? If not, what's left?

**Comment by chizhg** [comment]
We have remove the linter functions from the test scripts, so we don't have this issue anymore.
