### ISSUE TITLE
Run knative tests and builds for other architectures

### ISSUE THREAD

**Issue by barthy1** [knative/test-infra#2337]
At this moment tests and releases for knative parts (serving, eventing, operator, client) are available only for amd64 (based on my knowledge)
Other architectures (s390x, ppc64le, arm64) usually require to run the tests and builds on the native hardware.
Suggestion is to add to knative CI/CD system the ways to run the tests and builds on corresponding native hardware.
My team (from IBM Z) can help with hardware, setup and run for s390x(IBM Z). Similar approach as we suggest will work for ppc64le (IBM Power).

At this moment we already started with internal builds and tests of knative repositories on s390x.
But we need input from knative community, which integration way will be appropriate and better fits to default knative practices. 
Experience from our side - Openshift CI on s390x, where Z hardware was provided via [sshd-bastion](https://github.com/openshift/release/tree/master/core-services/sshd-bastion), k8s Z clusters on this hardware were picked up by boskos and builds/tests were running via special Prow job. 

Repositories to cover(current understanding):
https://github.com/knative/serving
https://github.com/knative/eventing
https://github.com/knative/net-kourier
https://github.com/knative/client
https://github.com/knative/operator
https://github.com/knative/eventing-contrib
https://github.com/knative-sandbox/net-istio

**Comment by chizhg** [comment]
@BbolroC did some work for s390x. Is there anything else needed?

/remove-lifecycle frozen

**Comment by barthy1** [comment]
@BbolroC did great work. Now all main knative components have nightly tests for s390x. So I'd like to close this issue.
@chizhg thank you for reminder!
