### ISSUE TITLE
Prow config generator supports override `run_if_changed`

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#2343]
As discussed on Slack: https://knative.slack.com/archives/CCSNR4FCH/p1596842636408900, it's desired to allow certain presubmit job have `run_if_changed` field to be kicked off only when certain files changed, for example `third_party/foo_ingress` under serving repo, when there are changes it's required to pass `foo_ingress` related tests

**Comment by chaodaiG** [comment]
CC: @mattmoor 
CC: @chizhg

**Comment by mattmoor** [comment]
concretely, I want to start requiring the `pull-knative-serving-contour-latest ` job when `./third_party/contour-latest` changed.
