### ISSUE TITLE
EXISTING_CLUSTER still tears down the environment

### ISSUE THREAD

**Issue by vaikas-google** [knative/test-infra#235]
Setting the K8S_CLUSTER_OVERRIDE is not being honored.

vaikas@penguin:~/projects/go/src/github.com/knative/serving$ ./test/e2e-tests.sh --run-tests
- Cluster is gke_quantum-reducer-434_us-west1-knative-eventing-e2e
- User is vaikas@google.com
- Docker is us.gcr.io/quantum-reducer-434
Deleting any previous SUT instance
>> Removing test resources (test/config/)
>> Bringing down Serving
namespace "knative-serving" deleted
clusterrole.rbac.authorization.k8s.io "knative-serving-admin" deleted
clusterrole.rbac.authorization.k8s.io "knative-serving-write" deleted
serviceaccount "controller" deleted
serviceaccount "autoscaler" deleted
clusterrolebinding.rbac.authorization.k8s.io "knative-serving-controller-admin" deleted
clusterrolebinding.rbac.authorization.k8s.io "knative-serving-autoscaler-write" deleted
gateway.networking.istio.io "knative-shared-gateway" deleted
service "knative-ingressgateway" deleted
deployment.extensions "knative-ingressgateway" deleted

**Comment by adrcunha** [comment]
Setting `K8S_CLUSTER_OVERRIDE` means that a new test cluster won't be created for your test, not that we assume Knative is already installed and shouldn't be touched.

**Comment by mattmoor** [comment]
@vaikas-google IDK if eventing has weird setup requirements, but I always `go test -tags=e2e ./test/...`, which lets me use `-run=TestFoo` and `-count=N`.  FWIW

**Comment by adrcunha** [comment]
As I explained in #236, Ville should be able to run the tests against his existing cluster exactly like you pointed, Matt: by using `go test`.
