### ISSUE TITLE
We don't have a way to manually update the Prow job config for Knatve

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2411]
Currently the Prow job config is updated with a plugin and it's defined in https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/plugins.yaml#L75-L80. The plugin will update the Prow job config after a new change is submitted and merged in the knative/test-infra repo.

This process normally works pretty well, but sometimes e.g. when Prow has an outage due to misconfigured Prow jobs, we won't be able to merge a PR thus won't be able to trigger the plugin, so we will need a way to manually update the Prow job config. Currently there is not a way to do this in knative/test-infra repo.

cc @chaodaiG @peterfeifanchen

**Comment by chaodaiG** [comment]
+ @cjwagner and @fejta for ideas

**Comment by cjwagner** [comment]
> when Prow has an outage due to misconfigured Prow jobs, we won't be able to merge a PR thus won't be able to trigger the plugin

This kind of problem would typically be resolved by using the [`/override`](https://prow.knative.dev/command-help#override) plugin to allow Tide to ignore the misconfigured ProwJob or by manually merging the PR via the merge button. I'd recommend configuring that plugin if it hasn't been already.

Another option is the [`config-bootstrapper`](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/config-bootstrapper#config-bootstrapper) tool. This could be run locally if provided with an appropriate kubeconfig. It also consumes the `config_updater` section in plugin.yaml to match the behavior of the plugin.
