### ISSUE TITLE
go.mod `replace` usage impacts downstream consumers, impacted by circular dependency loop

### ISSUE THREAD

**Issue by howardjohn** [knative/test-infra#2414]
https://github.com/knative/networking/blob/master/go.mod#L32-L36

All knative repos use the following `replace` hacks to get k8s dependencies working. This means anyone importing a knative library *also* has to do these hacks, otherwise they will get incompatible k8s libraries (it will force a super old client-go version).

At some point in the past these were required for k8s imports, but its been fixed for some time now (for example - no `replaces` needed: https://github.com/istio/istio/blob/master/go.mod#L119-L124).

Here is the fun part - the dependency cannot easily be fixed because we have a circular import of knative/pkg -> knative/test-infra -> k8s/test-infra -> knative/pkg. This CAN be fixed, but as far as I can tell requires co-ordination between 5 different repos. I did this locally with:

Add this to all 5 repos go.mod (replace with your own paths)

```
replace knative.dev/pkg => /home/howardjohn/go/src/knative.dev/pkg
replace knative.dev/test-infra => /home/howardjohn/go/src/knative.dev/test-infra
replace k8s.io/test-infra => /home/howardjohn/go/src/k8s.io/test-infra
replace github.com/tektoncd/pipeline => /home/howardjohn/go/src/github.com/tektoncd/pipeline
replace sigs.k8s.io/boskos => /home/howardjohn/go/src/sigs.k8s.io/boskos
```

In reverse order from that list, update go.mod to remove replaces, run `go mod tidy`.

This could be done in real repos only with `replace` to temporary branches I think

**Comment by chizhg** [comment]
This is one thing I was worried about when I finished removing the circular dependencies between `knative/test-infra` and `knative/pkg` 😅 
@cjwagner it looks the only place that `knative.dev/pkg` is used in `k8s/test-infra` repo is the `prow/cmd/pipeline` package - https://github.com/kubernetes/test-infra/blob/master/prow/cmd/pipeline/controller.go#L52, any chance we can get rid of it?

**Comment by howardjohn** [comment]
@chizhg I think since github.com/tektoncd/pipeline is still widely used and imports `knative.dev/pkg` this wouldn't help too much. Unless go treats indirect vs direct dependency differently?

**Comment by n3wscott** [comment]
Interesting. Looking into it.

**Comment by slinkydeveloper** [comment]
I'm gonna try to fix https://github.com/kubernetes/test-infra/issues/19583 and let's see if this solves the issue

**Comment by chizhg** [comment]
@howardjohn we have got rid of the circular dependencies here, so you should be able to update your Knative dependencies to the latest to make your life easier.

**Comment by howardjohn** [comment]
I think this is fixed now, I will close unless there was more work. k8s/test-infra still has circular deps, but looks like its not knative's fault
