### ISSUE TITLE
Improve unit testing coverage for config generator from 12.9% to 80%

### ISSUE THREAD

**Issue by joshua-bone** [knative/test-infra#2419]
/assign

**Comment by chizhg** [comment]
Hmm is it for the current config generator? Since we have discussed completely rewriting it, is it worth to work on bumping up the unit test coverage for it? @chaodaiG

**Comment by chaodaiG** [comment]
We don't have a concrete plan of rewriting it yet, since it's been used so heavily atm, I think it still worths improving unit test coverages

**Comment by chizhg** [comment]
I see, that makes sense. It's a big chunk of work AFAICT though..
