### ISSUE TITLE
Check for cluster-admin-binding-${USER} in acquire_cluster_admin_role()

### ISSUE THREAD

**Issue by eric-sap** [knative/test-infra#2446]
The function acquire_cluster_admin_role() in scripts/infra-library.sh only checks to see if the cluster-admin-binding clusterrolebinding is present, but it can create one named cluster-admin-binding-${USER} when running on a local cluster.  This is never cleaned up and on running the setup_test_cluster() function again, it fails with the expected
```
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "cluster-admin-binding-myuser" already exists
```
I've worked around this in our (eventing-kafka) copy of the e2e-tests.sh script by simply deleting that clusterrolebinding before calling go_test_e2e() but it seems like this shouldn't be necessary.  I suspect this is just an oversight in acquire_cluster_admin_role() but I am hesitant to fix it myself as I'm not completely certain if it might have unintended other consequences.

**Comment by chizhg** [comment]
It's a typo, I have created https://github.com/knative/test-infra/pull/2450 to fix it.
Thanks for reporting!
