### ISSUE TITLE
Link checker fails on REAMDE.md when infra scripts have been imported to scripts/

### ISSUE THREAD

**Issue by rhuss** [knative/test-infra#2478]
See e.g. https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1010/pull-knative-client-build-tests/1313011377060712451 where the link check fails on its own scripts.

We have disabled link checking globally in the client repo for now but would be cool if we can fix it here.

**Comment by n3wscott** [comment]
We should not import test infra scripts to `./scripts`

**Comment by rhuss** [comment]
Are you sure that the check wouldn't fail if imported in `vendor/` since this is a relative link and I'm not sure that the target is picked up by go.mod resoluton as well.

**Comment by chizhg** [comment]
We have removed the markdown check logic from the test scripts in https://github.com/knative/test-infra/pull/2476, since we were planning to run it with GitHub Actions instead.

**Comment by rhuss** [comment]
cool, so lets close this issue then.
