### ISSUE TITLE
drop scripts/update-test-infra.sh

### ISSUE THREAD

**Issue by n3wscott** [knative/test-infra#2493]
No not use scripts/update-test-infra.sh, use go mod.

**Comment by coryrc** [comment]
Using go mod requires all downstream users match the exact libraries in test-infra, which is not intended.

See https://knative.slack.com/archives/CCSNR4FCH/p1601628568033700 how it is causing problems.

**Comment by chizhg** [comment]
Or we create a new `scripts` repo under knative, then there won't be problems using `go mod` to vendor these scripts.

**Comment by chizhg** [comment]
The script has been dropped after we moved the scripts to `knative.dev/hack`, so close this issue.
