### ISSUE TITLE
Generalize dump_app_logs()

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#252]
Move it to `library.sh` so all repos can benefit from it:

https://github.com/knative/build/pull/466#pullrequestreview-173628974

**Comment by ericKlawitter** [comment]
This is done via [test-infra commit](https://github.com/knative/test-infra/commit/cfcb8c3d5b2eb146c40e5d8a828520f240b35747) and [build commit](https://github.com/knative/build/commit/dc8cdea4502ef2f01770902db5f1b3e5df039a31).
