### ISSUE TITLE
retest command doesn't trigger failed github actions

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#2534]
can we hook this in - it seems like PR authors are not able to re-trigger failed github actions

**Comment by dprotaso** [comment]
cc @knative/productivity-wg-leads

**Comment by chizhg** [comment]
@dprotaso this actually needs to be supported by Prow, could you transfer the issue to k8s/test-infra repo and track it there?

**Comment by dprotaso** [comment]
upstream issue: https://github.com/kubernetes/test-infra/issues/21581

**Comment by dprotaso** [comment]
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1400/files

**Comment by chizhg** [comment]
This issue should have been fixed at https://github.com/kubernetes/test-infra/issues/21581 and https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1400 so close it.

/close
