### ISSUE TITLE
Enable cherry picker plugin

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#2536]
Can we enable this plugin to make it easier to cherry pick changes

https://github.com/kubernetes/test-infra/blob/master/prow/external-plugins/cherrypicker/README.md

**Comment by mattmoor** [comment]
cc @abrennan89 @n3wscott

**Comment by chizhg** [comment]
The cherrypicker plugin has been enabled,  now you can comment `/cherrypick release-x.x.x` on a merged PR to cherrypick it into other branches, or if you want to use GitHub label, you can  add the label like `cherrypick/x.x.x` on the PR.

See https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker for more details.

**Comment by mattmoor** [comment]
I'm testing this here: https://github.com/knative/docs/pull/3071#issuecomment-736662413

I don't see this working.  Is there a way to check status?
