### ISSUE TITLE
Run presubmit check for branch protector

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2559]
We have configured `branch-protector` Prow jobs for Knative to automatically configure branch protection rules for Knative repositories - https://github.com/knative/test-infra/tree/master/config/branch_protector, but the presubmit check (which has `--confirm=false`) is taking nearly 1 hour to finish, so we are disabling it in https://github.com/knative/test-infra/pull/2555.

We should make the presubmit check more lightweight (potentially we need some improvements for the `branch-protector` tool) and reenable it.

**Comment by chizhg** [comment]
This can be easily fixed after https://github.com/knative/test-infra/issues/2962 is done.

**Comment by kvmware** [comment]
https://github.com/knative/test-infra/blob/6d572240f416188df3153f4522d101361ba0f997/prow/jobs/custom/branchprotector.yaml#L54 shows `confirm` option is enabled
