### ISSUE TITLE
No way to retry a release if the artifact upload fails for GitHub.

### ISSUE THREAD

**Issue by n3wscott** [knative/test-infra#2566]
The current auto-releaser script will not run if the label exists for a release, we had a GitHub issue were the artifacts could not be attached to the release (they failed to upload from an outage) and a few of our 0.19  releases got created, labeled, but no yaml. But because the label exists, the job is a no-op. No way to recover from this. 

A failed job log: https://console.cloud.google.com/storage/browser/_details/knative-prow/logs/ci-knative-sandbox-eventing-natss-auto-release/1326314413245861888/build-log.txt

We manually fixed it by:

- ko resolve -f ./config > eventing-natss.yaml
- Updated the `devel` labels to `v0.19.0`
- Replace my digests with those that are found in https://console.cloud.google.com/storage/browser/_details/knative-prow/logs/ci-knative-sandbox-eventing-natss-auto-release/1326314413245861888/build-log.txt
- Uploaded this file to github on the release.

It would be nice to be able to have the artifact also uploaded to prow/gcr. Or the ability to rerun this job.

**Comment by chizhg** [comment]
https://github.com/knative/test-infra/issues/1782 is the umbrella that includes all the issues I observed on the current release scripts, which also includes this issue.
