### ISSUE TITLE
`buoy float` can't handle `master`

### ISSUE THREAD

**Issue by aliok** [knative/test-infra#2591]
For example, I am getting this when I do `./hack/update-deps.sh --upgrade` in `eventing-kafka`:
```
Error: Invalid character(s) found in major number "0master"
Usage:
  buoy float go.mod [flags]
Flags:
  -d, --domain string    domain filter (i.e. knative.dev) [required] (default "knative.dev")
  -h, --help             help for float
  -r, --release string   release should be '<major>.<minor>' (i.e.: 1.23 or v1.23) [required]
      --ruleset string   The ruleset to evaluate the dependency refs. Rulesets: [Any, ReleaseOrBranch, Release, Branch] (default "Any")
2020/11/26 15:16:07 Error during command execution: Invalid character(s) found in major number "0master"
```
Isolated it to this command that's run in this script:
```
buoy float /home/aliok/go/src/github.com/knative-sandbox/eventing-kafka/go.mod --release master --domain knative.dev
```

The automated updates work fine though: https://github.com/knative-sandbox/knobots/runs/1456593886?check_suite_focus=true

When I inspect it, I see `buoy` is executed with `0.20` and not `master` in this line: https://github.com/knative-sandbox/knobots/runs/1456593886?check_suite_focus=true#step:6:16

So, my problem here is, how do I use the new code in `knative.dev/hack` master in eventing-kafka master? Can't run `./hack/update-deps.sh --upgrade` locally and the Githib action is only updating to 0.20.

**Comment by n3wscott** [comment]
Working as intended. "master" is not a release.
