### ISSUE TITLE
ClusterManager has a lot of master* configs.

### ISSUE THREAD

**Issue by n3wscott** [knative/test-infra#2634]
Move to not hardcode the HEAD branch of any repo. This is an effort to support inclusive naming and eliminate the usage of a `master` branch.

See https://github.com/knative/community/issues/293﻿

**Comment by nak3** [comment]
This is really necessary. If we create the new repo now, `main` is the default branch and prow fails :cry:  
[net-ingressv2](https://github.com/knative/community/issues/389) is failing as https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-sandbox-net-ingressv2-nightly-release/1352547498790490112.
