### ISSUE TITLE
Move prow to pod-utils

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#265]
The knative prow config uses bootstrap.py utility to set up prow jobs. This has been deprecated for a while and we should be moving to pod utilities to define our prow jobs

**Comment by adrcunha** [comment]
I had a quick discussion about this with the k8s folks due to #249. pod-utils is still missing some features (eg timestamps) so I we shouldn't upgrade now.

**Comment by adrcunha** [comment]
I already did that for one job, just follow the code coverage example and use `runner.sh` as entry point.

**Comment by jessiezcc** [comment]
Triaged, not a high priority, will re-evaluate in Q2

**Comment by adrcunha** [comment]
Chao, please validate this approach before doing a full change. Manually change one job and use run_job.sh, so you can check that everything is working as intended. I hope https://github.com/knative/test-infra/issues/265#issuecomment-440338316 is obsolete now.

**Comment by chaodaiG** [comment]
@adrcunha unfortunately https://github.com/knative/test-infra/issues/265#issuecomment-440338316 is not obsolete yet, just synced with k8s folks, the timestamp feature is still missing from podutil, see this discussion

But for migrating sample-controller to knative.dev/sample-controller in this PR https://github.com/knative/sample-controller/pull/24 and more along the line, we still need to move forward with podutil
