### ISSUE TITLE
Warning about not using ghproxy during peribolos run

### ISSUE THREAD

**Issue by vaikas** [knative/test-infra#2650]
While working on this PR:
https://github.com/knative/community/pull/430

Looked at the peribolos logs here:
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_community/430/pull-knative-peribolos/1356898274002341888

I saw this:

```
{"component":"unset","file":"prow/flagutil/github.go:75","func":"k8s.io/test-infra/prow/flagutil.(*GitHubOptions).Validate","level":"warning","msg":"It doesn't look like you are using ghproxy to cache API calls to GitHub! This has become a required component of Prow and other components will soon be allowed to add features that may rapidly consume API ratelimit without caching. Starting May 1, 2020 use Prow components without ghproxy at your own risk! https://github.com/kubernetes/test-infra/tree/master/ghproxy#ghproxy","severity":"warning","time":"2021-02-03T09:32:19Z"}
```

**Comment by chizhg** [comment]
We are using a dedicated GitHub oauth token for peribolos Prow jobs, which is different from the one used by other jobs. In this case ghproxy is not useful anymore since its main purpose is for rate limiting the requests sent with the same token.
