### ISSUE TITLE
Send a notice for post-submit peribolos failures.

### ISSUE THREAD

**Issue by vaikas** [knative/test-infra#2662]
As discussed in #2653 we should send failure notices from the post-submit prow job. This is a feature request for it.
@n3wscott @chizhg

**Comment by vaikas** [comment]
#2652 this one addresses the post-submit, where as #2653 addressed the more comprehensive pre-submit phase.

**Comment by chizhg** [comment]
I can help with it. Which channel do you want the failure notices to be sent to?
