### ISSUE TITLE
Ship Maven and JDK in prow runner 

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/test-infra#2726]
In eventing-kafka-broker today we have to run maven in docker to build, test, etc. This makes our scripts more (and unnecessary) complex. It would be nice if the prow runner could just ship maven and a jdk to run our builds.

It would be nice to have the jdk version configurable (maven version doesn't really matter, last one is always fine), but if it's too hard, it's not a big deal and you can just default to openjdk 15 (the one we use in eventing-kafka-broker) 

Both maven and jdk setup can be easily automatized using https://sdkman.io/

**Comment by slinkydeveloper** [comment]
cc @chaodaiG any ideas about this one?

**Comment by chizhg** [comment]
You can add them in https://github.com/knative/test-infra/blob/main/images/prow-tests/Dockerfile.
