### ISSUE TITLE
Setup Prow build cluster for external secrets

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2748]
https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md#set-up-prow-maintainers

To use for s390x jobs.

/assign @chaodaiG 
/cc @chaodaiG 
/cc @barthy1

**Comment by chaodaiG** [comment]
Enabled via https://github.com/GoogleCloudPlatform/oss-test-infra/pull/807, verified that the service is running in knative build cluster. For instructions on how to use see https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md

/close
