### ISSUE TITLE
Switch knative-sandbox back to OWNERS and self-approval

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#2751]
After surveying the knative-dev mailing list, 68% of respondents preferred to bring self-approval back to knative-sandbox.

An important clarification: **Self-approval does not allow merging code that has not been reviewed.** At least one reviewer who is not the PR creator must review and `/lgtm` a PR before it can merge. This will still be true if self-approval returns.

Unfortunately, (AFAIK) GitHub CODEOWNERS approval does not allow the above: only code owners can approve a PR and there is no separate concept of approve and lgtm as with Prow approval.

So to bring back self-approval AND ensure that all merged PRs are reviewed, we'll need to switch knative-sandbox back to using OWNERS and Prow approval as before.

**Comment by rhuss** [comment]
Some background info: Here's an old open issue for GitHub to allow self-approval, but it looks like there is no movement in that area anymore: https://github.community/t/do-not-require-owner-approval-if-the-pull-request-is-from-an-owner/369

There seems to be a way to tweak the approval algo via bots like in https://docs.pullapprove.com/config/reviews/#author_value the question would be, whether we want to leverage that to get kind of a self-approval behaviour as we know it back.

**Comment by evankanderson** [comment]
As you might gather, the `gh` tool is helping managing these operations, which aren't quite simple enough to automate (yet?)

**Comment by rhuss** [comment]
@evankanderson please let me know when it is time to roll back that 'technical user' hack in the team assignments that was introduced to reduce notification spam.

**Comment by evankanderson** [comment]
Unnecessary PRs:
* https://github.com/knative-sandbox/kn-plugin-source-pkg/pull/3 -- that repo is empty.
* https://github.com/knative-sandbox/actions-kind/pull/1 -- also empty
* https://github.com/knative-sandbox/build-spike/pull/4 -- empty, probably also defun(k)t
* 
Dave is looking at https://github.com/knative-sandbox/wg-repository/pull/1 and https://github.com/knative-sandbox/integration/pull/4
I'll need someone from eventing for https://github.com/knative-sandbox/eventing-kafka/pull/574

**Comment by evankanderson** [comment]
/reopen

I still need to remove CODEOWNERS

**Comment by evankanderson** [comment]
/close

The CODEOWNERS files shouldn't do any harm, but shouldn't be needed, either.
