### ISSUE TITLE
Switch knative back to self-approval

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#2752]
After surveying the knative-dev mailing list, 53% of respondents preferred to bring self-approval back to knative. See #2751 for the equivalent knative-sandbox issue.

An important clarification: **Self-approval does not allow merging code that has not been reviewed.** At least one reviewer who is not the PR creator must review and /lgtm a PR before it can merge. This will still be true if self-approval returns.

Since knative is still using OWNERS and Prow for approval, the work here is less urgent and simpler than in #2751: less urgent because approvers can already manually self-approve by adding `/approve` to their PR description, and simpler because all we need to do is update the prow plugins config to `require_self_approval: false`.

**Comment by evankanderson** [comment]
/close

(Apparently "Fixes ..." doesn't work from a different org.)
