### ISSUE TITLE
Use external secrets manager for s390x cluster secret

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2760]
https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md#usage-prow-clients

Now that #2748 is complete, you can follow the above instructions to create a secret in your own GCP project.

For step 3: `Create kubernetes external secrets custom resource by`, put it in https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/knative/cluster/build
We wrote a little more [here](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/knative#prow-secrets).

/assign @barthy1

**Comment by barthy1** [comment]
The connected issue https://github.com/knative/test-infra/issues/2775

**Comment by BbolroC** [comment]
The secret is installed and working.
