### ISSUE TITLE
Prow-tests image documentation is outdated/wrong, image doesn't become beta?

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#2765]
https://github.com/knative/test-infra/tree/main/images/prow-tests

It appears the image gets pushed by a job automatically? If so, the `make cloud_build` stuff should be moved out to a separate section. Please also include what job does this and how to get its status.

When is the oncall supposed to tag the image? I think the build process should automatically tag them `:beta`.

/assign @chizhg

**Comment by albertomilan** [comment]
We did some manual alterations on the labels. Verify the expected functionality does happen automatically in ongoing image generations before applying any change to the configuration.
