### ISSUE TITLE
cherry-pick plugin not up to date?

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#2769]
Multiple commands were fixed here https://github.com/kubernetes/test-infra/issues/21714

but it didn't pick it up here:
https://github.com/knative/serving/pull/11298#issuecomment-832392366

it's also unclear why evan's comment didn't produce the necessary cherry picks

https://github.com/knative/serving/pull/11298#pullrequestreview-651753871

**Comment by nak3** [comment]
I hit this issue before and realized that one `/cherry-pick xxx` needs to be in one comment :sweat: It seems multiple `/cherrry-pick` lines are not supported.

**Comment by chizhg** [comment]
From https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/cluster/500-cherrypicker.yaml#L36 it's already using the latest version though.

**Comment by dprotaso** [comment]
Cool - I'll reopen if I see it again

**Comment by dprotaso** [comment]
This comment didn't trigger three PRs as expected  - I had to do separate comments

https://github.com/knative/serving/pull/12614#issuecomment-1038228717

**Comment by dprotaso** [comment]
Another - https://github.com/knative/serving/pull/12617#issuecomment-1038232043
