### ISSUE TITLE
verify-codegen.sh should check /vendor

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#281]
https://github.com/knative/serving/pull/2561 should be replicated to all repos.

/assign chaodaiG

**Comment by adrcunha** [comment]
@chaodaiG are all yours PRs merged?

**Comment by chaodaiG** [comment]
There are still 2 open waiting for approval:
https://github.com/knative/eventing-sources/pull/133
https://github.com/knative/caching/pull/17

**Comment by chaodaiG** [comment]
update: @adrcunha , now all PRs are merged

**Comment by adrcunha** [comment]
Awesome, thanks!
