### ISSUE TITLE
Protected dependabot branches

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/test-infra#2816]
In eventing-kafka-broker we use dependabot to update our Java dependencies. Every dependabot PR creates a branch in our repo: https://github.com/knative-sandbox/eventing-kafka-broker/branches

For some reason, dependabot branches becomes protected, which prevents us from:

* Cleaning up all these branches when PRs are merged
* Use the rebase dependabot command
* Using the GH action that updates the THIRD-PARTY.txt file https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/.github/workflows/build-dependabot-pr.yaml

**Comment by chizhg** [comment]
It looks it can be configured like https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L148-L151 to exclude certain branches to be protected. Feel free to submit a PR for it.

**Comment by dprotaso** [comment]
Should we change the config to just include `main` and `release-*` branches only?

There's usually some persons stray branch that would be nice to clean up without having admin access

**Comment by chizhg** [comment]
That also sounds more ideal to me but it looks `branchprotector` does not support `include` syntax in its config, but I could be wrong.
Feel free to open an issue under https://github.com/kubernetes/test-infra/issues to ask if that's a case or if it's a reasonable feature request.

**Comment by dprotaso** [comment]
made an upstream issue

https://github.com/kubernetes/test-infra/issues/22657
