### ISSUE TITLE
Knative gubernator is showing merged PR as Needs Attention

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#283]
A new deployment may fix it. 

https://github.com/knative/test-infra/tree/master/ci/gubernator
make deploy

**Comment by jessiezcc** [comment]
new deployment doesn't help, the current workaround is to add a random comment to merged PR, then it will be gone from Gubernator page. 
It happens when github fails to send the event, gubernator won't update the state. Adding a comment will trigger a new event.

**Comment by adrcunha** [comment]
This should be filed against kubernetes, as it's an issue with gubernator.

**Comment by adrcunha** [comment]
Closing this as the issue was opened in the kubernetes/test-infra repo.
