### ISSUE TITLE
Allow knative-release-leads team to run jobs using the Prow UI

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#2832]
We have a [rotation of leads](https://github.com/knative/release) that shepherd a Knative release. There's a corresponding GitHub team `knative-release-leads` in the `knative` org that is used for this process.

Members of this team currently don't have the ability to run Prow jobs via the UI. We should grant this team the same access as the milestone maintainers.

https://github.com/knative/test-infra/blob/5273590479dfaa642f6a37e6dbb0bcb182047847/guides/manual_release.md#option-1-via-prow-ui

**Comment by dprotaso** [comment]
@chizhg @chaodaiG is this an easy config change?

**Comment by chaodaiG** [comment]
It can be configured here: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/84080b48e72981f92fcd95184ac737f00ccaded8/prow/knative/config.yaml#L124

**Comment by dprotaso** [comment]
eek. `github_team_ids` - there's not reference by name?

**Comment by dprotaso** [comment]
in case the team is re-created for whatever reason

**Comment by chaodaiG** [comment]
Not afaict, feel free file a bug under https://github.com/kubernetes/test-infra

**Comment by dprotaso** [comment]
Made the PR here: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/937
