### ISSUE TITLE
repo:write allows new branches to be created on non-forked repos

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#2929]
Sometimes people push new branches to repos instead of their forks. With branch protection on one cannot easily delete those branches (would have to disable protection which is dangerous). When https://github.com/knative/test-infra/issues/2859 is solved that should allow us to delete branches that are not explicitly in the `include` rules. However, the larger problem of github UI allowing branches to be created still is a problem. This should not be allowed.

**Comment by chizhg** [comment]
@kvmware is this issue fixed now?

**Comment by kvmware** [comment]
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1236 fixes this
