### ISSUE TITLE
Knative bots hosting

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#294]
Knative contributors have started to produce bots for various purposes, and they are quite beneficial to be run against Knative repos themselves. 
We need a process where contributors can graduate their bots to be run against Knative repos (at which point, we'd probably have a Knative bots repo). And of course need a Knative environment where these bots can be hosted. This also serves great dogfood purposes (Knative bots running on top of Knative and work against Knative repos)

**Comment by adrcunha** [comment]
Nikhil left the team, parking this issue on me.
/assign adrcunha
/unassign nbarthwal
/label TBD

**Comment by adrcunha** [comment]
This is now captured in the high level design doc for the next version of the test infrastructure -- https://docs.google.com/document/d/1QHPks3oRKccTpzAOJuU2tgHjyiA0Somm7PwdQVupyk0/edit -- feedback is welcome.

Closing this issue, as new work/tasks should be in a separate issue.
