### ISSUE TITLE
Understand the relationship between the different repos

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/test-infra#2946]
**Problem**
Its difficult for new contributors to understand the relationship between the different repos in the `knative` and `knative-sandbox` orgs. 
This was raised at the New Contributor Retro ([Reference](https://docs.google.com/presentation/d/1janQbHA3NQ_DtYBre8FETMmN4O7-sOfpjoarreCzzKw/edit#slide=id.g1014d5d8257_0_26))

**Persona**
Which persona is this feature for?
Contributors

**Exit Criteria**
Basic: A visual way of understanding the relationship between repos.
Next Level: Surfacing this in every repo

**Comment by xtreme-sameer-vohra** [comment]
cc @kvmware 
@evankanderson you mentioned that there might be some tools that could be leveraged

A google search revealed https://github.com/Helcaraxan/gomod which looks promising

**Comment by kvmware** [comment]
https://docs.google.com/document/d/1mFY2QdXUvhCORyVkhJtBOqWeYGOIxmJ-ltSPXWZRU3E/edit?usp=sharing a proposal has been submitted to the DUX working group meeting. Please add comments or suggestions there.
