### ISSUE TITLE
Move all GCP projects used for Knative infra from google.com to knative.team org

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2976]
As part of CNCF infra migration, we need to move all GCP projects used for Knative infra from google.com to knative.team org, so that they can be accessed and managed by Knative community members.

These projects include:
- knative-tests
- knative-boskos-01…100
- knative-nightly, knative-releases
- knative-gcp, knative-nightly
- knative-performance, knative-eventing-performance
- knative-e2e-dns, knative-serving-e2e-tests

More details can be found in the [Knative test infrastructure 1.0](https://docs.google.com/document/d/1U6wybYjCslEhsKOiennrwhoKZmSVnd1NGbFI8gnnnOg/edit#) doc

**Comment by upodroid** [comment]
This is what we need to do.

1. Configure Google Cloud properly for knative.team https://cloud.google.com/resource-manager/docs/creating-managing-organization
2. Move the projects to knative.team GCP Org
3. Once the project is accepted in CNCF, update the billing in Google Workspace and Google Cloud. We'll need to log support cases with Google to update ownership and billing for both products.

**Comment by upodroid** [comment]
The organization is configured now.

```
cy@cloudshell:~$ gcloud organizations list --format yaml
---
creationTime: '2020-12-17T06:05:30.349Z'
displayName: knative.team
lifecycleState: ACTIVE
name: organizations/22054930418
owner:
  directoryCustomerId: C03vqxd4z
cy@cloudshell:~$
```

**Comment by chizhg** [comment]
@upodroid I checked with Ihor Dvoretskyi from CNCF regarding whether they are okay for us to create the GCP org, but below is what he said:
```
We had some issues in the past with the ownership transfer for other projects (potentially caused by Cloud Identity). 
I don’t want to say that this kind of transfer is technically impossible, but I’d always prefer to start from scratch.
```

I'm not sure what the issues he meant here since I've never done this before, but it sounds there are certain risks for using this GCP org rather than waiting for CNCF to create it for us.

**Comment by upodroid** [comment]
Transferring projects between organizations has been streamlined by Google last year. You had to engage Google Support and took time but it is self service now.

The GCP org is tied to the GSuite organization. Ihor is effectively proposing we scrap our current gsuite and start with a fresh gsuite + gcp org which is extremely painful to deal with.

Lets arrange a meeting with the CNCF rep, GCP/GSuite sellers and us and then work it out properly.

**Comment by upodroid** [comment]
Also, CNCF needs to take ownership and billing responsibility for `knative.team` GSuite Subscription. It is currently paid by a Googler with their corporate card. I'll log a separate issue for that.

**Comment by chizhg** [comment]
I have successfully move all these GCP projects to the `knative.team/infra` folder, and I haven't observed any issues so far. I'll mark this issue as fixed, and we can track the following automation work with other issues.
