### ISSUE TITLE
Move Knative Prow config files from GoogleCloudPlatform/oss-test-infra repo to the knative/test-infra repo

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2982]
As the outcome of [Proposal: Reducing Productivity Oncall Duties](https://docs.google.com/document/d/1tktwX9qHR9DKiA6yZCEMRYouNtScyRVW4ztVea-MJ1M/edit?resourcekey=0-G8IkKBaNP2s7xc2j92nvAQ#), Knative Prow config files were moved from GoogleCloudPlatform/oss-test-infra repo to the knative/test-infra repo, which are managed and maintained by the Prow team at Google.

Now that Knative has been donated to CNCF, we'd want to move the Knative Prow to be community-managed. This issue is for tracking the effort on moving the Prow config files back to the knative/test-infra repo and configuring autobump.

The steps will be:
1. Move everything from https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/knative, which includes Prow deployment config files and some other script files.
2. Move the autobump Prow job from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml#L167-L239, which is for automatically creating PRs to bump the image versions for Prow.
> Note there is also an autobump Prow job in the knative/test-infra repo (https://github.com/knative/test-infra/blob/main/config/prod/prow/knative-autobump-config.yaml), so we may consider combining them.
3. Move the postsubmit Prow job from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml#L26-L58 to auto-deploy Prow.

More details can be found in the [Knative test infrastructure 1.0](https://docs.google.com/document/d/1U6wybYjCslEhsKOiennrwhoKZmSVnd1NGbFI8gnnnOg/edit#) doc

**Comment by chizhg** [comment]
On a side note for this issue, @upodroid is working on https://github.com/knative/community/issues/443 to automate management of GCP resources, and likely we'll want all these config files to be in the same repo.

@upodroid is your plan to have the k8s tools in the test-infra repo?

**Comment by upodroid** [comment]
1. https://github.com/kubernetes/k8s.io/tree/master/groups will live at https://github.com/knative/community/tree/main/groups
2. https://github.com/kubernetes/k8s.io/tree/main/infra/gcp will live at https://github.com/knative/test-infra/tree/main/infra/gcp

**Comment by chizhg** [comment]
Step 3 cannot be done at this point since the Prow team is stilling managing the Knative Prow instance. We'll do it after Knative is officially accepted by CNCF and the process is completely removed from oss-test-infra repo. So keeping this issue open for now for better tracking purpose.

**Comment by kvmware** [comment]
Created an issue #3101 to track step 3
