### ISSUE TITLE
Move Knative TestGrid config files from GoogleCloudPlatform/testgrid repo to the knative/test-infra repo

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#2983]
Similar to the Prow config files migration issue at https://github.com/knative/test-infra/issues/2982, this issue is for tracking the work to move the Knative TestGrid backend deployment config files from [GoogleCloudPlatform/testgrid](https://github.com/GoogleCloudPlatform/testgrid/tree/master/cluster/prod/knative) to the knative/test-infra repo

More details can be found in the [Knative test infrastructure 1.0](https://docs.google.com/document/d/1U6wybYjCslEhsKOiennrwhoKZmSVnd1NGbFI8gnnnOg/edit#) doc

**Comment by chizhg** [comment]
Below are the resource usage history for the TestGrid `summarizer` and `updater` component:  

![image](https://user-images.githubusercontent.com/19399934/158266517-2221fbd9-7313-42e8-b5ef-cf18e87c0c77.png)

![image](https://user-images.githubusercontent.com/19399934/158266545-c926d46e-a915-4138-8664-1aa64001d867.png)

Both of them are pretty low so should not add much additional cost once they are migrated over. One caveat to keep in mind though is it's processing the artifacts stored in GCS that are produced by Prow jobs, so the resource usage will grow as more and more Prow jobs are being added.

**Comment by kvmware** [comment]
Google is fine hosting this for us (Knative) for the meantime as it is very low resource use and the backend and frontend need to be in sync and would break often if we hosted ourselves. We should check back with them on a yearly basis just to confirm if they are still fine hosting it though.
