### ISSUE TITLE
Turn on the ability for /retest to re-run failed GitHub Actions

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#2992]
This landed upstream thanks to @shinigambit 

cc @kvmware @chizhg 

https://github.com/kubernetes/test-infra/issues/21581

**Comment by chizhg** [comment]
It looks Fabian is looking into it, so assigning to him.

**Comment by shinigambit** [comment]
Forgot to link the PR to this issue, the configuration should be taking effect already. Feel free to close the issue if it's working as expected
