### ISSUE TITLE
Utilize the new reusable workflows

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#2994]
Currently we copy the workflows across repos. This not needed anymore with the new reusable workflow feature.

Knative repo for hosting GitHub Actions workflows (also a sandbox one. Verify if we can ref workflows across orgs. If so, we don't need both.)
https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/
https://github.com/knative/.github
https://github.com/knative-sandbox/.github

**Comment by shinigambit** [comment]
To reference reusable workflows we still need to copy (via knobots) or create manually the yaml file that points to the reusable workflows, currently I'm copying the reusable bits to [knative-sandbox/.github/.github/workflows](https://github.com/knative-sandbox/.github/tree/main/.github/workflows) and modifying the templates defined in [knative-sandbox/.github/workflow-templates](https://github.com/knative-sandbox/.github/tree/main/workflow-templates) to just point to the reusable files, that way knobots should take care of copying the "empty" templates to the appropriate repos. @chizhg @kvmware please let me know if you have any comments about this approach

**Comment by kvmware** [comment]
Sounds like we won't be able to escape using knobots. However, with reusable workflows we will make the use of knobots much less frequent since only rename and add/removal of jobs would need to be synced. We do get the win of when making changes to jobs would not need knobots and thus the many different repos would not have to have PRs spammed to them :+1:

**Comment by chizhg** [comment]
The plan sounds good to me, and +1 to Krsna's comment.

One open question I have after reading https://docs.github.com/en/actions/using-workflows/reusing-workflows#reusable-workflows-and-starter-workflows is, do we want to specify the different release branch name when referencing the reusable workflow, or shall we always use `main`? If the former, we'll need to start cutting release for the `.github` repos and will need to update the workflow templates every time when a release is cut. If the latter, we'll need to keep backward compatibility for every change made to the reusable workflows. This'll need a bit more thoughts and evaluations.

cc @dprotaso any thoughts on this?

**Comment by chizhg** [comment]
@shinigambit @dprotaso @kvmware is there anything left for this issue? Shall we mark this issue as resolved now?
