### ISSUE TITLE
Publish breakdown of GCP Infra used by knative test-infra

### ISSUE THREAD

**Issue by upodroid** [knative/test-infra#3003]
@chizhg 

Can you supply the following screenshots from billing?

![image](https://user-images.githubusercontent.com/25100905/149372859-e0e1dd99-5d72-4700-b731-f2dea0eef0e2.png)

I suspect it may not be possible, but access to the billing exports would be cool or a copy of the report @evankanderson wrote.

The usual suspects that we can optimise are the following:
- using preemptible nodes
- eliminate logging
- eliminate metrics
- right sizing nodes for specific tests.

/label kind/cncf-infra

**Comment by chizhg** [comment]
FYI https://docs.google.com/spreadsheets/d/1UhN-2KixU_q_G7Bp87LczShHA0Ms-MAroxjdvyQAlL0/edit#gid=0 is the cost sheet created by Evan.

**Comment by chizhg** [comment]
And below is the new billing screenshot for November 2021:

![image](https://user-images.githubusercontent.com/19399934/149377058-5f1932dd-6934-4dc9-8e5a-a08fb79d130e.png)

**Comment by upodroid** [comment]
Can you break it down by SKU?

**Comment by evankanderson** [comment]
Can this be closed?

**Comment by chizhg** [comment]
Yes, this can be closed - we have already done all the work that we identified to reduce the cost.
