### ISSUE TITLE
Introduce Robust Image testing pipeline

### ISSUE THREAD

**Issue by upodroid** [knative/test-infra#3017]
We have been updating the prow-tests image recently and a few bugs snuck through including a critical one such as #3015

#3008 introduced a presubmit job that builds the image and verifies successful build but the image isn't tested properly with a prowjob.

We should extend #3008 to run a local Prow Job. k8s infra repo has instructions at https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md#running-a-prowjob-locally

**Comment by upodroid** [comment]
@chi

**Comment by chizhg** [comment]
/reopen

Opening it for visibility. We may still need to introduce some presubmit testing in the future to make it more robust.

**Comment by upodroid** [comment]
This has been fixed.
