### ISSUE TITLE
Update the git version in the prow-tests image

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#3027]
The `post-knative-test-infra-prow-tests-image-push` Prow job is now failing, and it seems to be still due to the old git version https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-test-infra-prow-tests-image-push/1483865568942493696#1:build-log.txt%3A5

/cc @upodroid

**Comment by upodroid** [comment]
git version is already updated in the new image, have we rolled it out yet?

**Comment by chizhg** [comment]
My bad, I forgot about that.. I was monitoring on the beta (staging) Prow jobs, and found one error, https://github.com/knative/test-infra/pull/3028 is the fix.

**Comment by upodroid** [comment]
On a sidenote, pull-knative-test-infra-prow-tests-image-build should be failing properly

**Comment by chizhg** [comment]
That should be okay I think. We only need to make sure it's on the main branch when pushing the images.

**Comment by chizhg** [comment]
The issue was fixed after rolling out the new image.
