### ISSUE TITLE
Create an oncall rotation for Knative infra

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#3029]
After the infra is migrated to CNCF (basically everything in https://github.com/orgs/knative/projects/40/views/11 is done), we should create an oncall rotation for maintaining the infra.

We can hash out more details about the responsibilities, but ideally the oncall should only be responsible for handling the infra issues, including Prow, TestGrid, Boskos, etc, all other productivity related issues should be directed to the Slack channels instead of directly pinging the oncall.

/cc @kvmware

**Comment by kvmware** [comment]
Currently blocked by lack of contributors. Work can be done on this with respect to documentation, process, etc.
