### ISSUE TITLE
Migrate to Containerd node images before GKE v1.24

### ISSUE THREAD

**Issue by upodroid** [knative/test-infra#3036]
We will need to recreate the nodepools of the permanent GKE Clusters that we run.

![image](https://user-images.githubusercontent.com/25100905/150993539-302bbb64-6022-4628-8909-fba3cd3e263e.png)

https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/

/kind cncf-infra

**Comment by chizhg** [comment]
You are so fast! I was just about to bring this up 😄 

The GKE clusters created for the E2E tests are also using legacy `cos` node image, and it should be an easy fix - we can just pass the `--image-type` flag to the `kubetest2 gke` command - https://github.com/kubernetes-sigs/kubetest2/blob/master/kubetest2-gke/deployer/options/cluster.go#L36
