### ISSUE TITLE
create-build-cluster.sh tries to curl a non existent file

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#3060]
https://github.com/knative/test-infra/blob/main/config/prow/build-cluster/create-build-cluster.sh#L36 results in a 404.

**Comment by psschwei** [comment]
It shows up for me

<img width="546" alt="image" src="https://user-images.githubusercontent.com/44698588/151997934-8c0cb9e3-85b3-4589-b0a2-663ac99cc613.png">

**Comment by kvmware** [comment]
The link on that line points to a non existent file.

![image](https://user-images.githubusercontent.com/84356882/152005974-8cb19131-2c30-4e5e-91bf-82a85f8ea997.png)

**Comment by psschwei** [comment]
Sorry, misread the issue title.

**Comment by cardil** [comment]
Let's remove this. Invoking a shell script, directly downloaded from the network without checking for consistency, isn't safe.

**Comment by kvmware** [comment]
I agree with the downloading a file and running it is not the best, but sorta seems like an idiom used for now (I am guessing to avoid duplicating and manually syncing files) https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/create-build-cluster.sh#L36

**Comment by cardil** [comment]
At least, we should check the download sha, before executing it blindly. It's not an excuse that other people does that. 

Yes, people do that, then get hacked and stop doing that.
