### ISSUE TITLE
Coverage jobs are failing with no apparent reason

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#308]
/assign @steuhs 

Example:
https://github.com/knative/eventing-sources/pull/154#issuecomment-445954045

GitHub links to https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing-sources/154/pull-knative-eventing-sources-go-coverage/1072220963090731009/ which shows 

Unable to load build details from gs://knative-prow/pr-logs/pull/knative_eventing-sources/154/pull-knative-eventing-sources-go-coverage/1072220963090731009

**Comment by steuhs** [comment]
There is no information on the build logged. Probably fails before the coverage binary is run. Will take a closer look later

**Comment by adrcunha** [comment]
Note that it also failed for PR 2691 in serving, so this is not an isolated case.

**Comment by adrcunha** [comment]
Looks like your job is failing at the very start. Start by finding the job in the cluster and investigating is logs.

**Comment by steuhs** [comment]
It's likely to be unrelated to coverage job. Something changed before 12:03pm, Dec 10th and then all the coverage jobs starts failing. https://prow.knative.dev/?job=pull-knative-serving-go-coverage

The behavior is similar here
https://prow.knative.dev/?job=ci-knative-build-latency

@chaodaiG has done some investigation and this PR probably cause the issue https://github.com/knative/test-infra/pull/303

@adrcunha
