### ISSUE TITLE
[Discussion] Move ./tools and ./pkg dir out into their own repo.

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#3100]
In the effort to try to cleanup and simplify `test-infra` repo, I think maybe we should move all the golang tools into their own directory and keep `test-infra` more as a central place for configurations etc. Problem is golang is very crufty and expect a root `pkg` folder as well as `go.mod` and `go.sum` which is very confusing in a repo. The repo is currently being used as a golang project as well as a central organization. Open to other ideas of how to clean that up.

With a org search https://github.com/search?p=1&q=org%3Aknative+knative.dev+test-infra+pkg+-repo%3Aknative%2Ftest-infra+-repo%3Aknative%2Feventing-operator+-repo%3Aknative%2Fserving-operator+-repo%3Aknative%2Fclient-contrib&type=Code it seems that nothing is using `test-infra` go project except for the tools in the repo itself so it would be a clean/easy move to a new repo.

**Comment by chizhg** [comment]
Previously we made a lot of effort on removing the `test-infra` dependency for other Knative projects, see the discussions in https://github.com/knative/test-infra/issues/2078 and https://github.com/knative/test-infra/issues/2069, and we ended up moving the Bash scripts to a separate `hack` repo. 

Currently `test-infra` is standalone and it should not be imported by any other repos, and this has been working well except having a relatively big `go.mod` file, so I'm not sure what's the benefit we can get by moving `./tools` and `./pkg` to a separate repo, which would potentially make the dependency chain more complicated.

**Comment by kvmware** [comment]
I am suggesting moving all the golang stuff to a single repo. Not, each own repos. Sorry should have clarified that

**Comment by kvmware** [comment]
We should also move `buoy` to `tools` as well

**Comment by kvmware** [comment]
would have to copy buoy first then cherrypick the hack scripts to all the supported releases then finally remove buoy
