### ISSUE TITLE
Enable postsubmit Prow job once CNCF process is complete

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#3101]
From https://github.com/knative/test-infra/issues/2982 "Prow team is stilling managing the Knative Prow instance. We'll do it after Knative is officially accepted by CNCF and the process is completely removed from oss-test-infra repo. So keeping this issue open for now for better tracking purpose."

Uncomment and enable https://github.com/knative/test-infra/blob/main/prow/jobs/custom/autodeploy-prow.yaml

**Comment by chizhg** [comment]
This is done by https://github.com/knative/test-infra/pull/3208
