### ISSUE TITLE
Drop usage of `go get` in favour of `go install` 

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#3113]
using `go get` to install a binary is deprecated in go1.17 and [is support is removed in go1.18](https://tip.golang.org/doc/go1.18#go-command)

Mentioned here: https://github.com/knative/serving/pull/12653#issuecomment-1048120859

/assign @chizhg @kvmware 

Any chance you could take a look at this sometime this week - go1.18 comes out either next week or the week after.

I know we won't plan on moving our CI to go1.18 immediately but it would be good to make sure new contributors don't hit issues running our scripts locally

**Comment by kvmware** [comment]
https://github.com/knative/hack/search?q=%22go+get seems to have all 1.18> valid `go get` commands. From the release notes, `(with GO111MODULE=off), go get still builds and installs packages, as before` and the other command uses `-d` flag.

I can check other repos though or please point out anything if I am missing anything.

**Comment by dprotaso** [comment]
We're using it in `run_go_tool`: https://github.com/knative/hack/blob/cf8cbc0e9165fb3193e6e145852e238c0f816746/library.sh#L554

And we can drop the workaround in that bash function around since `go install` doesn't modify the `go.mod` file anymore.

> From the release notes, (with GO111MODULE=off), go get still builds and installs packages, as before and the other command uses -d flag.

`go install` has been around for over a year - I think we're good to adopt it as most tools have adopted modules etc.
