### ISSUE TITLE
Proposal - Infrastructure Management Methods

### ISSUE THREAD

**Issue by upodroid** [knative/test-infra#3147]
As part of the CNCF migration, the Google Cloud projects are being handed over by Google. We want to manage the entire infrastructure using Infrastructure as Code tools and store the configuration in this git repository in the infra/gcp folder.

We need to agree how we will manage our infrastructure and we have a few options:
- bash 👎
  - Example One https://github.com/kubernetes/k8s.io/tree/main/infra/gcp/bash - Bash is legacy in k8s.io
  - Example Two https://github.com/knative/test-infra/blob/main/prow/cluster/boskos
- Terraform 👍
- [Config Connector](https://cloud.google.com/config-connector/docs/overview) 👎

Once we have an agreement on the IaC tool, I will go ahead and write the terraform code to manage all the infrastructure in the knative projects.

/kind cncf-infra
/kind cncf-after

**Comment by ameukam** [comment]
>  Bash is legacy in k8s.io

For more clarification, bash is still used in some specific use cases; I don't think _legacy_ is the right term for SIG k8s Infra. Terraform is the preferred tool at the moment for infrastructure management. 

We also want to investigate tools like `Config Connector` or CrossPlane in the future depending on the progress we make during the migration to the community infrastructure. See https://github.com/kubernetes/k8s.io/issues/3324.

**Comment by kvmware** [comment]
As discussed in productivity:
Let us move forward with terraform and let us punt on a decision to use Config Connector, etc. til later with a new proposal :+1: 
1. It will give us some relieve from complex Bash.
2. it is an industry standard and has wide support. (ex. can export google cloud config as terraform etc.)

**Comment by kvmware** [comment]
Been in prod for awhile.
