### ISSUE TITLE
Turn off vulnerability scanning for knative-nightly images

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#3163]
According to the report:
![image](https://user-images.githubusercontent.com/19399934/158450274-de0fcb5f-27bf-4ed1-be34-fe2f82b80905.png)
, the cost for vulnerability scanning for the images stored in the `knative-nightly` projects is pretty high.

Since we also do vulnerability scanning for `knative-release`, it makes more sense for us to only enable one, even in the long term, since there are overlaps. So for now let's turn it off for `knative-nightly` to save some costs.

FYI @upodroid

**Comment by chizhg** [comment]
Done.

**Comment by upodroid** [comment]
Good idea, scanning nightlies isn't that useful.
