### ISSUE TITLE
Root cause why 1.2 dot release job for knaitve/eventing wasn't there

### ISSUE THREAD

**Issue by pierDipi** [knative/test-infra#3166]
1.2 dot release job for eventing isn't in this list:
https://github.com/knative/test-infra/blob/9e055f3cecdd4500480968bd2b371419a25ec5d5/prow/config_knative.yaml#L1053-L1067

The list is updated by the [prow-jobs-syncer](https://github.com/knative/test-infra/tree/main/tools/prow-jobs-syncer) tool but for some reason, 1.2 is not there.

Additional context / workaround: https://github.com/knative/test-infra/pull/3165

**Comment by chizhg** [comment]
There was a bug with querying the branches for given repos, which should have been fixed by the new `release-jobs-syncer` tool added in https://github.com/knative/test-infra/pull/3191.

/close
