### ISSUE TITLE
Getting a Power CI for Knative

### ISSUE THREAD

**Issue by gyliu513** [knative/test-infra#318]
We want to enable Knative running on POWER, so it is better to enable POWER CI for Knative as well.

Can anyone propose some help for how to enable this?

**Comment by adrcunha** [comment]
Can you please elaborate on your proposal, and how it affects/benefits the current Knative CI/CD system?

**Comment by gyliu513** [comment]
Thanks @adrcunha , If I can provide some POWER machines for Knative, who I need to contact to enable Knative CI running on those machines?

**Comment by adrcunha** [comment]
Let's discuss the idea first, then we can discuss the implementation details. :)

**Comment by gyliu513** [comment]
More info here, you may also see that Kubernetes now support x86, POWER and s390x for each release, this is because now many customers are using a mixed infrastructures for their cloud, so it would be great for Knative CI enable POWER support. 

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#server-binaries

ppc64le is for POWER.

@adrcunha as the Knative meeting time is not China friendly and I may not able to attend meeting for discussion, but would be good talk this via this issue, please show your comments if any ;-)

**Comment by gyliu513** [comment]
Thanks @adrcunha , got it, I will start from the first item: Building knative on ppc64le, will append some detail here when there are some progress.

**Comment by gyliu513** [comment]
FYI @seth-priya @bpradipt
