### ISSUE TITLE
Create budgets & alerts for Knative infra billing

### ISSUE THREAD

**Issue by chizhg** [knative/test-infra#3212]
Once Knative infra is switched to CNCF billing, budgets and alerts need to be created to prevent over-cost.

From the `Billing` page:

Avoid surprises on your bill by creating budgets to monitor all your Google Cloud charges in one place. After you’ve set a budget, you can create budget alerts to email billing admins and users when charges exceed a certain amount.

**Comment by chizhg** [comment]
Specially GCR egress traffic costs can grow without control - https://docs.google.com/document/d/1yNQ7DaDE5LbDJf9ku82YtlKZK0tcg5Wpk9L72-x2S2k/edit#, so we need to keep that in mind.

**Comment by kvmware** [comment]
Waiting for billing accounts to fully transfer to community.

**Comment by kvmware** [comment]
/remove-lifecycle stale
@upodroid  any updates on this?
