### ISSUE TITLE
Enable the verify-owners plugin for Prow

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#324]
The verify-owners plugin validates OWNERS files if they are modified in a PR. On validation failure it automatically adds the 'invalid-owners' label to the PR, and a review comment on the incriminating file(s).

Source:
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/verify-owners/verify-owners.go

**Comment by yt3liu** [comment]
Tested the Prow plugin that it add the tag 'do-not-merge/invalid-owners-file' when OWNERS file is invalid. And does not add the tag when the OWNERS file is valid. 

Test PR: https://github.com/knative/test-infra/pull/548

**Comment by adrcunha** [comment]
Thanks Joyce!

\close
