### ISSUE TITLE
Knative org peribolos job is failing

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#3247]
See: https://prow.knative.dev/?job=*peribolos*

`
{"client":"github","component":"peribolos","file":"k8s.io/test-infra/prow/github/client.go:907","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"RemoveOrgMembership(knative, google-ospo-team)","severity":"info","time":"2022-04-07T16:44:57Z"}
{"component":"peribolos","file":"k8s.io/test-infra/prow/cmd/peribolos/main.go:209","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative members: status code 422 not one of [200], body: {\"message\":\"The request could not be processed.\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","severity":"fatal","time":"2022-04-07T16:44:57Z"}
`

**Comment by chizhg** [comment]
See the reason in https://knative.slack.com/archives/CCSNR4FCH/p1649255826443469

**Comment by chizhg** [comment]
Possibly also duplicate with https://github.com/knative/community/issues/186

**Comment by chizhg** [comment]
Temporary fix will be removing `aryann` from the knative peribolos config file. The same approach will apply for the following errors like this.

/cc @dprotaso @kvmware
