### ISSUE TITLE
Review bazel settings in Prow config

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#326]
Things that *might* not be needed/necessary anymore:

* bazel remote cache (OR actually set it up)
* privileged mode

**Comment by srinivashegde86** [comment]
we use kubernetes_execute_bazel scenario used to run the workflows. there is a non-bazel version as well, which we can use

**Comment by adrcunha** [comment]
We use bazel for the test result parsing, so we can't drop bazel (unless someone wants to write a parser).

**Comment by adrcunha** [comment]
The parser is actually a good idea. Filed #332.

**Comment by adrcunha** [comment]
The current bazel settings seem to be useless to our parser:

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/2745/pull-knative-serving-unit-tests/1074919996653572096/

This is https://prow.knative.dev/log?job=pull-knative-serving-unit-tests&id=1074919996653572096 which is a Prow job without the bazel settings at all.
