### ISSUE TITLE
Pull kn.dev into knative-dns project

### ISSUE THREAD

**Issue by hh** [knative/test-infra#3299]
- [ ] Change DNS servers / zone service to Knative-dns
- [x] Create DNS xfer codes
- [x] Send request to LF IT with codes https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

https://github.com/knative/test-infra/issues/3134#issuecomment-1112442000
> When I was at Google I also scooped `kn.dev` for Knative, if it's easy enough to transfer that, I'd suggest it as well.

**Comment by chizhg** [comment]
There is also a kn-e2e.dev domain which is used by the auto TLS e2e test - https://github.com/knative/serving/blob/main/test/e2e-auto-tls-tests.sh#L27

**Comment by upodroid** [comment]
@thisisnotapril @mattmoor @hh Can we initiate the transfer of ownership for kn.dev and kn-e2e.dev?

Please use the following NS Records:

```
kn.dev
ns-cloud-c1.googledomains.com. 
ns-cloud-c2.googledomains.com. 
ns-cloud-c3.googledomains.com. 
ns-cloud-c4.googledomains.com.
```

```
kn-e2e.dev
ns-cloud-e1.googledomains.com.
ns-cloud-e3.googledomains.com.
ns-cloud-e4.googledomains.com.
ns-cloud-e2.googledomains.com.
```

**Comment by upodroid** [comment]
Google handed the xfer codes to LF. This should be done later this week and LF will modify the domain to use the correct NS servers.

**Comment by upodroid** [comment]
@hh What is the latest on this ticket?

**Comment by hh** [comment]
[IT-24536](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-24536) - kn.dev NS records update

**Comment by upodroid** [comment]
This is done now.

Thanks

```
 REDACTED  MCW0CDP3YY  ~  $  dig ns kn-e2e.dev +short
ns-cloud-e2.googledomains.com.
ns-cloud-e1.googledomains.com.
ns-cloud-e4.googledomains.com.
ns-cloud-e3.googledomains.com.
 REDACTED  MCW0CDP3YY  ~  $  dig ns kn.dev +short
ns-cloud-c4.googledomains.com.
ns-cloud-c2.googledomains.com.
ns-cloud-c3.googledomains.com.
ns-cloud-c1.googledomains.com.
```
