### ISSUE TITLE
Peribolos weirdness

### ISSUE THREAD

**Issue by kvmware** [knative/test-infra#3384]
1. Adding empty new groups with dry-run has problems
- https://github.com/knative/community/pull/1091 related
- https://github.com/kubernetes/test-infra/issues/26542
3. Productivity-wg leads are not admins of repos

**Comment by dprotaso** [comment]
I think the way the dry-run is configured is incorrect

https://github.com/kubernetes/test-infra/issues/26542#issuecomment-1151773192

I'm guessing we don't want these `fix` flags
https://github.com/knative/test-infra/blob/dbfbc04b6384fc92094f1923be2f8383d84bd701/prow/jobs/custom/peribolos.yaml#L41-L48

I haven't dug deeply into the tooling

**Comment by kvmware** [comment]
Yes @upodroid and I talked about this. We are for sure using the tool incorrectly it seems. We will investigate and try to mimic k8s setup more.

**Comment by dprotaso** [comment]
Any updates?

This is blocking a bunch of administrative knative/community PRs modifying/adding 

ie. https://github.com/knative/community/pull/1091
