### ISSUE TITLE
Allow creating major releases from existing nightly builds

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#365]
Add the flag `--from-nightly` to `release.sh` that will:
* **NOT** run any test
* find out the commit used to create the nightly release given by the `--from-nightly` flag
* create a *release-X.Y* branch on the GitHub repo (version given by the `--version` flag) from such commit
* copy the already built nightly images/manifests to the release GCR/GCS, properly tagging them (version given by the `--version` flag)
* publish the release on GitHub (version given by the `--version` flag, optional release notes given by the `--release-notes` flag)

Also add the flag `--from-latest-nightly` as a shortcut form for `--from-nightly <tag of the latest nightly>`.

CC @evankanderson @mattmoor

**Comment by scothis** [comment]
What nightly releases? I don't see any artifacts since November. 

https://console.cloud.google.com/storage/browser/knative-releases/

**Comment by adrcunha** [comment]
Nightly releases now live in https://console.cloud.google.com/storage/browser/knative-nightly/
