### ISSUE TITLE
Personalize covbot

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#367]
Currently the bot used to post coverage reports on PRs is simply "covbot". It should have a clearly identifiable name,  profile and avatar, just like knative-prow-robot and knative-prow-releaser-robot.

**Comment by srinivashegde86** [comment]
Resurrecting this issue again :)

I would like to report on certain benchmarks once we add them to the PR conversation similar to what we do for coverage report. I would prefer not to have another bot to report results and reuse the bot once we update it to report these benchmark results as well or we want to keep this separate and not reuse it for perf benchmark reports?

SG?

/cc @adrcunha 
/cc @jessiezcc

**Comment by adrcunha** [comment]
Less is more. covbot could be renamed to "Metrics Robot" and used to report all kind of custom metrics.

**Comment by srinivashegde86** [comment]
I have renamed the bot to kn-metrics-bot.

**Comment by adrcunha** [comment]
Can it be knative-metrics-robot, so the name is in sync with the other robots?

**Comment by srinivashegde86** [comment]
done. updated to knative-metrics-robot

**Comment by adrcunha** [comment]
Thanks. Looking forward to the updated robot profile. :)

**Comment by adrcunha** [comment]
I updated the robot profile.

![image](https://user-images.githubusercontent.com/35786489/58984644-5f91b080-878e-11e9-8a46-e4d5d552c4b4.png)
