### ISSUE TITLE
Automate the creation of major releases

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#368]
Summary: a bi-hourly job (to ensure enough time for building a release) checks for new release branches (using the releases published on GitHub for comparison), then builds a new major release.

**Comment by adrcunha** [comment]
@nbarthwal goal is to have this ready by end of January.

**Comment by jessiezcc** [comment]
reopen since the issue is not fully addressed without prow job

**Comment by jessiezcc** [comment]
@nbarthwal, .4 release is only 1.5 week away.

**Comment by nbarthwal** [comment]
Yes, working on it!

**Comment by adrcunha** [comment]
For monitoring, we need a new tab in Testgrid.

**Comment by adrcunha** [comment]
Nikhil left the team, assigning this issue to me.
/assign adrcunha
/unassign nbarthwal

**Comment by adrcunha** [comment]
Documentation is the last part of this issue, so closing this as we have issue #491 tracking this.
/close
