### ISSUE TITLE
Reviewers not being assigned by prow

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#3719]
I created a PR and for some reason reviewers weren't added by Prow

https://github.com/knative-sandbox/net-istio/pull/1061

But I have `reviewers` in the OWNERS file

https://github.com/knative-sandbox/net-istio/blob/f055c175caad377e3187defbc4200f36e6e2ab6a/OWNERS#L9-L11

**Comment by dprotaso** [comment]
I'm gonna close this out - I think it's working as expected now

**Comment by dprotaso** [comment]
This doesn't seem to be working

https://github.com/knative-sandbox/net-istio/pull/1117
https://github.com/knative-sandbox/net-certmanager/pull/540

/unassign @upodroid 

@kvmware can you look into this

**Comment by kvmware** [comment]
To confirm you are not seeing this only on knative-sandbox or also with knative?
I am seeing as recently as 5mins ago this working for knative at least.

**Comment by dprotaso** [comment]
I'm noticing it's not working in knative-sandbox
