### ISSUE TITLE
Split `test-infra` repo into `tools` and `infra` repos

### ISSUE THREAD

**Issue by cardil** [knative/test-infra#3721]
## Problem

This repo contains a bunch of tools that are used for development, testing and release purposes. It also contains Prow configuration. I think that's unnecessary bonding of entirely different interests.

## Proposal

I think we should split this repo in two: 

- `knative/tools` - to hold all Golang tools used across projects for various purposes (Golang pkg: `knative.dev/tool`)
- `knative/infra` - configuration of CI/CD infrastructure (Prow, and Testgrid for now, maybe GitHub actions as well)

### Layout

- `knative/tools` - a flat list of directories which each containing a single tool, plus a pkg dir for shared code.
- `knative/infra` -
   - `prow` - Prow configuration
   - `images` - files needed for building images used by prow
   - `testgrid` - Testgrid configuration
   - `configgen` - single tool that makes sense to leave in infra, as it's directly connected to the Prow config

## Benefits

Such layout would allow for greater discoverability for new contributors, as it's immediately obvious where the tools should go, or where infrastructure code should go.

That would allow us to create more and more Go-native tooling in `knative/tools`, by moving parts of `knative/hack`, until its total removal.

It will also allow for better code review, as now this repo contains two completely separate expertises.

## Downsides

Separating repository always disrupt old PR and issues who link to that repository. We should ensure both new repos contain full history of test-infra.

## Implementation

To keep the history, we will do the following steps twice. Once for `infra` and once for `tools` repos. For each repo, do:

1. Create a repo, by copying `knative/test-infra` repo
1. In a single commit
   1. Remove all things that don't belong to the new repository
   2. Move stuff to new places
1. Adjust other places to point to new location
1. Make `knative/test-infra` an archive

**NOTE:** The `knative/infra` repo exists already, but as @kvmware saying we can totally replace it with new extracted infra from this repo.

## Open decisions

Alternatively, we can create `knative/prow` repo instead of `knative/infra`. That would reflect a separate `knative/actions` repo. Then instead of migrating `knative/actions` into `knative/infra`, we will leave it where it is, keeping both repos.

Another good name for an infra repo, would be `knative/ci`, or `knative/cicd` (which covers releases as well).

We should also think what repos we should have in the end, so it would be simple both for contributors, and maintainers. My idea would be to minimize the number of repos as much as we can. I'm thinking about those 2 repos: `tools` and `infra`. The `infra` could have content from: `knative/release`, `knative/actions`, `knative-sandbox/knobots` and serve as a home for productivity. The `tools` repo would have tools, which are used in knative, but are general and can be used even outside the project.

/kind cleanup
/area tools
/area prow

**Comment by kvmware** [comment]
Thanks for the write up and issue! I like the idea of us cloning /test-infra to /tools and /infra and archiving test-infra for history sake.

**Comment by dprotaso** [comment]
I'd rather not move GitHub actions away from our `knative/actions` repository - that's the central spot for reusable actions

**Comment by kvmware** [comment]
The idea is once infra is cleaned up and should only be hosting prow, terraform, etc we would think about bringing in actions there where we would still use reusables, but that would be probably later once we move more to actions and spin down our dependence on prow. Is there any big push back reason you would have for keeping actions separate at that point?

**Comment by cardil** [comment]
@dprotaso If we move those actions, it would be just a minor change for consuming repos.

```diff
jobs:
  test:
-     uses: knative/actions/.github/workflows/go-test.yaml@main
+     uses: knative/infra/github/workflows/go-test.yaml@main
```

I think that's doable. Looks easy.

**Comment by dprotaso** [comment]
> Is there any big push back reason you would have for keeping actions separate at that point?

I just don't see the value of the churn - and you'll have to keep the old actions around for at least 6 months so you don't break release branches (or you update branches as well)

**Comment by cardil** [comment]
If we decide to move the actions (for sure, that's for the future, not now), we'll definitely leave the old repo in place as a read-only archive.

Also, the old branches, should really be using actions from a specific release, not the tip. We know otherwise repos CI may be in a defunct state and will require manual revitalization, by aligning actions to previous, compatible versions.

**Comment by dprotaso** [comment]
> Also, the old branches, should really be using actions from a specific release, not the tip. We know otherwise repos CI may be in a defunct state and will require manual revitalization, by aligning actions to previous, compatible versions.

A big con to this approach is you could be building with older golang versions that could have a CVE

**Comment by kvmware** [comment]
basically done
