### ISSUE TITLE
Spin down 1.7 jobs

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#3728]
It's EOL - https://github.com/knative/community/pull/1286

**Comment by dprotaso** [comment]
Now we should spin down 1.8

**Comment by kvmware** [comment]
Sync release job did this. However, I did notice that https://github.com/knative/test-infra/pull/3814/files#diff-c6e6fe0f377ccb5123277dec6908f0faafe110ca1f104735b296e7a2c4108e6dL87-L97 older jobs still remain, is there a reason for this?

**Comment by dprotaso** [comment]
Looks like the job didn't spin down 1.8 releases

**Comment by kvmware** [comment]
we keep last three right? 1.10, 1.9, 1.8 no?

**Comment by dprotaso** [comment]
No last two - https://github.com/knative/test-infra/pull/3815

**Comment by dprotaso** [comment]
> I did notice that https://github.com/knative/test-infra/pull/3814/files#diff-c6e6fe0f377ccb5123277dec6908f0faafe110ca1f104735b296e7a2c4108e6dL87-L97 older jobs still remain, is there a reason for this?

It seems like security guard has versions 0.3,0.4 etc 

and older repos that got off the release train still have old jobs for releases that aren't supported

> prow/jobs/generated/knative-sandbox/eventing-awssqs-release-1.2.gen.yaml
