### ISSUE TITLE
githubhelper doesn't list all changed files in a PR

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#374]
In

https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_docs/734/pull-knative-docs-build-tests/1083251881859354624/build-log.txt

the merge process reports 519 files changes, but githubhelper lists only 30.

**Comment by chaodaiG** [comment]
This might be the reason:
https://github.com/google/go-github#rate-limiting
Anonymous client has a rate limit of 30 requests per minute.
@adrcunha

**Comment by chaodaiG** [comment]
This can be fixed if we use an token from service account

**Comment by adrcunha** [comment]
We can use the Knative bot. Are you willing to fix that, Chao? :D

**Comment by chaodaiG** [comment]
yeah I can work on it, since I'm learning how to use github api

**Comment by adrcunha** [comment]
#529 does fix the issue:

```
$ REPO_OWNER=knative REPO_NAME=docs PULL_NUMBER=734 go run githubhelper.go -list-changed-files | wc -l
520
```

Thanks Adam for that.
