### ISSUE TITLE
Investigate using Failure Aggregator for knative

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#414]
k8s has a failure aggregator that provides trending view of all the failures. This will be great for admins and WG's to check failures and identify flakes.

k8s version - https://storage.googleapis.com/k8s-gubernator/triage/index.html

**Comment by chaodaiG** [comment]
this looks pretty good. In terms of implementation, not sure how much we could leverage from k8s, if not there is going to be a major investment on re-implementing `test-infra/kettle` for data collection, and `test-infra/triage` for UI. Also we need to have a discussion of whether we want to store data in bigquery or not

**Comment by srinivashegde86** [comment]
idk much about kettle. I initially thought it might be simple to bring up. If this needs a lot of work, we can probably hold on to this for later.

**Comment by chaodaiG** [comment]
sounds good. I think bigquery is certainly worthy looking into when the needs come, and we could iterate on this then.

**Comment by adrcunha** [comment]
The dashboard code lives in https://github.com/kubernetes/test-infra/tree/master/triage
