### ISSUE TITLE
Performance tests do not show overview of failed tests

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#422]
Sample ivocation:
https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-performance/1088602638884278273/

**Comment by adrcunha** [comment]
This is because it's not using `go_test_e2e`, which generates the summary. Coincidentally I found it out this morning and I'm including the fix in a PR I'm working on.

**Comment by adrcunha** [comment]
Fixed by https://github.com/knative/serving/pull/3017
