### ISSUE TITLE
Release script is not pushing manifests to GCS

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#433]
The `publish_yamls` step was not merged in #392. As a result, the release script publishes the images, but not the manifests.

**Comment by steuhs** [comment]
What does this issue look like? Does it fail the prow job?

**Comment by srinivashegde86** [comment]
Nope. This is one of the things, the release script does. This was a functionality missing issue. Not related to the prow job.

**Comment by srinivashegde86** [comment]
This is one of the functionalities of the release script and it did not fail the prow job.

**Comment by steuhs** [comment]
How was the problem noticed? What was the symptom?

**Comment by adrcunha** [comment]
Broken tests due to missing file in GCS.
