### ISSUE TITLE
Analyze package dependency between knative/test-infra and knative/serving

### ISSUE THREAD

**Issue by dushyanthsc** [knative/test-infra#441]
Ideally we should not have any dependency from knative/test-infra to knative-serving. We currently have this dependency which would bring serving to other repos, when they express dependency on test-infra. This issue is created to analyze where these dependencies exist and if possible move them to pkg if needed.

**Comment by adrcunha** [comment]
This is concerning. `test-infra` is intended to be repo-agnostic and this might lead to weird dependency issues. We should prioritize this.

**Comment by dushyanthsc** [comment]
I will take this up will take a look next week.

**Comment by dushyanthsc** [comment]
The dependency was introduced in the API Coverage tool:
https://github.com/knative/test-infra/blob/master/tools/apicoverage/apicoverage.go#L31

Spoke to Srinivas about this and the plan is that since the above tool would retired soon, we would just wait for webhook coverage tool work to complete and just delete this package from test-infra.

The only other dependency is: https://github.com/knative/test-infra/blob/master/tools/webhook-apicoverage/webhook/webhook.go#L29

I will work on removing this dependency this week and remove it.

**Comment by jessiezcc** [comment]
what's the latest on this issue, @dushyanthsc?

**Comment by dushyanthsc** [comment]
I removed the second dependency in this PR: https://github.com/knative/test-infra/pull/463

For the first one, it will be removed as part of retiring the old API Coverage tool which is waiting on the prow job for the new tool. 

ETA end of next week.

**Comment by adrcunha** [comment]
API Coverage was removed and also its dependency on knative/serving.
