### ISSUE TITLE
coverage job is not reporting metrics to testgrid

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#442]
https://testgrid.knative.dev/knative-serving#coverage shows blank rows for the last 3 days.

**Comment by adrcunha** [comment]
cough... how I miss monitoring... cough... :)

**Comment by steuhs** [comment]
From https://storage.cloud.google.com/knative-prow/logs/ci-knative-serving-go-coverage/1091139354480349184/build-log.txt:

--- FAIL: TestNewRouteCallsSyncHandler (3.50s)
	logger.go:130: 2019-02-01T01:02:56.763Z	DEBUG	TestNewRouteCallsSyncHandler.route-controller	reconciler/reconciler.go:109	Creating event broadcaster	{"knative.dev/controller": "route-controller"}
	logger.go:130: 2019-02-01T01:02:56.763Z	DEBUG	TestNewRouteCallsSyncHandler.route-controller	reconciler/reconciler.go:119	Creating stats reporter	{"knative.dev/controller": "route-controller"}
	logger.go:130: 2019-02-01T01:02:56.763Z	INFO	TestNewRouteCallsSyncHandler.route-controller	route/route.go:131	Setting up event handlers	{"knative.dev/controller": "route-controller"}

**Comment by steuhs** [comment]
Coverage job relies on the unit tests to pass. This test should be flaky, otherwise it should not get into the master branch in the first place. The change I can make is to ignore failed tests and let the process go through without data from failed tests

**Comment by srinivashegde86** [comment]
that is passing in the continous runs though. What is the difference here?

**Comment by steuhs** [comment]
@srinivashegde86 do you have the script for continuous run? Does it call "go test" on the entire repo?

**Comment by srinivashegde86** [comment]
yes. it ultimately uses `go test` to run the tests through some utility functions.

https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh#L74

https://github.com/knative/test-infra/blob/master/scripts/library.sh#L247

**Comment by steuhs** [comment]
@srinivashegde86 I assume the e2e test script only runs the e2e tests, not the unit tests. Is that right?

**Comment by steuhs** [comment]
@srinivashegde86 I do see it (pkg/reconciler/v1alpha1/route.TestNewRouteCallsSyncHandler) fails sometimes recently https://testgrid.knative.dev/knative-serving#continuous

**Comment by jessiezcc** [comment]
@steuhs, any progress udpate on the fix?
