### ISSUE TITLE
Move conformance tests to its own repo

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#444]
conformance validation should not be tied into serving repo. It'd make sense to be separated to its own repo for better portability.

**Comment by jessiezcc** [comment]
Need a tech discussion for go/nogo with wg leads

**Comment by adrcunha** [comment]
With https://github.com/knative/serving/issues/4263 it would be unnecessary to separate the conformance tests from serving, and maintain yet another Knative repository.

**Comment by mattmoor** [comment]
Yeah, I don't want this if we can avoid it.  Closing since we seem to be in agreement on that.
