### ISSUE TITLE
More prow jobs doing less stuff

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#459]
We've been cramming stuff (like markdown checks) into existing CI legs, which:
1. Makes it less clear from the failing job what exactly failed
2. Makes each leg longer (at a minimum this is relevant to flake reruns)

My recollection is that the k8s.io/test-infra folks have separated out things like `verify-bazel` and whatnot into separate legs, so it's clear even without making the jump to gubernator what's wrong.

**Comment by adrcunha** [comment]
At a minimum, this depends on #382, or our already-hard-to-read Prow config will become as terrible as k8s' Prow config.

It also requires refactoring how we run presubmit tests (and thus the CI tests), which seems to offer a good opportunity to:

1. migrate the (already complex) bash scripts to Go (preferred) or some other language
1. drop kubetest (#424)
1. show better errors in build tests (#428)

Of course, there's the dirty way of doing it, which basically means adding more flags to `presubmit-tests.sh` and replicating the presubmit jobs.

**Comment by adrcunha** [comment]
[WIP] Assorted comments about the new test-infra:
* it should allow running old tests (e.g., running tests from the 0.5 branch, even though HEAD is now 0.6)
* prefer providing test services  as opposed to providing shared code

**Comment by evankanderson** [comment]
One additional observation (which may be obvious) for the new test setup:

Test setup should probably be thought as a nesting set (stack) of operations. At a minimum:

1. Provision resources (i.e. GKE cluster, kind cluster, etc for e2e tests)
2. Setup environment (i.e. load base CRDs, controllers)
3. Create test-specific resources and validate behavior (within go test, typically)

It seems like step 1 and step 2 should be separable -- step 1 would be the responsibility of the test-infra repo, while step 2 would be the responsibility of the repo under test (i.e. via an operator, helm chart, or `ko apply`). For manual testing, users would start at either 3 or 2 in most cases, but could also have a harness to perform 1 (and there could be different harnesses for 1 for kind, GKE, etc).

**Comment by evankanderson** [comment]
Thinking about this a bit more:

It seems like `test-infra` should run a tool which performs step 1 and can bootstrap step 2 via some sort of contract.

It seems like step 2 should live in the component repo, and should be responsible for building the necessary artifacts (docker containers, etc) and then launching them on the cluster.

Step 3 would be independently runnable if you already had a cluster setup (e.g. for conformance testing an existing environment, or for testing against your current state). There would need to be some sort of contract for step 3 to select the cluster (and set of tests) it should run.

An open question is whether Step 3 should be orchestrated by step 1 or step 2. I'd be inclined to say that Step 2 would be a better choice, but I'm not certain; we might end up with a common runner across most/all repos and then end up with the same vendoring situation as we have today.

**Comment by adrcunha** [comment]
All issues mentioned in my first comment are not solved. Feedback and input is now captured in the high level design doc for the next version of the test infrastructure -- https://docs.google.com/document/d/1QHPks3oRKccTpzAOJuU2tgHjyiA0Somm7PwdQVupyk0/edit -- feedback is welcome.

Closing this issue, as new work/tasks should be in separate, smaller issues.

**Comment by chizhg** [comment]
/uncc @adrcunha 

As test-infra 2.0 was not launched as planned, some of the discussions under this issue need to be revisited.

/reopen

**Comment by chizhg** [comment]
Many workloads have been moved to GitHub Actions, so it's not an issue anymore.
