### ISSUE TITLE
Protect release script changes in presubmit tests

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#471]
Changes in release script could cause CI jobs failure, we should have a mechanism preventing this from happening in presubmit test

**Comment by chaodaiG** [comment]
An example, on Jan 11th, a [PR](https://github.com/knative/build/pull/529) renamed `release.yaml` to `build.yaml`, which caused continuous and presubmit tests failing in eventing and build-template repo

**Comment by adrcunha** [comment]
That's not a good example. This was a valid change and the errors in eventing should be alerted by monitoring.

**Comment by chaodaiG** [comment]
agree that this case is very hard to prevent, which is why I didn't put it in the issue body. The purpose of creating this issue is to help test release scripts

**Comment by adrcunha** [comment]
I would rather spend time rewriting the release scripts in something that's not bash than writing tests for it. They don't necessarily have to be written in bash, but they were because when they were first created, it was easy. Plus, a few complications:
* the vendoring approach makes it harder (and slow) to propagate changes.
* lack of monitoring causes errors to be skipped.

**Comment by nbarthwal** [comment]
I completely agree with @adrcunha , I have been very vocal about this from the beginning that release script in bash is a terrible idea and we are accumulating technical debt on it day by day. We need to re-write it in Python/Go/Something else, rather that doing patch work on fixing this mess.

**Comment by jessiezcc** [comment]
should we repurpose this issue to rewrite release script in non bash then?

**Comment by nbarthwal** [comment]
I would say yes @jessiezcc

**Comment by adrcunha** [comment]
1. There's no reason to repurpose an issue, just file a new one and preserve history.
1. Rewriting the release script in some other language is either not a priority and a very narrow scope for something that's more complex (see next item).
1. We should properly plan tackling #459.

**Comment by jessiezcc** [comment]
sounds perfectly good.
