### ISSUE TITLE
Various links in gubernator don't work

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#475]
See here:

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/3179/pull-knative-serving-integration-tests/1095435847307628544/#teste2e-testbuildpipelineandservetaskrun

clicking on 'log files' doesn't work

**Comment by adrcunha** [comment]
It doesn't work for Kubernetes as well. For example:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-multizone/36669/

![image](https://user-images.githubusercontent.com/35786489/52820593-38896480-3061-11e9-97db-99b0ce131383.png)

The link to the log leads to

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-multizone/36669/nodelog?junit=junit_runner.xml&wrap=on

which shows

![image](https://user-images.githubusercontent.com/35786489/52820635-52c34280-3061-11e9-89f5-62a9ae5b7f55.png)

**Comment by adrcunha** [comment]
I think that due to https://github.com/kubernetes/test-infra/issues/10375 this bug won't be fixed.

**Comment by jessiezcc** [comment]
switch to spyglass would solve this. Not worth the engineering effort to fix it given that spyglass is around the corner.
