### ISSUE TITLE
Update go version to 1.12rc1

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#486]
A new feature in serving websockets need to use go1.12rc1 version,
link: https://github.com/knative/serving/pull/3240
Instead of manually installing this version in serving repo, updating it in prow-tests image, so that all jobs use consistent go version. 
This proposal was communicated among team leads and green lighted. Also, our local workstations are already using this version, so the risk of it breaking tests badly is pretty low.

TODO: once 1.12 version becomes stable version, switch back to use standard kubekins-e2e images

**Comment by jessiezcc** [comment]
depending on 1.12 to be official, let's hold

**Comment by adrcunha** [comment]
1.12 is now official: https://golang.org/dl/
