### ISSUE TITLE
Clean up TestPerformanceLatency category on testgrid perf tab

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#488]
We renamed TestPerformanceLatency to TestTimeToServeLatency, but it still shows up on testgrid. 
It needs to be cleaned up so that it doesn't cause any user confusion.

**Comment by srinivashegde86** [comment]
Cleaned up the few days where we were using the wrong names. Should be reflected in testgrid soon. Will wait to confirm and close

**Comment by srinivashegde86** [comment]
I cleaned up the artifacts - https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-performance/1095125622620950530

but testgrid still shows TestPerformanceLatency on the tabs. Maybe its using its cached results and not updating it?

**Comment by srinivashegde86** [comment]
this is now fixed
