### ISSUE TITLE
`ko resolve` failure should abort the release

### ISSUE THREAD

**Issue by ImJasonH** [knative/test-infra#513]
knative/build's `release.sh` includes [this](https://github.com/knative/build/blob/release-0.4/hack/release.sh#L33):

```
function build_release() {
  ...
  ko resolve ${KO_FLAGS} -f config/ > ${OUTPUT_YAML}
  YAMLS_TO_PUBLISH="${OUTPUT_YAML}"
}

main $@
```

When `ko resolve` fails (like due to a [typo](https://github.com/knative/build/pull/567) for instance), the `build_release` function continues and the [`main` call to `build_release`](https://github.com/knative/build/blob/release-0.4/vendor/github.com/knative/test-infra/scripts/release.sh#L391) doesn't fail, and instead proceeds to push the release to GitHub and GCS.

This led to a silently broken Build v0.4.0 release in https://github.com/knative/build/issues/566

When `ko resolve` fails it should abort the release instead.

/assign @nbarthwal

**Comment by adrcunha** [comment]
A blanker protection should be calling  `build_release` between `set -e` and `set +e`. This kind of bug is easy to be reintroduced whenever something changes in the release build.

**Comment by adrcunha** [comment]
Interesting, a failure in `ko resolve` should actually fail the release:

https://github.com/knative/test-infra/blob/master/scripts/release.sh#L386

**Comment by ImJasonH** [comment]
Yeah I was surprised by that too, but @nbarthwal seemed to think this was the correct behavior as written.

**Comment by nbarthwal** [comment]
I tested a dummy script and it showed the same behaviour.

**Comment by adrcunha** [comment]
Forcing an error in the `ko` command correctly fails the build:

```
$ ./hack/release.sh --notag-release --nopublish --skip-tests
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@ Release configuration @@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
- Destination GCR: ko.local
- Tests will NOT be run
- Artifacts WILL NOT be tagged
- Release will not be published
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@ Building the release @@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
2019/02/25 09:56:00 Error enumerating files: lstat xconfig/: no such file or directory
error: error building the release
```

Now let me try the exact error that was silently ignored...

**Comment by adrcunha** [comment]
Ok, to keep this short, the error was swallowed due to the `||` operator when checking if the function failed. Ah, bash weirdness...

**Comment by nbarthwal** [comment]
This line, I think:

build_release ||abort "error building the release"

Will fix it!

**Comment by adrcunha** [comment]
> This line, I think: build_release ||abort "error building the release" Will fix it!

That's the original line. The fix is not using the shortcut operator.

**Comment by nbarthwal** [comment]
On a seperate note, I think we should make writing bash script (or 
whatever alternate solution) a priority. This is accumulating 
unneccessary technical debt!
