### ISSUE TITLE
Integration tests are failing due to GKE version 1.12.5

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#537]
It's failing at least in test-infra and build-pipeline right now:
examples:
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_test-infra/506/pull-knative-test-infra-integration-tests/1101192779393929217/
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_build-pipeline/564/pull-knative-build-pipeline-integration-tests/1101196554120728578/

**Comment by steuhs** [comment]
1.12.5 is now supported on "region=us-west1" and the first issue is resolved.

The 2nd link brings up 404 @chaodaiG

**Comment by adrcunha** [comment]
Second link is not 404s anymore, and the failure was also because 1.12.5 wasn't yet available.
