### ISSUE TITLE
Create a common way to set up monitoring components

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#540]
we have added support for [zipkin tracing](https://github.com/knative/pkg/blob/master/test/zipkin/util.go) and for [prometheus](https://github.com/knative/test-infra/blob/master/shared/prometheus/prometheus.go).

Both these components share common things:
* Check if the port exists
* If exists, check if the component pods exist
* If pods exist, are they running as expected
* IF running, port-forward the component to the port so that we start listening on it.

These should be shared for all components

**Comment by Fredy-Z** [comment]
This issue has been resolved.
/close
