### ISSUE TITLE
Properly check licenses when using go modules

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#546]
Looks like the license checker doesn't work fine with go modules. It should.

See https://github.com/knative/client/pull/34

**Comment by sixolet** [comment]
Running `go mod vendor` doesn't vendor in the relevant binaries that this wants to run, only the go code.

**Comment by adrcunha** [comment]
I'm pretty sure this is done, I just forgot to close it. I'll double check client.

**Comment by adrcunha** [comment]
This is done.
