### ISSUE TITLE
api-coverage tab is empty

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#547]
https://testgrid.knative.dev/knative-serving#api-coverage

![image](https://user-images.githubusercontent.com/35786489/53835759-1b023900-3f43-11e9-8ab0-1472e299a67b.png)

**Comment by adrcunha** [comment]
@srinivashegde86 @jessiezcc is it even worth keeping this tab?

**Comment by jessiezcc** [comment]
@dushyanthsc is going to put new conformance measurement to this tab I believe.

**Comment by dushyanthsc** [comment]
Yes, I will take out this job and put in a new one next week. Assigning it to myself for the moment.

**Comment by adrcunha** [comment]
The job is gone and the tab is now deleted.
