### ISSUE TITLE
Knative setup is flaky for perf tests

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#550]
There have been multiple instances in the past(and yesterday), where the knative setup to build the test cluster fails due to some reason or the other.

For eg, 
` The Service "istio-ingressgateway" is invalid: spec.ports[2].nodePort: Invalid value: 31400: provided port is already allocated`

build log:
https://storage.googleapis.com/knative-prow/logs/ci-knative-serving-performance/1103098011203932160/build-log.txt

I have seen this error atleast a few times and this passes on manual retries.

**Comment by srinivashegde86** [comment]
we can maybe add retries for setup failures?

/cc @adrcunha

**Comment by adrcunha** [comment]
I don't like the retry approach because it's slow, complex and hides the root cause. I would prefer a (tracked) workaround. I've seen this before, so it's not exclusive to the perf jobs.

**Comment by srinivashegde86** [comment]
logged https://github.com/knative/serving/issues/3374 to check on istio behavior

**Comment by adrcunha** [comment]
I understand. Let's leave that as a last resort, since manual checking is even worse. 3374 sounds promising.

**Comment by srinivashegde86** [comment]
the base issue in serving is closed now. Closig this as well

/close
