### ISSUE TITLE
Integration tests are failing due to not enough resource in us-west1-c

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#571]
Examples:
- In repo "serving":
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/3353/pull-knative-serving-integration-tests/1105982603938238464/
- In repo "test-infra"
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_test-infra/567/pull-knative-test-infra-integration-tests/1105985624378183682/

Example error message:
Current errors: [ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS]: Instance 'gke-kserving-e2e-cls1105-default-pool-f041ef5d-599g' creation failed: The zone 'projects/knative-boskos-09/zones/us-west1-c' does not have enough resources available to fulfill the request.  '(resource type:compute)'. - ; Instance 'gke-kserving-e2e-cls1105-default-pool-f041ef5d-7l4k' creation failed: The zone 'projects/knative-boskos-09/zones/us-west1-c' does not have enough resources available to fulfill the request.  '(resource type:compute)'. - ; Instance 'gke-kserving-e2e-cls1105-default-pool-f041ef5d-l33k' creation failed: The zone 'projects/knative-boskos-09/zones/us-west1-c' does not have enough resources available to fulfill the request.  '(resource type:compute)'. - ; Instance 'gke-kserving-e2e-cls1105-default-pool-f041ef5d-nrz5' creation failed: The zone 'projects/knative-boskos-09/zones/us-west1-c' does not have enough resources available to fulfill the request.  '(resource type:compute)'. - ; ."

**Comment by adrcunha** [comment]
Move the jobs to a new region/zone. This is a simple update to the config (through the generator).

**Comment by steuhs** [comment]
This issue is reoccurring today

**Comment by steuhs** [comment]
It happened 3 time in Mar 28th and around 20 times in Mar 29

**Comment by adrcunha** [comment]
Reassigning to the current oncall, @nbarthwal

**Comment by steuhs** [comment]
It happened 4 times today. You can see the occurrences here: https://pantheon.corp.google.com/logs/viewer?project=knative-tests&minLogLevel=0&expandAll=false&timestamp=2019-04-01T20:35:08.586000000Z&customFacets=jsonPayload.to&limitCustomFacetWidth=true&dateRangeStart=2019-03-22T23:38:49.153Z&interval=P7D&resource=container&scrollTimestamp=2019-04-01T18:26:21.000000000Z&filters=text:%22Google%20Compute%20Engine%20does%20not%20have%20enough%20resources%20available%20to%20fulfill%20request:%22&dateRangeUnbound=forwardInTime

**Comment by adrcunha** [comment]
This should have been fixed by #671. Since then we saw no stockouts, so far so good... Considering this fixed.
