### ISSUE TITLE
Use defaults for coverage job flags

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#588]
Currently, there are three flags that we pass to the code coverage job
```
--profile-name=coverage_profile.txt"
--cov-target=.
--cov-threshold-percentage=80
```

Of these, only `cov-threshold-percent` changes to 0 from 80 for post vs pre submit jobs. We should use reasonable defaults in the coverage job and not provide them in all the job configs.

**Comment by adrcunha** [comment]
This is a quick & simple simplification.

/assign @steuhs

**Comment by Fredy-Z** [comment]
Updated `coverage-image`, `coverage-dev-image` and `Prow` config.
/close
