### ISSUE TITLE
Create a common way to upload test images

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#590]
Currently, the repos are having upload-test-images.sh script under the test/ dir. We are modifying [serving](https://github.com/knative/serving/commits/master/test/upload-test-images.sh) and keeping it in shape. We should probably move this over to test-infra and import in all the repos as all the repos are doign this and pretty much in the same way

**Comment by adrcunha** [comment]
/assign @dushyanthsc 

Please reassign to the right person in your crew.

**Comment by adrcunha** [comment]
This is now captured in the high level design doc for the next version of the test infrastructure -- https://docs.google.com/document/d/1QHPks3oRKccTpzAOJuU2tgHjyiA0Somm7PwdQVupyk0/edit -- feedback is welcome.

Closing this issue, as new work/tasks should be in a separate issue.
