### ISSUE TITLE
Add Better Handling of Stockouts 

### ISSUE THREAD

**Issue by ericKlawitter** [knative/test-infra#592]
We should come up with a better way of handling stockouts. In the past, we switched to Zonal GKE Clusters to address this issue, but this is not a tenable solution as zonal clusters aren't highly available.

Let's come up with a better way of dealing with these issues.

**Comment by adrcunha** [comment]
For context, #593 is the rollback of #572 and #573.

**Comment by adrcunha** [comment]
Currently all jobs run in the same region. We could split them among different regions (it's way easier now with the config generator), but I'm not sure how effective that would be.
