### ISSUE TITLE
oncall should show slack handle

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#619]
Right now it's `steuhs`, which isn't a slack handle.

https://storage.googleapis.com/knative-infra-oncall/oncall.html

**Comment by adrcunha** [comment]
![image](https://user-images.githubusercontent.com/35786489/58345150-8d7d0980-7e0c-11e9-965b-25486db3b1fe.png)

**Comment by steuhs** [comment]
Should we set the display name or the full name to github name?

**Comment by adrcunha** [comment]
Display name.

**Comment by adrcunha** [comment]
All oncalls now use their GitHub username as their Slack handle.
