### ISSUE TITLE
Integration tests lack 'compute.targetPools.list' permission for 'projects/knative-tests'

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#625]
The error happens every once a while and resolves itself after several failures.
breakouts since Mar 1st:
Mar 25th
Mar 26th

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing/951/pull-knative-eventing-integration-tests/1110603806170681344/

I0326 18:06:23.420] 2019/03/26 18:06:23 main.go:312: Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resource not found
I0326 18:06:23.422] Test subprocess exited with code 1
I0326 18:06:45.429] ERROR: (gcloud.compute.target-pools.list) Some requests did not succeed:
I0326 18:06:45.429]  - Required 'compute.targetPools.list' permission for 'projects/knative-tests'
I0326 18:06:45.429] 
I0326 18:07:07.246] ERROR: (gcloud.compute.target-pools.list) Some requests did not succeed:
I0326 18:07:07.246]  - Required 'compute.targetPools.list' permission for 'projects/knative-tests'
I0326 18:07:07.247] 
I0326 18:07:07.318] Artifacts were written to /workspace/_artifacts
I0326 18:07:07.319] Test result code is 1
I0326 18:07:07.322] ==================================
I0326 18:07:07.322] ==== INTEGRATION TESTS FAILED ====
I0326 18:07:07.322] ==================================

**Comment by adrcunha** [comment]
Closing in favor of 638.
