### ISSUE TITLE
Email alert for knative-tests project deletion

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#635]
Configure project settings so that email alerts are sent to owners when a project is deleted

**Comment by adrcunha** [comment]
Email alerts should be sent for any major changes (e.g., billing changes).

**Comment by srinivashegde86** [comment]
we now have a lien on project deletion and the project cannot be deleted unless we remove the lien. If we want to track other changes, we should define them and prioritize accordingly. 

I am closing this for now. We should open other bugs based on the requirements.
