### ISSUE TITLE
Separate the dependencies on infrastructure and allow testing running on any K8s cluster

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/test-infra#637]
The current testing depends on bottom infrastructure very much. I'm not able to run e2e test without a Google cloud account, even I have my own K8s cluster on my own cloud infrastructure.

I think we should separate the dependencies to lower level infrastructure. Here are some thoughts in my mind:
- use general command lines, not specific command lines for a single kind of infrastructure
- allow people to define their own cloud infrastructure in a separated file

**Comment by adrcunha** [comment]
Unit tests don't need a cluster, so it's fine. presubmit tests on GitHub do use Google Cloud, but it's all automatic so it's also fine.

You can run E2E tests against any K8s cluster you have running. Basically you set KO_DOCKER_REPO and point kubectl to your cluster and run the E2E tests with go.

For serving, detailed instructions are here (there's no mention of gcloud or Google account in them):

https://github.com/knative/serving/tree/master/test#running-end-to-end-tests

**Comment by jessiezcc** [comment]
per @adrcunha's instruction above, close the issue for now.
