### ISSUE TITLE
Boskos issues causing CI/presubmits to fail

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#638]
We've been seeing failures with acquiring projects from boskos for the CI/presubmit flows.

A generic "resource not found" error:

https://storage.googleapis.com/knative-prow/logs/ci-knative-serving-continuous/1111055658830008320/build-log.txt

Same error, but with permission denials listed:

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing/951/pull-knative-eventing-integration-tests/1110601542886494209/

One possibility is that the boskos pool could be eventually exhausted at peak times.

**Comment by adrcunha** [comment]
We're using a pretty old boskos image (https://github.com/knative/test-infra/blob/master/ci/prow/boskos/config.yaml#L56), we should at least update it to get the latest improvements and bugfixes.

**Comment by steuhs** [comment]
This is the same issue as https://github.com/knative/test-infra/issues/625

**Comment by adrcunha** [comment]
From 625, another example of permission denied errors:

Mar 25th
Mar 26th

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing/951/pull-knative-eventing-integration-tests/1110603806170681344/

```
I0326 18:06:23.420] 2019/03/26 18:06:23 main.go:312: Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resource not found
I0326 18:06:23.422] Test subprocess exited with code 1
I0326 18:06:45.429] ERROR: (gcloud.compute.target-pools.list) Some requests did not succeed:
I0326 18:06:45.429] - Required 'compute.targetPools.list' permission for 'projects/knative-tests'
I0326 18:06:45.429]
I0326 18:07:07.246] ERROR: (gcloud.compute.target-pools.list) Some requests did not succeed:
I0326 18:07:07.246] - Required 'compute.targetPools.list' permission for 'projects/knative-tests'
I0326 18:07:07.247]
I0326 18:07:07.318] Artifacts were written to /workspace/_artifacts
I0326 18:07:07.319] Test result code is 1
I0326 18:07:07.322] ==================================
I0326 18:07:07.322] ==== INTEGRATION TESTS FAILED ====
I0326 18:07:07.322] ==================================
```

**Comment by adrcunha** [comment]
We can ignore the permission denied issues, they're not related to boskos. They actually come from the network cleanup code in e2e-tests.sh:

https://github.com/knative/test-infra/blob/f2aa3067cfc8465c76a42d746dbce063e54df8d1/scripts/e2e-tests.sh#L190

**Comment by adrcunha** [comment]
In addition to updating the boskos service, I also suggest expanding the pool (it definitely won't hurt).

**Comment by adrcunha** [comment]
@steuhs @jessiezcc Just got pinged about this issue. Stephen, I think you should prioritize that; at least the initial tentative fixes I suggested.

**Comment by steuhs** [comment]
@adrcunha by expanding the pool, I guess you mean to increase the number for E2E_MAX_CLUSTER_NODES?

**Comment by evankanderson** [comment]
I have several small cleanup PRs that seem to be hitting this.

Is there some way that we can queue (rather than fail) the e2e tests when the Boskos pool is empty? Something like a max_concurrency for serverless functions?

**Comment by adrcunha** [comment]
@steuhs No. There are instructions about expanding the pool in the ci/prow dir README.
@evankanderson Sorry, there isn't. kubetest kinda interacts under the hood with boskos.

**Comment by chaodaiG** [comment]
The permission denied issue is becoming worse, it has failed at least latest 10 continuous runs in serving:
https://testgrid.knative.dev/knative-serving#continuous

**Comment by adrcunha** [comment]
As I mentioned in https://github.com/knative/test-infra/issues/638#issuecomment-477765004 the permission denied error is a red herring. I believe Stephen is working on expanding the boskos pool, hopefully that will solve (or at least alleviate) the problem.

**Comment by steuhs** [comment]
After 3 actions taken to solve this issue, this issue stopped occurring from 2019-04-01 10:36:10.000 PDT

1) expand boskos pool by adding 11 more projects #657
2) update boskos images #658
3) update flags passed to boskos janitor image #658

The problem is resolved after the last action is taken
