### ISSUE TITLE
Clearly show unit test failures due to race conditions

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#640]
Knative unit tests (and E2E too) run with `-race`. It can cause a test to fail, but it won't be shown as such in the test summary, causing confusion.

For example:

https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_serving/3537/pull-knative-serving-unit-tests/1111306561692635137/build-log.txt

![image](https://user-images.githubusercontent.com/35786489/55178173-201d6700-5142-11e9-8a5e-9ae4492d70ba.png)

Buried in the logs we find:

```
I0328 16:45:14.315] ==================
I0328 16:45:14.316] WARNING: DATA RACE
I0328 16:45:14.318] Read at 0x00c0005ee343 by goroutine 61:
I0328 16:45:14.318]   testing.(*common).logDepth()
I0328 16:45:14.318]       /usr/local/go/src/testing/testing.go:629 +0x132
I0328 16:45:14.318]   testing.(*common).Logf()
I0328 16:45:14.319]       /usr/local/go/src/testing/testing.go:614 +0x90
I0328 16:45:14.319]   testing.(*T).Logf()
...
I0328 16:45:14.423]   github.com/knative/serving/pkg/reconciler/v1alpha1/revision.TestGlobalResyncOnConfigMapUpdateRevision.func2()
I0328 16:45:14.423]       /go/src/github.com/knative/serving/pkg/reconciler/v1alpha1/revision/revision_test.go:620 +0x8e
I0328 16:45:14.423]   testing.tRunner()
I0328 16:45:14.424]       /usr/local/go/src/testing/testing.go:865 +0x163
...
```

However, the go test log reports the test as passing:

```
I0328 16:45:14.238] === RUN   TestGlobalResyncOnConfigMapUpdateRevision
I0328 16:45:14.239] === RUN   TestGlobalResyncOnConfigMapUpdateRevision/Update_LoggingURL
I0328 16:45:14.241] --- PASS: TestGlobalResyncOnConfigMapUpdateRevision (0.77s)
```

https://golang.org/doc/articles/race_detector.html doesn't show a way to force a test to fail on a race condition. `halt_on_error` might be an option if it properly logs the test as failed. Other option would be to detect the exit code, parse the log looking for the race detection stacktrace and produce a Junit XML file with the details.

**Comment by adrcunha** [comment]
This can be coupled with #428.

**Comment by jessiezcc** [comment]
this fits into test common code/infra project.
