### ISSUE TITLE
go test failed on knative-client in the new go coverage job

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#642]
https://prow.knative.dev/log?job=ci-knative-client-go-coverage&id=1111070508478107650

**Comment by srinivashegde86** [comment]
this seems to be running now - https://testgrid.knative.dev/knative-client#coverage

**Comment by adrcunha** [comment]
Logs GCS link is https://pantheon.corp.google.com/storage/browser/knative-prow/logs/ci-knative-client-go-coverage/1111070508478107650/?project=knative-tests
