### ISSUE TITLE
Create an artifacts dir for local testing

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#656]
We use the artifacts dir to store artifacts when running tests. But, when I run tests locally(not on prow), we dont have the env var ARTIFACTS set to the artifacts dir handled by prow. We need a way to create a dir and use that to store the artifacts. These are useful for debugging and/or verifying the test results.

**Comment by adrcunha** [comment]
I've seen the pattern "get artifacts dir; check if exists; create if not; fail if error" a few times in the codebase. This is a good candidate for refactoring/sharing, which will also simplify the resolution of this task.

**Comment by jessiezcc** [comment]
not a priority, but good to have

**Comment by Fredy-Z** [comment]
To add more background for this issue:
Currently when we run tests locally by using `go test` command, there is no standard and elegant way to export the test result as junit format `.xml` file like what `prow` does. 
Test cases like [this](https://github.com/knative/serving/blob/ce19a633478c7da01fec82826c11662364786be2/test/performance/observed_concurency_test.go#L209) explicitly create the file, but we want a more generic way to handle this.

**Comment by adrcunha** [comment]
What you're describing is a different issue. This issue is about a simple refactoring.
