### ISSUE TITLE
Unify Knative Testgrid CI dashboards for previous releases 

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#669]
https://github.com/knative/test-infra/pull/668 creates 3 new CI flows for release-0.5.

However, currently the Testgrid config generator creates one dashboard for each CI flow. It would be better if all flows could be a tab (serving, eventing and eventing-sources) in a single dashboard (knative-0.5), simplifying and unifying the results display.

**Comment by Fredy-Z** [comment]
/assign @Fredy-Z 

I can take this one and fix it together with the one assigned to me before.

**Comment by adrcunha** [comment]
Please update TestGrid.
