### ISSUE TITLE
Default Knative Serving installation function is broken

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#674]
https://github.com/knative/serving/pull/3353 updated Knative Serving to use Istio 1.1.1, and that required a small change in the way Istio CRDs are installed.

However, the PR above didn't update the standard Knative Serving installation function, used by all the other repos to bring up the SUT (https://github.com/knative/test-infra/blob/0125a23e5d1edb5e2b6f27b9b5a30a3965d6319e/scripts/library.sh#L302)

https://github.com/knative/test-infra/pull/672 updates the function above. This now needs to be replicated to the other repos, in order to unbreak their integration and CI tests.

/assign @nbarthwal

**Comment by adrcunha** [comment]
Filed https://github.com/knative/test-infra/issues/675 for pursuing a long-term solution and preventing this from reoccurring.

**Comment by adrcunha** [comment]
@tcnghia FYI

**Comment by adrcunha** [comment]
Also, when serving gets test-infra update, the copy of wait_until_batch_job_complete() in e2e-common.sh can be removed.

**Comment by nbarthwal** [comment]
ok
