### ISSUE TITLE
Couple Istio and Knative installation between test-infra and serving

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#675]
knative/serving has its own serving installation function (https://github.com/knative/serving/blob/b5ae99b62303ff31437ba49b7fe48a664a74bdae/test/e2e-common.sh#L123), while all other repos use a standard function from knative/test-infra (https://github.com/knative/test-infra/blob/0125a23e5d1edb5e2b6f27b9b5a30a3965d6319e/scripts/library.sh#L302).

If these two functions are out-of-sync, updates to knative/serving might block E2E tests (presubmits and CI) in all the other repos (e.g., https://github.com/knative/test-infra/issues/674).

**Comment by adrcunha** [comment]
One simple (short-term?) solution would be adding an extra E2E test to serving that uses the function in library.sh to bring up serving.

**Comment by jessiezcc** [comment]
Pls sync up with @adrcunha on short term vs long term preference.

**Comment by adrcunha** [comment]
With Knative Serving 0.6 this is now obsolete, as installing it is now a single yaml. Closing as obsolete.
