### ISSUE TITLE
Use --force and maybe --grace_period=0 when deleting resources with kubectl

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#676]
There have been multiple instances of pods getting stuck during delete. We should be using --force and --grace_period flags with `kubectl delete` so that we dont wait around a long time and delete the pods without waiting and forcefully, if needed.

`kubectl delete pod --grace-period=0 --force --namespace <NAMESPACE> <PODNAME>`

**Comment by adrcunha** [comment]
Apart from 3641, looks like only build is using a similar approach in scripts:

```
$ grep -r "kubectl delete pod" .
./docs/eventing/samples/kubernetes-event-source/README.md:kubectl delete pod busybox
./eventing-sources/samples/kubernetes-event-source/README.md:kubectl delete pods busybox
$ grep -r "kubectl delete " . | grep -v ".md:" | grep -v "^./serving/"
./build/test/e2e-common.sh:  kubectl delete --ignore-not-found=true builds.build.knative.dev --all
./build/test/e2e-common.sh:  kubectl delete --ignore-not-found=true buildtemplates --all
```
