### ISSUE TITLE
Prow should report to github when tests finishes

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#682]
Currently, we report tests are done, once when the scripts are done running. This includes creating everything, running tests and deleting all the created objects.

We should report to github once the tests are done running and delete the associated resources in parallel. So, github does not have to wait the additional few minutes that takes.

**Comment by jessiezcc** [comment]
According to @adrcunha, github will only take the signal of job being completed, and we are not doing resources cleanup anymore.
