### ISSUE TITLE
Automate Prow components versions bumping

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#689]
Current process of updating Prow components versions is manual, which is time consuming and error prone. Automating the versions bumping can make this process more resilient and we always get latest features and fixes. 
We might be able to borrow from automating script in Kubernetes/test-infra repo:
https://github.com/kubernetes/test-infra/blob/0f376b4ea70b4d3d8f51c622158a623fee2e9744/prow/autobump.sh

**Comment by adrcunha** [comment]
Synced with the k8s team about this. We should only automatically bump our components version up to the one used by prow.k8s.io, which is safe.

**Comment by dushyanthsc** [comment]
We would be taking a look at this in Q3 (Jul - Sept)

**Comment by adrcunha** [comment]
Note: autobump.sh was replaced by experiment/autobumper. See https://github.com/kubernetes/test-infra/pull/12471

**Comment by chaodaiG** [comment]
Kubernetes is updating Prow version almost daily now: https://github.com/kubernetes/test-infra/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+label%3Aarea%2Fprow%2Fbump+

So if we choose to use the same version as Kubernetes, it's not too much different from using latest Prow version. An idea of getting a tested version is going through kubernetes/test-infra PR history, and pick a PR  with `area/prow/bump` label that is roughly one week old,  merged and was not reverted later

**Comment by adrcunha** [comment]
Fejta mentioned something about test-infra updating frequently and being the "staging" version, while k8s would update less frequently, on stable versions. Maybe that's what he was referring to? We should get confirmation from the k8s team before proceeding.

**Comment by chaodaiG** [comment]
Just checked with @cjwagner , the entire kubernetes org is managed by a single Prow instance.

**Comment by adrcunha** [comment]
Thanks. +1 for the ideas of using a slightly older, not rolled-back version.

**Comment by chaodaiG** [comment]
This is done after #1057 merged
/close
