### ISSUE TITLE
Consider using Sonobuoy for integration/performance tests

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#690]
From https://github.com/heptio/sonobuoy :

Sonobuoy is a diagnostic tool that makes it easier to understand the state of a Kubernetes cluster by running a set of Kubernetes conformance tests in an accessible and non-destructive manner.

**Comment by chizhg** [comment]
Since we don't control the roadmaps for Sonobuoy, and it does not really help as it has some caveats based on the discussion with GKE team, so we are not going to consider using it.

/close
