### ISSUE TITLE
Consider creating staging Prow cluster for testing test-infra changes

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#691]
Currently there is not really a good way for testing some of the changes related to Prow before hitting errors in production. For example: Prow cluster config change, plugins updates, and bots.

We can reduce the risk of these breakages by setting up a staging Prow cluster, by mirroring production Prow cluster, on which we can enable auto config updates, enable automatic testing, and even create release pipeline for updating Prow in production.

**Comment by adrcunha** [comment]
Having a staging Prow would indeed help catching any config errors that could be missed by the validators. However, simply duplicating the cluster/config won't work, as it would run the jobs twice. Thus we need a more thoughtful approach for this. My first question would be: what's the approach the k8s team uses?

**Comment by adrcunha** [comment]
Synced up with k8s team about this. There's no staging Prow, but they use test-infra as canary before upgrading prow.k8s.io. Regarding component upgrades, we can just follow whatever prow.k8s.io is using and we should be safe.

A staging Prow would involve more work (which is in the roadmap of the k8s team), like customizing webhooks, setting test repos, etc.

That being said, I'm closing this issue as it's a non trivial amount of work with lower value than #689.

**Comment by chaodaiG** [comment]
Agreed
