### ISSUE TITLE
Dont use latest k8s version when creating cluster

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#694]
Can we use the second latest version of k8s to run our e2e tests? When we use latest, we will always have flakiness during GKE rollouts causing retests. If this happens during our periodic job runs, we will have to wait till the next run or mauallykick off another run, which again is not guaranteed to pass. 

We should probably use the previous latest version, which is guaranteed to be supported since it supports atleast 3 versions

zone-1 supported versions -> N-2, N-1, N
zone-2 supported versions -> N-1, N, N+1

So, if we pick N or N-1, we should be able to create the cluster. Currently, we are picking N+1(latest) and trying to create the cluster, which does not work if we hit zone-1

Similar to https://github.com/knative/test-infra/issues/108

**Comment by adrcunha** [comment]
Not using latest might be finally an option. We have been using latest because during Knative development many features required the bleeding edge k8s.

This would require some coding though, as the version selection is done by kubetest. There's prior art in e2e-tests.sh for querying and selecting the k8s version.

So, choosing the not latest k8s version in a region means we would be usually using N-1, and during rollouts, occasionally N (where N is the current latest stable version, available everywhere).

@mattmoor wdyt?

**Comment by srinivashegde86** [comment]
`gcloud container get-server-config --region=us-central1 --format="flattened(validMasterVersions)"` gives the list of valid master versions for a region and we can pick the second to latest from this

**Comment by adrcunha** [comment]
Yes, that's what my code was doing (which I called "prior art").

**Comment by adrcunha** [comment]
Note that how to select the k8s version is not the real issue here, but to ensure proper testing environment for Knative.

**Comment by srinivashegde86** [comment]
sg. I was playing with `--format` to see how to get this information :D 

Agreed. If we need to always test with latest, we may need to live with the occassional flakiness based on the rollout cadence 🤷‍♂️

**Comment by adrcunha** [comment]
> If we need to always test with latest, we may need to live with the occassional flakiness based on the
> rollout cadence 🤷‍♂️

Actually it just occurred to me that Chao's PR for stockout handling can also be used to detect when a cluster couldn't be created because a k8s version isn't available; it would then retry with a previous version. Of course, this only applies if we *must* test against latest k8s.

**Comment by adrcunha** [comment]
The error message when creating a cluster with a version not available yet is:

```
W0910 17:57:41.758] ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.10.7" found.
```

**Comment by adrcunha** [comment]
Currently we run the tests against `gke-latest`. There's no need to retry with a previous version, as kubetest will fetch the latest version again when retrying to create the cluster.
