### ISSUE TITLE
Presubmit tests are still run when there is no code change

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#704]
According to the intention of our test scripts, integration tests should not be run if there is only documentation change. 
But currently it's not the case:
https://github.com/knative/docs/pull/1225
https://github.com/knative/eventing/pull/1015

**Comment by adrcunha** [comment]
In 1225 the script knows that only a .md file was changed, e.g

```
I0423 19:25:11.650] Changed files in commit b04b9f28a8db64b4283fea7e1c02c846360bb987:
I0423 19:25:11.650] docs/eventing/samples/iot-core/README.md
```

However, it's still running the tests.

**Comment by adrcunha** [comment]
@Fredy-Z can you please update the other repos now that the fix is on?
/assign @Fredy-Z

**Comment by Fredy-Z** [comment]
Done.
