### ISSUE TITLE
Enable PR status on Prow

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#709]
Instructions are in https://github.com/kubernetes/test-infra/blob/master/prow/docs/pr_status_setup.md

**Comment by adrcunha** [comment]
PR status enabled in https://prow.knative.dev/pr

**Comment by Fredy-Z** [comment]
/cc @Fredy-Z 
I can take this issue if no one is working on it.

**Comment by dushyanthsc** [comment]
Thanks for picking it up @Fredy-Z.

/unassign @dushyanthsc

**Comment by adrcunha** [comment]
@Fredy-Z please ensure you're in sync with the current oncall whenever you make changes to our Prow cluster.
