### ISSUE TITLE
Switch to Spyglass

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#710]
But keep Gubernator for the PR dashboard, as it's used by many developers.

**Comment by adrcunha** [comment]
Spyglass config in prow.k8s.io is in https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L27

**Comment by Fredy-Z** [comment]
/assign @Fredy-Z 
I can take this issue if no one is working on it.

**Comment by dushyanthsc** [comment]
@Fredy-Z thanks. Lets talk through these when you start working on it.

/unassign @dushyanthsc

**Comment by adrcunha** [comment]
Thanks, Chi. Since this is more complex than enabling PR status, I suggest you work on that first.

**Comment by adrcunha** [comment]
Due to #981, we have to increase the priority of this issue.
