### ISSUE TITLE
Integrate observability repo onto testgrid

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#711]
The repo has been made public, it's necessary for this repo to be surfaced on knative testgrid.

**Comment by adrcunha** [comment]
1. Update the vendored test-infra dir and the presubmit/e2e script on the repo.
2. Create the pre/post submit jobs, together with the Testgrid tabs.

**Comment by adrcunha** [comment]
1 was fixed by https://github.com/knative/observability/pull/24

/close
