### ISSUE TITLE
Handle server side errors better in releases

### ISSUE THREAD

**Issue by ericKlawitter** [knative/test-infra#713]
Currently, releases fail if we receive a server side error, e.g. a 502 from the GitHub server when attempting to upload the release to GitHub. 

This happened with serving [release 0.5.2](https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-dot-release/1120613746985668608), when a 502 caused the release to fail. We should add some retry logic so that the release script can overcome this types of issue.

**Comment by adrcunha** [comment]
Nikhil left the team, assigning this issue to me.
/assign adrcunha
/unassign nbarthwal
