### ISSUE TITLE
Rename and reorganize TestGrid tab names

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#715]
* dashboards don't have to start with "knative-"
* "conformance-tests" can be just "conformance"

Possibly related:
* all periodic job names start with "ci-", maybe use different prefixes for different jobs (e.g., "nightly")
* PRs like 705 introduce long names, maybe shorten them to keep readability

**Comment by Fredy-Z** [comment]
Do you have suggestion for shortening the name like `ci-knative-serving-istio-1.1.2-no-mesh` and `ci-knative-serving-istio-1.0.7-mesh`? How about `ci-serving-istio-1.1.2` and `ci-serving-istio-1.0.7-mesh`?

**Comment by adrcunha** [comment]
I like that. I think "no-mesh" could become "nomesh" to keep "-" as word separators. Depending on what's the default for mesh, we can drop one or the other (so it would be `ci-serving-istio-1.1.2-nomesh` or `ci-serving-istio-1.1.2-mesh`). Nghia probably knows best.

**Comment by Fredy-Z** [comment]
I asked Kenny and he said the default is mesh, but that might change in the future. So I think it's better to keep both for now.

**Comment by adrcunha** [comment]
On second thought, let's not change the names of the buckets, only Testgrid.
