### ISSUE TITLE
Auto retest PRs that failed flaky tests

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#716]
Currently, when a PR encountered flaky tests failure in presubmit test, PR authors need to manually add  `/retest` in PR comment to help PR merge. This is time consuming and often delays the integration of a PR, it's also sometimes not that obvious whether the tests failed in a PR are really flaky or not.

Now that we collect data for discovering active flaky tests in #132 , we can automate the process of retest by using the same data, for reducing PR turn around time.

**Comment by adrcunha** [comment]
/assign @chaodaiG 

Let's think about getting an intern for working on this and other improvements over flaky tests.

**Comment by chaodaiG** [comment]
@adrcunha , That's exactly what I'm considering about this work. Let's plan on it

**Comment by dushyanthsc** [comment]
We would be taking a look at this in Q3 (Jul - Sept)

**Comment by chaodaiG** [comment]
It's delivered and running as a tool named flaky-test-retryer
Thanks for @TrevorFarrelly  for all the hard works

/close
