### ISSUE TITLE
Create a CI flow with Minikube

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#717]
Although you currently can't run Minikube on a Prow job, we should investigate a way to have a CI flow to exercise it.

**Comment by adrcunha** [comment]
A simple way of doing this can be running the test inside a VM. Such VM could be one of the GCP projects from the boskos pool (we can use kubetest for the lease part, without bringing up a cluster).

**Comment by fejta** [comment]
I assume you already looked into kind?

**Comment by adrcunha** [comment]
If the above approach is feasible, this could be even used for building/testing Knative Client on Windows (unsure about OS X).

**Comment by dushyanthsc** [comment]
Q3 (Jul - Sept)
