### ISSUE TITLE
Tool for updating test-infra in other repos

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#733]
Currently for updating test-infra in other repos, the following steps are performed:

1. Navigate to a repo
1. Check out a new branch
1. Run `dep ensure -update github.com/knative/test-infra` and `./hack/update-deps.sh`
1. Run `git commit` and `git push`
1. Go to UI, Create Pull Request
1. Repeat step 1 - 5 for all repos

We have done this ~20 times since 2019, but not in all repos every time, ideally test-infra should be updated at the same time. 

Proposing a tool for updating test-infra in other repos, which does every steps mentioned above.

**Comment by adrcunha** [comment]
I don't think it's worth writing a complex tool for that. We can have a simple bash script to automate most of the steps. Also, please notice that updating test-infra might cause conflicts with other updates, so a human keeping an eye on the process is a good thing.

Assigning to Nikhil for priority, but IMO it should be low.

/assign @nbarthwal

**Comment by chaodaiG** [comment]
Agree with bash script, that's also what was in my mind. This tool should only do things up to Pull Request step, and the user who kicks off the process still need to manually go into every PR to make sure they are correct
