### ISSUE TITLE
Setup cross-platform testing support for knative/client

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#746]
### Problem statement and requirements

Testing on Linux is easy, since Prow runs on Linux. OS X and Windows require a different solution.

E2E tests must (also) run against public Knative builds (nightly, versioned).

E2E tests must run against multiple versions of Knative (must define which later).

Expanding the E2E tests can be done by the developers. Currently there’s only a smoke test, and sixolet can write an initial go test that can be used as a template for other tests.

### Open questions

* How to integrate that?
* Can we emulate them on a container, like Wine (since there’s no GUI involved)?
* How kubectl does that?
* Can we learn/reuse the solution?
* OS X: Can we use Circle CI?
* Windows: Can we use Azure Pipelines?

/assign @dushyanthsc

**Comment by dushyanthsc** [comment]
We would be evaluating this issue in July-Sept time-frame.
