### ISSUE TITLE
knative observability continous runs are failing

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#749]
https://testgrid.knative.dev/knative-observability#continuous

error:
W0508 21:31:20.679] ./test/presubmit-tests.sh: line 21: ./test/../vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh: No such file or directory
W0508 21:31:20.681] ./test/presubmit-tests.sh: line 46: main: command not found

this repo uses go modules and not dep like other knative repos. Not sure if this has something to do with it.

**Comment by srinivashegde86** [comment]
it uses gitmodules for vendoring - https://github.com/srinivashegde86/observability/blob/master/.gitmodules

```
$ ls ./test/../vendor/github.com/knative/test-infra/
$
```

**Comment by srinivashegde86** [comment]
related issue for using dep on the observability repo - https://github.com/knative/observability/issues/5

**Comment by adrcunha** [comment]
As I mentioned in #5, the solution is to vendor just test-infra, like Knative/client did.
