### ISSUE TITLE
Prow contains hardcoded links to kubernetes

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#75]
Although this is not Knative-specific, would be nice to get it fixed.

Prow contains several places where kubernetes is hardcoded. For example, the default reply from Prow robot about an approval contains links to Kubernetes documentation like https://go.k8s.io/bot-commands and https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process. See https://github.com/knative/test-infra/pull/73#issuecomment-412289662 as an example.

**Comment by jessiezcc** [comment]
closing due to low priority.
