### ISSUE TITLE
Google CLA bot issues

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#770]
## Expected Behavior

No bot issues. :)

## Actual Behavior

We've seen PRs where the bot complains that the CLA was not signed (even though it was before), like in https://github.com/knative/serving/pull/1435; or where a PR created with pair programming like in https://github.com/knative/serving/pull/1390 or https://github.com/knative/serving/pull/1352.

## Steps to Reproduce the Problem

  1. Creating a PR with two different commiters is probably the easiest way to reproduce.

## Additional Info

For https://github.com/knative/serving/pull/1352, an adming was able to solve the problem by temporarily disabling and then re-enabling a setting about admins being able to edit PRs.

**Comment by Benjamintf1** [comment]
Any update?

**Comment by adrcunha** [comment]
In some cases you the issue can be fixed by adding the "cla: yes" or "cla: no" labels to override the bot (mind the space).

**Comment by adrcunha** [comment]
**Note**

I'm keeping this issue open to report any updates that might appear regarding this issue. This issue is being handled by a different team at Google, not me, and the solution is not trivial. I'll post any relevant updates here, as soon as I'm notified about them.

**Comment by adrcunha** [comment]
googlebot now understands the author explicit consent. The author must add the comment

```@googlebot I consent.```

to explicit state that.

Closing this as the problem should now be fixed, please reopen if not.

**Comment by adrcunha** [comment]
Closed
