### ISSUE TITLE
The coverage report does not report on files that has no corresponding *_test.go files

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#79]
The go coverage report only looks at files that have *_test.go files. This provides wrong coverage outputs and also bumps up the coverage numbers. It is not reflective of the current state.

go test does specify that the package has no test files and we should capture this behaviour in our report.

For eg. in knative/pkg/test, we have some go files but no _test files.
knative/pkg/test$ go test
? github.com/knative/pkg/test	[no test files]

**Comment by steuhs** [comment]
Do we really want to include the data from source files without corresponding _test.go? I think our consensus was to ignore them
In terms of reporting, what do you think the report would look like if we are to include those files? @srinivashegde86

**Comment by steuhs** [comment]
fixed by the last two commits here: https://github.com/steuhs/test-infra/commits/re-org
