### ISSUE TITLE
Prow stopped working

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#801]
Expected:
Prow works as normal

Actual:
Prow doesn't schedule presubmit jobs for PR
https://github.com/knative/test-infra/pull/800
Prow doesn't update status with finished job
https://prow.knative.dev/

Additional info:
Tide status is not available: https://prow.knative.dev/tide

**Comment by chaodaiG** [comment]
`kubectl cluster-info dump` got following errors:
{"component":"plank","error":"error listing prow jobs: json: cannot unmarshal string into Go struct field DecorationConfig.grace_period of type time.Duration","level":"error","msg":"Error syncing.","time":"2019-05-18T01:49:03Z"}
{"component":"tide","error":"v1.ProwJobList.Items: []v1.ProwJob: v1.ProwJob.Spec: v1.ProwJobSpec.DecorationConfig: v1.DecorationConfig.GracePeriod: readUint64: unexpected character: \ufffd, error found in #10 byte of ...|_period\":\"15s\",\"time|..., bigger context ...|redentials_secret\":\"test-account\",\"grace_period\":\"15s\",\"timeout\":\"2h0m0s\",\"utility_images\":{\"clonere|...","level":"error","msg":"Error syncing.","time":"2019-05-18T01:48:14Z"}

There might be more

**Comment by chaodaiG** [comment]
@cjwagner in case you have seen something similar

**Comment by adrcunha** [comment]
Investigated with Chao. Looks like `mkpj` created an unparseable config for our Prow cluster, with entries like "grace_period: 15s", "timeout: 2h0m0s" and the previous working configs were "grace_period: 15000000000" and "timeout: 7200000000000".

It's possible that a new mkpj (which renders time values as human-readable strings) was used to generate a config for our Prow cluster (which is running v20190415-c700e7878).

**Comment by adrcunha** [comment]
Updating Prow to the latest version (https://github.com/knative/test-infra/pull/802) fixes the issue, which confirms the hypothesis above.

**Comment by adrcunha** [comment]
Prioritizing addressing #689 would help avoiding this kind of situation.

**Comment by stevekuznetsov** [comment]
This is caused by using a `mkpj` of newer version than `plank`. Please upgrade `plank` and/or use an older `mkpj` and delete the offending ProwJobs

**Comment by adrcunha** [comment]
The problem mentioned above was fixed. The idea if this issue is to prevent any kind of similar issue (config mismatch or bad configs) to cause Prow stop working.
