### ISSUE TITLE
Evaluate changing terminal text or background color based on kubecfg context

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#806]
When working on crucial kubernetes cluster(s), i.e. knative-prow, it will be pretty helpful if the terminal text/background clearly indicates that. For example, `knative-prow` as red text in terminal

**Comment by adrcunha** [comment]
This looks like a simple bash prompt tweak rather than a knative/test-infra issue to me.

**Comment by adrcunha** [comment]
Since bash prompts are pretty personal, I prefer leaving a link to a ready-to-use solution for showing the current context in your prompt. It can be easily adapted to show specific contexts in a different color.

https://pracucci.com/display-the-current-kubelet-context-in-the-bash-prompt.html
