### ISSUE TITLE
Use role based account for managing knative-tests project

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#807]
Restrict personal account with admin privilege on knative-tests project, and use role based account instead. This can help preventing a developer from switching freely to knative-tests with admin rights

**Comment by adrcunha** [comment]
https://cloud.google.com/iam/docs/creating-custom-roles

**Comment by chaodaiG** [comment]
Minimum permissions needed for Prow admins:
- All permissions of "Viewer" role
- container.clusters.create
- container.clusters.update
- container.thirdPartyObjects.create
- container.thirdPartyObjects.delete
- container.thirdPartyObjects.update
- container.configMaps.update
