### ISSUE TITLE
Error happens occasionally when installing the nightly serving release

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#829]
Not sure if it's an infra issue. Add it here now for record.

Detailed log: https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_test-infra/828/pull-knative-test-infra-integration-tests/1133108957661892608/
```
I0527 20:38:13.477] Installing Serving from https://storage.googleapis.com/knative-nightly/serving/latest/serving.yaml
I0527 20:38:13.937] namespace/knative-serving created
I0527 20:38:13.958] clusterrole.rbac.authorization.k8s.io/knative-serving-certmanager created
I0527 20:38:13.977] clusterrole.rbac.authorization.k8s.io/knative-serving-istio created
I0527 20:38:14.001] clusterrole.rbac.authorization.k8s.io/knative-serving-admin created
I0527 20:38:14.025] clusterrole.rbac.authorization.k8s.io/knative-serving-core created
I0527 20:38:14.082] serviceaccount/controller created
I0527 20:38:14.103] clusterrolebinding.rbac.authorization.k8s.io/knative-serving-controller-admin created
I0527 20:38:14.347] customresourcedefinition.apiextensions.k8s.io/certificates.networking.internal.knative.dev created
I0527 20:38:14.377] customresourcedefinition.apiextensions.k8s.io/clusteringresses.networking.internal.knative.dev created
I0527 20:38:14.407] customresourcedefinition.apiextensions.k8s.io/configurations.serving.knative.dev created
I0527 20:38:14.442] customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev created
I0527 20:38:14.480] customresourcedefinition.apiextensions.k8s.io/podautoscalers.autoscaling.internal.knative.dev created
I0527 20:38:14.516] customresourcedefinition.apiextensions.k8s.io/revisions.serving.knative.dev created
I0527 20:38:14.545] customresourcedefinition.apiextensions.k8s.io/routes.serving.knative.dev created
I0527 20:38:14.578] customresourcedefinition.apiextensions.k8s.io/services.serving.knative.dev created
I0527 20:38:14.615] customresourcedefinition.apiextensions.k8s.io/serverlessservices.networking.internal.knative.dev created
I0527 20:38:14.659] service/activator-service created
I0527 20:38:14.690] service/controller created
I0527 20:38:14.728] service/webhook created
I0527 20:38:14.771] deployment.apps/activator created
I0527 20:38:14.811] service/autoscaler created
I0527 20:38:14.840] deployment.apps/autoscaler created
I0527 20:38:14.874] configmap/config-autoscaler created
I0527 20:38:14.899] configmap/config-certmanager created
I0527 20:38:14.923] configmap/config-defaults created
I0527 20:38:14.949] configmap/config-deployment created
I0527 20:38:14.974] configmap/config-domain created
I0527 20:38:14.996] configmap/config-gc created
I0527 20:38:15.019] configmap/config-istio created
I0527 20:38:15.046] configmap/config-logging created
I0527 20:38:15.077] configmap/config-network created
I0527 20:38:15.105] configmap/config-observability created
I0527 20:38:15.127] configmap/config-tracing created
I0527 20:38:15.151] deployment.apps/controller created
I0527 20:38:15.177] deployment.apps/networking-certmanager created
I0527 20:38:15.209] deployment.apps/networking-istio created
I0527 20:38:15.238] deployment.apps/webhook created
I0527 20:38:15.238] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/serving.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
I0527 20:38:15.239] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/serving.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
I0527 20:38:15.239] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
```

**Comment by adrcunha** [comment]
It seems that it's complaining about Istio CRDs not ready? Maybe it's because it's expecting stuff from a Istio version newer than what's installed by the add-on?

**Comment by adrcunha** [comment]
Also, some time ago we had race conditions regarding the creation of Istio CRDs that resulted in error messages similar to the ones above when installing knative/serving. They manual workaround was to simply `kubectl apply` the yaml again after a few seconds (when hopefully the CRDs were already created). If memory serves me well, for Istio someone (Nghia, I think) added a patch/hack to wait for the CRDs to be created before continuing.

**Comment by chaodaiG** [comment]
Under test-infra, this only happened for PR 828 and PR 830 so far

**Comment by chaodaiG** [comment]
It's actually failing a bunch of stuff, at least client, eventing-sources, docs are affected. While serving and eventing are not affected, and they don't rely on GKE Istio Addon

**Comment by Fredy-Z** [comment]
/assign @yt3liu 
Assigning to Joyce since she's oncall :-)

**Comment by yt3liu** [comment]
For the intermittent error from "caching.internal.knative.dev/v1alpha1", since the image definition is also part of knative-serving, the wait solution will not work. 

```
I0527 20:38:15.239] unable to recognize "https://storage.googleapis.com/knative-nightly/serving/latest/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
```

The next step is to add the re-try `kubectl apply` after it fails for the first time.

**Comment by adrcunha** [comment]
> The next step is to add the re-try `kubectl apply` after it fails for the first time.

I believe you're talking about https://github.com/knative/test-infra/blob/beeb6309cd1b885279e326b38d1f015739ea3c0d/scripts/library.sh#L335

If so:
* this should be a short-term solution\
* beyond the long-term solution we should have a way to avoid this kind of situation to happen again
* this should be in sync with the official instructions on how to install Knative ("got an error, retry" is a bad UX)
* this is not strictly test-infra stuff, don't keep the burden only on yourself, relevant devs should be involved

**Comment by Fredy-Z** [comment]
Link the Serving issue for tracking:
https://github.com/knative/serving/issues/4176

**Comment by adrcunha** [comment]
The proper way (as in "no race conditions") of installing Knative Serving is documented in https://knative.dev/docs/install/knative-with-gke/

Basically it says the install is a 2-step process now:

```
kubectl apply --selector knative.dev/crd-install=true --filename serving.yaml
kubectl apply --filename serving.yaml
```

**Comment by adrcunha** [comment]
Note that the documentation doesn't say there must be a wait between both commands, so I assume the CRDs are ready once the first command finishes.

**Comment by yt3liu** [comment]
The retry logic is propagated to other repos and the problem is triaged. The install knative serving in two steps as suggested by serving team will go out in the next upgrade of test-infra in other repos.
