### ISSUE TITLE
Gubernator links to github.com/knative/knative_eventing

### ISSUE THREAD

**Issue by grantr** [knative/test-infra#84]
In https://gubernator.knative.dev/pr/knative_eventing/376, the links to the eventing repo are https://github.com/knative/knative_eventing, but they should be https://github.com/knative/eventing.

**Comment by adrcunha** [comment]
I don't think it's worth working on this. Gubernator is deprecated, replaced by Spyglass. Better spend the effort on https://github.com/knative/test-infra/issues/710 (switching from Gubernator to Spyglass).
