### ISSUE TITLE
Update Mail dependencies in monitoring k8s app

### ISSUE THREAD

**Issue by yt3liu** [knative/test-infra#841]
Currently the cloud mail dependencies is not available through `go get`. Once it is available, fetch the dependencies through go get and remove the current solution to fetch the dependencies (hack).

**Comment by adrcunha** [comment]
/assign @srinivashegde86 

Assigning to Srinivas so he can prioritize accordingly.

**Comment by srinivashegde86** [comment]
We are not using cloud mail anymore. Closing this
