### ISSUE TITLE
Add /want-lgtm to Prow

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#866]
Sometimes you want multiple reviewers to weigh in before a change is merged, but Prow always merges as soon as the minimum set is satisfied (AFAIK).

Internally, we have the concept of `WANT_LGTM` to enumerate those you want an `/lgtm` from before merging a change.  I feel like such a concept would be useful in Prow as well.

e.g. I'd like to write:
```
/want-lgtm @fejta
/want-lgtm @cjwagner
```

To have `tide` block merges until both have given the `/lgtm`, this should also implicitly `/assign` them.

I think it would also be useful to have `/want-lgtm all` that waits for `/lgtm` from all assigned reviewers.

cc @cjwagner @fejta @grantr @adrcunha @jessiezcc WDYT?

**Comment by adrcunha** [comment]
This is basically https://github.com/kubernetes/test-infra/issues/6014

The conclusion in that issue (which was closed) is that "use `/hold` to wait ... it's working fine as a socially enforced process and not worth codifying" https://github.com/kubernetes/test-infra/issues/6014#issuecomment-352950594, as suggested by Fejta [above](https://github.com/knative/test-infra/issues/866#issuecomment-397349632).
