### ISSUE TITLE
Make conformance and e2e test images public

### ISSUE THREAD

**Issue by bobcatfish** [knative/test-infra#867]
/area test-and-release
/kind dev

## Expected Behavior
There is no reason folks should have to build and push the [e2e images]() and [conformance test images]() whenever they want to run the tests, the images hardly ever change and they don't do much. They should be available publicly so folks can get up and running with the tests faster, and they should be regularly updated.

Note this will have to play nicely with a person's `$DOCKER_REPO_OVERRIDE`.

## Actual Behavior
The tests expect anyone running the e2e or conformance tests [to have built and pushed the images to their own repo](https://github.com/elafros/elafros/tree/master/test#building-the-test-images).

## Steps to Reproduce the Problem
n/a

## Additional Info
Thanks @jonjohnsonjr !

**Comment by adrcunha** [comment]
Ideally the images would be automagically rebuilt once their code or dependencies change.

**Comment by adrcunha** [comment]
https://github.com/knative/serving/issues/4263 is a superset of this issue, closing.
