### ISSUE TITLE
How to run e2e tests against vanilla k8s (minikube / other k8s cluster)?

### ISSUE THREAD

**Issue by houshengbo** [knative/test-infra#889]
Question 1: Do we support any other kube clusters on other platforms, except GKE?
Question 2: Do we support running e2e tests against existing kube cluster, without installing kube cluster again?

**Comment by srinivashegde86** [comment]
You can run the e2e tests against any K8S cluster with knative installed - https://github.com/knative/serving/blob/master/test/README.md#running-end-to-end-tests

**Comment by houshengbo** [comment]
@srinivashegde86 Thanks, but that is not enough. 
I mean running the script ./test/e2e-tests.sh.

**Comment by srinivashegde86** [comment]
Yes, you can use the `--run-tests` flag to run the tests with the script. You will need to set KO_DOCKER_REPO and kubeconfig to the registry and the cluster you want to use.

Different flags with the script:
https://github.com/knative/test-infra/blob/d1bb39bbca6e8d5b7d84410bcae0e3fc74747081/scripts/README.md#using-the-e2e-testssh-helper-script

Excerpt from the README:
`Calling your script with --run-tests and the variable KO_DOCKER_REPO set will immediately start the tests against the cluster currently configured for kubectl.`

**Comment by adrcunha** [comment]
Closing, since it was answered.
