### ISSUE TITLE
serving/istio* tests are not running since 7 Jun

### ISSUE THREAD

**Issue by coryrc** [knative/test-infra#890]
https://testgrid.knative.dev/serving#istio-1.0.7-no-mesh

I am investigating.

**Comment by chaodaiG** [comment]
The jobs actually ran, they are not showing on testgrid. For example:
https://prow.knative.dev/?job=ci-knative-serving-istio-1.0.7-mesh

**Comment by adrcunha** [comment]
Testgrid was stuck, restarting it solved the problem.
