### ISSUE TITLE
Support of other container registries like docker.io and quay.io

### ISSUE THREAD

**Issue by houshengbo** [knative/test-infra#895]
KO_DOCKER_REPO is key env var for knative. Modules like Knative serving have already supported other container registry, like docker hub to push and pull the images.

If we configure KO_DOCKER_REPO with a value for docker.io or quay.io registry, some images will fail to be pushed, since these registries do not support nested image names, like github.com/<folder>/<folder>/Image_name. They only support one layer of name, like Image_name.

Shall we extend our support of container registry to services, other than google container registry? 

We can implement a verification: if the KO_DOCKER_REPO is a google container registry, nothing change; if KO_DOCKER_REPO is other image registry, we use the short version of the image name.

**Comment by adrcunha** [comment]
Where exactly support to other registries should be added? To the release script? Where knative/serving added support to other registries (so far I didn't find anything in the /hack and /test dirs)?

**Comment by houshengbo** [comment]
@adrcunha This should be an issue for knative serving again. In https://github.com/knative/serving/blob/master/hack/generate-yamls.sh#L75,

ko resolve ${KO_YAML_FLAGS} -f config/ | "${LABEL_YAML_CMD[@]}" > "${SERVING_YAML}"

KO_YAML_FLAGS is set to -P for full name, but if it is docker hub or other registry, we should use -B for KO_YAML_FLAGS to pick up the short name.
