### ISSUE TITLE
Allow the version of the Knative installation be configurable

### ISSUE THREAD

**Issue by rhuss** [knative/test-infra#897]
In https://github.com/knative/client/pull/170/files we are trying to establish E2E tests which tests against various version of Knative serving. Therefore we need to be able to parameterize the version of Knative to install in the E2E setup, but unfortunately the version in https://github.com/knative/client/blob/0d9494736616aa21e8a45da443cbc7a0a922ca7f/vendor/github.com/knative/test-infra/scripts/library.sh#L506 is currently hardcoded and not overwritable.

For a quick win it would be enough to allow this env variable to be overwritable, but for long term it would be much neither if the overall test could be parameterized with the Knative version to used for the tests)

**Comment by houshengbo** [comment]
I root for this. 
/assign @houshengbo
