### ISSUE TITLE
If no argument is specified, when calling e2e-tests.sh, how does knative serving get installed?

### ISSUE THREAD

**Issue by houshengbo** [knative/test-infra#916]
Does the  “function create_test_cluster()” call the “function knative_setup” in knative/test-infra/scripts/e2e-tests.sh(when --run-tests is not specified)? I only found “function setup_test_cluster” calls “function knative_setup”(when --run-tests is specified). 
In general, if we do not specify --run-tests, how do we make sure “function knative_setup” is called to set up the knative?

**Comment by adrcunha** [comment]
> Does the “function create_test_cluster()” call the “function knative_setup” in knative/test-
> infra/scripts/e2e-tests.sh(when --run-tests is not specified)?

No, because it's not called when you pass --run-tests.

> I only found “function setup_test_cluster” calls “function knative_setup”(when --run-tests is specified).

Yes, that's correct.

> In general, if we do not specify --run-tests, how do we make sure “function knative_setup” is called to
> set up the knative?

setup_test_cluster() is called after create_test_cluster() creates the test cluster through kubetest. See https://github.com/knative/test-infra/blob/master/scripts/e2e-tests.sh for details.

/close
