### ISSUE TITLE
PROW_JOB_ID should not be required

### ISSUE THREAD

**Issue by scothis** [knative/test-infra#93]
Running the update-codegen.sh script from eventing fails because `PROW_JOB_ID` is unbounded. This var should have a default automatically set when not running on prow.

```shell
$ ./hack/update-codegen.sh
./hack/../vendor/github.com/knative/test-infra/scripts/library.sh: line 32: PROW_JOB_ID: unbound variable
```

**Comment by adrcunha** [comment]
https://github.com/knative/serving/pull/1975 fixes the serving repo.

**Comment by adrcunha** [comment]
https://github.com/knative/eventing/pull/413 fixes the eventing repo.

**Comment by dprotaso** [comment]
https://github.com/knative/build/pull/327 fixes it for build repo

**Comment by adrcunha** [comment]
https://github.com/knative/pkg/pull/61 fixes the pkg repo

**Comment by adrcunha** [comment]
https://github.com/knative/build-templates/pull/62 fixes the build-templates repo

**Comment by adrcunha** [comment]
https://github.com/knative/docs/pull/371 fixes the docs repo.
