### ISSUE TITLE
Investigate why it takes janitor ~40 minutes cleaning up Boskos project

### ISSUE THREAD

**Issue by chaodaiG** [knative/test-infra#946]
There has been a few times that Boskos ran out of resources, and often found out that majority of the projects were waiting to be cleaned. After some initial investigation, it looks like the cleaning up of Boskos project isn't very efficient.

Inspected Janitor log after a Boskos project done with an integration test from a pull request in test-infra, it took ~40 minutes for Janitor to completely clean it up.

Example job link: https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_test-infra/944/pull-knative-test-infra-integration-tests/1140657826260062209/?log#log
Example Janitor link: https://pantheon.corp.google.com/logs/viewer?project=knative-tests&resource=container%2Fcluster_name%2Fprow%2Fnamespace_id%2Fdefault&minLogLevel=0&expandAll=false&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22prow%22%0Aresource.labels.namespace_id:%20%22test-pods%22%0A%22knative-boskos-25%22%0ANOT%20%22knative-boskos-26%22%0AjsonPayload.level%3D%22info%22&timestamp=2019-06-17T17:48:40.939000000Z&scrollTimestamp=2019-06-17T17:43:04.000000000Z&customFacets=jsonPayload.component,jsonPayload.level&limitCustomFacetWidth=false&dateRangeStart=2019-06-17T11:48:41.190Z&interval=PT6H&dateRangeEnd=2019-06-17T17:48:41.190Z

**Comment by chaodaiG** [comment]
This might not be true any more. Just checked 2 Boskos projects finished this morning, Janitor took [17 minutes](https://pantheon.corp.google.com/logs/viewer?project=knative-tests&minLogLevel=0&expandAll=false&customFacets=jsonPayload.component,jsonPayload.level&limitCustomFacetWidth=false&interval=CUSTOM&resource=container%2Fcluster_name%2Fprow%2Fnamespace_id%2Fdefault&timestamp=2019-06-28T14:39:50.966000000Z&advancedFilter=%22janitor%22%0A%22knative-boskos-10%22%0ANOT%20%22knative-boskos-11%22&dateRangeStart=2019-06-28T12:00:00.218Z&scrollTimestamp=2019-06-28T14:30:21.000000000Z&dateRangeEnd=2019-06-28T14:39:51.218Z) cleaning up after test-infra e2e tests, and [20 minutes](https://pantheon.corp.google.com/logs/viewer?project=knative-tests&minLogLevel=0&expandAll=false&customFacets=jsonPayload.component,jsonPayload.level&limitCustomFacetWidth=false&interval=CUSTOM&resource=container%2Fcluster_name%2Fprow%2Fnamespace_id%2Fdefault&timestamp=2019-06-28T14:36:23.322000000Z&advancedFilter=%22janitor%22%0A%22knative-boskos-46%22%0ANOT%20%22knative-boskos-11%22&dateRangeStart=2019-06-28T12:00:00.662Z&scrollTimestamp=2019-06-28T12:55:18.000000000Z&dateRangeUnbound=forwardInTime) after serving e2e tests. 

Will need to have more data though, FYI @coryrc

**Comment by chaodaiG** [comment]
Janitor log timestamp was merged 06/28 https://github.com/kubernetes/test-infra/pull/13256, we can get more information out of Janitor log when we update to use Janitor released later than 06/28

**Comment by chaodaiG** [comment]
After `--verbose` turned on for janitor, there are more info:
going to delete 1 networks

start a new thread, total 1

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/northamerica-northeast1']

going to delete 1 networks

start a new thread, total 2

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/us-west1']

going to delete 1 networks

start a new thread, total 3

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/us-west2']

going to delete 1 networks

start a new thread, total 4

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/us-east1']

going to delete 1 networks

start a new thread, total 5

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/australia-southeast1']

going to delete 1 networks

start a new thread, total 6

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/us-east4']

going to delete 1 networks

start a new thread, total 7

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/asia-east2']

going to delete 1 networks

start a new thread, total 8

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/coERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
 - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.

Error try to delete resources networks: CalledProcessError()
Error try to delete resources networks: CalledProcessError()
mpute/v1/projects/knative-boskos-46/regions/asia-east1']

going to delete 1 networks

start a new thread, total 9

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/asia-southeast1']

going to delete 1 networks

start a new thread, total 10

going to delete 1 networks

start a new thread, total 11

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/us-central1']

going to delete 1 networks

start a new thread, total 12

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/asia-northeast2']

going to delete 1 networks

start a new thread, total 13

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/europe-west3']

going to delete 1 networks

start a new thread, total 14

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/asia-northeast1']

going to delete 1 networks

start a new thread, total 15

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/europe-west6']

going to delete 1 networks

start a new thread, total 16

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/europe-west4']

going to delete 1 networks

start a new thread, total 17

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/europe-west1']

going to delete 1 networks

start a new thread, total 18

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/southamerica-east1']

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/europe-north1']

going to delete 1 networks

start a new thread, total 19

going to delete 1 networks

start a new thread, total 20

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/europe-west2']

Waiting for all 20 thread to finish

Call ['gcloud', 'compute', '-q', 'networks', 'subnets', 'delete', '--project=knative-boskos-46', u'kserving-e2e-net1149389537487622146', u'--region=https://www.googleapis.com/compute/v1/projects/knative-boskos-46/regions/asia-south1']

Try to search for 'networks' with condition ''

['gcloud', 'compute', '-q', 'networks', 'list', '--format=json(name,creationTimestamp.date(tz=UTC),zone,region,isManaged)', '--filter=name !~ ^default', '--project=knative-boskos-46']

parsing item: {u'creationTimestamp': u'2019-07-11T18:53:20', u'name': u'kserving-e2e-net1149389537487622146'}

going to delete 1 networks

start a new thread, total 1

Call ['gcloud', 'compute', '-q', 'networks', 'dERROR: (gcloud.compute.networks.delete) Could not fetch resource:
 - The network resource 'projects/knative-boskos-46/global/networks/kserving-e2e-net1149389537487622146' is already being used by 'projects/knative-boskos-46/regions/us-central1/subnetworks/kserving-e2e-net1149389537487622146'

Error try to delete resources networks: CalledProcessError()
ERROR: (gcloud.container.clusters.list) ResponseError: code=404, message=Not Found.

**Comment by chaodaiG** [comment]
The cause was janitor not properly cleaning up "auto" subnet, which was produced by default when using kubetest creating cluster: https://github.com/kubernetes/test-infra/blob/4de0259d8729e8f5fa654e57cebd128bf944f49c/kubetest/gke.go#L281

**Comment by chaodaiG** [comment]
> The cause was janitor not properly cleaning up "auto" subnet, which was produced by default when using kubetest creating cluster: https://github.com/kubernetes/test-infra/blob/4de0259d8729e8f5fa654e57cebd128bf944f49c/kubetest/gke.go#L281

@krzyzacy for reference

**Comment by adrcunha** [comment]
I'm closing this issue as the goal was achieved: we know why janitor sometimes take a long time to clean up projects. Fixing it requires at least modifying kubetest, which is not in our list of priorities right now.

/close

**Comment by coryrc** [comment]
I identified the real problem and got it fixed here: https://github.com/kubernetes/test-infra/pull/16353
