### ISSUE TITLE
Issue for two projects using different version of dependencies

### ISSUE THREAD

**Issue by Fredy-Z** [knative/test-infra#957]
When I worked with `eventing` project, I met a dependency issue, but I'm not sure what is the best practice to solve it. So I create an issue here to keep a record.

The problem and steps to reproduce are described as below:
Both `eventing` and `test-infra` depend on `cloud.google.com/go`, but the versions are different - `v0.39.0` for `eventing` and `v0.33.1` for `test-infra`.
In `test-infra`, only code under `shared` directory is referencing code in `cloud.google.com/go`, so it worked fine if `eventing` do not use code in `test-infra/shared`.
But then I wanted to use `test-infra/shared` in `eventing`, both projects would have to depend on `cloud.google.com/go` `v0.39.0`. However, this version is not compatible with the transitive dependencies `test-infra` relies on - `google.golang.org/api` and `google.golang.org/grpc`, and things become more complicated as the two are also transitive dependencies of `eventing`, but different versions.

This issue happened when I tried to add `test-infra/shared` as a dependency in `eventing`, so I think it should be solved in `test-infra`. I created #956 as an attempt, but I'm not sure if it's the best practice.

This issue leads me to think about a scenario that seems even more annoying:
What if `test-infra` uses a function that exists in `cloud.google.com/go` `v0.33.1` but not in `v0.39.0`? Then `eventing` will not be able to use `test-infra/shared` anymore. And `serving` will not be able to update `cloud.google.com/go` to `v0.39.0`, as it's currently using `test-infra/shared`.

**Comment by adrcunha** [comment]
I think this is outside the scope of Productivity WG, and more a matter of regular golang dep best practices.
