### ISSUE TITLE
old fortio redirects are broken

### ISSUE THREAD

**Issue by mattmoor** [knative/test-infra#968]
/assign @srinivashegde86 
cc @dushyanthsc 

This change removed the `go-import` `<meta>` tags that made the old versions work, `test-infra` needs to move to the `fortio.org` based import paths ASAP.

https://github.com/istio/istio.io/commit/4d03f086f049df9751620601d68abcbcc32e37e4#diff-e3202d59ce8d9d83b8911b4107f87c1e

cc @geeknoid

**Comment by mattmoor** [comment]
This is an indirect dependency for Serving, so once it is fixed in test-infra, I'd like to verify that my auto-update works for serving.

**Comment by geeknoid** [comment]
Let me know if you'd like me to reinstate the links for a while.

**Comment by mattmoor** [comment]
The version of `fortio` we are on is very old, so I think we need to solve this.  If we can't figure it out today, we might reach out about that though. :)  thanks @geeknoid

**Comment by srinivashegde86** [comment]
The sample example mentioned in their docs still uses istio.io - https://github.com/istio/istio/blob/0.3.0/tests/e2e/tests/mixer/mixer_test.go#L37

**Comment by srinivashegde86** [comment]
Moving to fortio.org fails with "unexpected error while defensively cleaning up after possible derelict nested submodule directories: Entering 'vendor' error: unknown switch `x'"

there was a recent PR in dep when working with submodules - https://github.com/golang/dep/pull/2176. Probably related

**Comment by dushyanthsc** [comment]
To close the loop here, pinning to a 1.3.1 commit and `dep ensure` updates the packages correctly. `dep ensure -update fortio.org/fortio`, tries to pull the latest on fortio and is failing with 

```
 failed to fetch source for fortio.org/fortio: unable to update repository: From https://github.com/fortio/fortio
 ! [rejected]        latest_release -> latest_release  (would clobber existing tag)
: command failed: [git fetch --tags --prune origin]: signal: interrupt
```
