### ISSUE TITLE
presubmit checks should ensure Gopkg.lock was created with some minimal version of dep

### ISSUE THREAD

**Issue by dprotaso** [knative/test-infra#97]
If a contributor has an older version of dep there may be unnecessary edits to `Gopkg.lock` when opening a PR.  Future PRs from other contributors with a newer version of dep may change the lock file. This thrashing is noisy.

It'd be nice if we could enforce a minimal version of dep as part of the presubmit checks.

Latest release at this time is v0.5.0 
https://github.com/golang/dep/releases

**Comment by adrcunha** [comment]
Is there a canonical way of knowing what's `dep` version? Mine was installed through `go get` and reports no numeric version :(

```
$ dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : devel +b8669ef1ce
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

**Comment by adrcunha** [comment]
For the record, the prow jobs use the latest `dep`.

**Comment by dprotaso** [comment]
I updated the title & body reflect my expectations of having some presubmit checks to prevent thrashing of the `Gopkg.lock` file

The specific version of dep matters less - just that whatever contributors is consistent.

**Comment by adrcunha** [comment]
I understand the goal, but I'm still unsure how clean/reliably such check can be performed. `Gopkg.lock` contains no version information, `dep status` and `dep check` won't complain about missing fields in the lock file (e.g., `digest`), and simply grepping the lock file for `digest` (or any other field) is too brittle and hackish... :/

**Comment by jessiezcc** [comment]
Closing per staleness
